export interface CommonFood {
  id: string;
  name: string;
  category: "protein" | "dairy" | "grain" | "fruit" | "vegetable" | "fat" | "beverage" | "snack" | "condiment";
  servingSize: number;      // grams
  servingUnit: string;      // "large egg", "cup", "oz", etc.
  servingLabel: string;     // "1 large egg (50g)"
  calories: number;         // per serving
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  caloriesPerGram: number;
  proteinPerGram: number;
  carbsPerGram: number;
  fatPerGram: number;
  fiberPerGram: number;
  aliases: string[];
}

export const commonFoods: CommonFood[] = [
  // ─── Proteins ───────────────────────────────────────────────
  {
    id: "egg-whole",
    name: "Egg (whole, large)",
    category: "protein",
    servingSize: 50,
    servingUnit: "large egg",
    servingLabel: "1 large egg (50g)",
    calories: 72, protein: 6.3, carbs: 0.4, fat: 4.8, fiber: 0,
    caloriesPerGram: 1.440, proteinPerGram: 0.126, carbsPerGram: 0.008, fatPerGram: 0.096, fiberPerGram: 0,
    aliases: ["egg", "eggs", "whole egg", "boiled egg", "fried egg", "scrambled egg"],
  },
  {
    id: "egg-white",
    name: "Egg White",
    category: "protein",
    servingSize: 33,
    servingUnit: "large egg white",
    servingLabel: "1 large egg white (33g)",
    calories: 17, protein: 3.6, carbs: 0.2, fat: 0.1, fiber: 0,
    caloriesPerGram: 0.515, proteinPerGram: 0.109, carbsPerGram: 0.006, fatPerGram: 0.003, fiberPerGram: 0,
    aliases: ["egg white", "egg whites"],
  },
  {
    id: "chicken-breast",
    name: "Chicken Breast (cooked, no skin)",
    category: "protein",
    servingSize: 120,
    servingUnit: "4 oz",
    servingLabel: "4 oz / 120g",
    calories: 187, protein: 35.2, carbs: 0, fat: 4.1, fiber: 0,
    caloriesPerGram: 1.558, proteinPerGram: 0.293, carbsPerGram: 0, fatPerGram: 0.034, fiberPerGram: 0,
    aliases: ["chicken breast", "chicken", "grilled chicken", "baked chicken"],
  },
  {
    id: "chicken-thigh",
    name: "Chicken Thigh (cooked, no skin)",
    category: "protein",
    servingSize: 116,
    servingUnit: "thigh",
    servingLabel: "1 thigh (116g)",
    calories: 229, protein: 28.3, carbs: 0, fat: 12.1, fiber: 0,
    caloriesPerGram: 1.974, proteinPerGram: 0.244, carbsPerGram: 0, fatPerGram: 0.104, fiberPerGram: 0,
    aliases: ["chicken thigh", "dark meat chicken"],
  },
  {
    id: "ground-beef",
    name: "Ground Beef (90% lean, cooked)",
    category: "protein",
    servingSize: 113,
    servingUnit: "4 oz",
    servingLabel: "4 oz / 113g",
    calories: 200, protein: 28.5, carbs: 0, fat: 9.1, fiber: 0,
    caloriesPerGram: 1.770, proteinPerGram: 0.252, carbsPerGram: 0, fatPerGram: 0.081, fiberPerGram: 0,
    aliases: ["ground beef", "beef", "hamburger meat"],
  },
  {
    id: "sirloin-steak",
    name: "Sirloin Steak (cooked)",
    category: "protein",
    servingSize: 113,
    servingUnit: "4 oz",
    servingLabel: "4 oz / 113g",
    calories: 207, protein: 33.8, carbs: 0, fat: 7.1, fiber: 0,
    caloriesPerGram: 1.832, proteinPerGram: 0.299, carbsPerGram: 0, fatPerGram: 0.063, fiberPerGram: 0,
    aliases: ["steak", "sirloin"],
  },
  {
    id: "salmon",
    name: "Salmon Fillet (cooked)",
    category: "protein",
    servingSize: 113,
    servingUnit: "4 oz",
    servingLabel: "4 oz / 113g",
    calories: 234, protein: 25, carbs: 0, fat: 14.2, fiber: 0,
    caloriesPerGram: 2.071, proteinPerGram: 0.221, carbsPerGram: 0, fatPerGram: 0.126, fiberPerGram: 0,
    aliases: ["salmon", "grilled salmon", "baked salmon"],
  },
  {
    id: "tuna-canned",
    name: "Tuna (canned in water)",
    category: "protein",
    servingSize: 85,
    servingUnit: "can",
    servingLabel: "1 can (85g)",
    calories: 73, protein: 16.5, carbs: 0, fat: 0.6, fiber: 0,
    caloriesPerGram: 0.859, proteinPerGram: 0.194, carbsPerGram: 0, fatPerGram: 0.007, fiberPerGram: 0,
    aliases: ["tuna", "canned tuna"],
  },
  {
    id: "turkey-breast",
    name: "Turkey Breast (cooked)",
    category: "protein",
    servingSize: 113,
    servingUnit: "4 oz",
    servingLabel: "4 oz / 113g",
    calories: 153, protein: 34, carbs: 0, fat: 0.8, fiber: 0,
    caloriesPerGram: 1.354, proteinPerGram: 0.301, carbsPerGram: 0, fatPerGram: 0.007, fiberPerGram: 0,
    aliases: ["turkey", "turkey breast", "deli turkey"],
  },
  {
    id: "shrimp",
    name: "Shrimp (cooked)",
    category: "protein",
    servingSize: 85,
    servingUnit: "3 oz",
    servingLabel: "3 oz / 85g",
    calories: 84, protein: 20.4, carbs: 0.2, fat: 0.2, fiber: 0,
    caloriesPerGram: 0.988, proteinPerGram: 0.240, carbsPerGram: 0.002, fatPerGram: 0.002, fiberPerGram: 0,
    aliases: ["shrimp", "prawns"],
  },
  {
    id: "tilapia",
    name: "Tilapia (cooked)",
    category: "protein",
    servingSize: 113,
    servingUnit: "4 oz",
    servingLabel: "4 oz / 113g",
    calories: 145, protein: 30, carbs: 0, fat: 2.5, fiber: 0,
    caloriesPerGram: 1.283, proteinPerGram: 0.265, carbsPerGram: 0, fatPerGram: 0.022, fiberPerGram: 0,
    aliases: ["tilapia", "white fish"],
  },
  {
    id: "bacon",
    name: "Bacon (cooked)",
    category: "protein",
    servingSize: 24,
    servingUnit: "3 slices",
    servingLabel: "3 slices (24g)",
    calories: 129, protein: 9, carbs: 0.4, fat: 9.9, fiber: 0,
    caloriesPerGram: 5.375, proteinPerGram: 0.375, carbsPerGram: 0.017, fatPerGram: 0.413, fiberPerGram: 0,
    aliases: ["bacon", "bacon strips"],
  },
  {
    id: "pork-chop",
    name: "Pork Chop (cooked)",
    category: "protein",
    servingSize: 113,
    servingUnit: "4 oz",
    servingLabel: "4 oz / 113g",
    calories: 231, protein: 31, carbs: 0, fat: 11.1, fiber: 0,
    caloriesPerGram: 2.044, proteinPerGram: 0.274, carbsPerGram: 0, fatPerGram: 0.098, fiberPerGram: 0,
    aliases: ["pork chop", "pork"],
  },
  {
    id: "tofu",
    name: "Tofu (firm)",
    category: "protein",
    servingSize: 126,
    servingUnit: "1/2 cup",
    servingLabel: "1/2 cup (126g)",
    calories: 88, protein: 10, carbs: 2.2, fat: 5.3, fiber: 0.4,
    caloriesPerGram: 0.698, proteinPerGram: 0.079, carbsPerGram: 0.017, fatPerGram: 0.042, fiberPerGram: 0.003,
    aliases: ["tofu", "bean curd"],
  },
  {
    id: "tempeh",
    name: "Tempeh",
    category: "protein",
    servingSize: 84,
    servingUnit: "3 oz",
    servingLabel: "3 oz (84g)",
    calories: 162, protein: 15.4, carbs: 9, fat: 9, fiber: 0,
    caloriesPerGram: 1.929, proteinPerGram: 0.183, carbsPerGram: 0.107, fatPerGram: 0.107, fiberPerGram: 0,
    aliases: ["tempeh"],
  },

  // ─── Dairy ──────────────────────────────────────────────────
  {
    id: "greek-yogurt",
    name: "Greek Yogurt (plain, nonfat)",
    category: "dairy",
    servingSize: 170,
    servingUnit: "6 oz",
    servingLabel: "6 oz (170g)",
    calories: 100, protein: 17, carbs: 6, fat: 0.7, fiber: 0,
    caloriesPerGram: 0.588, proteinPerGram: 0.100, carbsPerGram: 0.035, fatPerGram: 0.004, fiberPerGram: 0,
    aliases: ["greek yogurt", "yogurt", "plain yogurt"],
  },
  {
    id: "whole-milk",
    name: "Whole Milk",
    category: "dairy",
    servingSize: 244,
    servingUnit: "cup",
    servingLabel: "1 cup (244ml)",
    calories: 149, protein: 8, carbs: 12, fat: 8, fiber: 0,
    caloriesPerGram: 0.611, proteinPerGram: 0.033, carbsPerGram: 0.049, fatPerGram: 0.033, fiberPerGram: 0,
    aliases: ["whole milk", "milk"],
  },
  {
    id: "skim-milk",
    name: "Skim Milk",
    category: "dairy",
    servingSize: 244,
    servingUnit: "cup",
    servingLabel: "1 cup (244ml)",
    calories: 83, protein: 8.3, carbs: 12.2, fat: 0.2, fiber: 0,
    caloriesPerGram: 0.340, proteinPerGram: 0.034, carbsPerGram: 0.050, fatPerGram: 0.001, fiberPerGram: 0,
    aliases: ["skim milk", "fat free milk", "nonfat milk"],
  },
  {
    id: "cheddar-cheese",
    name: "Cheddar Cheese",
    category: "dairy",
    servingSize: 28,
    servingUnit: "oz",
    servingLabel: "1 oz (28g)",
    calories: 113, protein: 7, carbs: 0.4, fat: 9.3, fiber: 0,
    caloriesPerGram: 4.036, proteinPerGram: 0.250, carbsPerGram: 0.014, fatPerGram: 0.332, fiberPerGram: 0,
    aliases: ["cheddar", "cheese", "american cheese"],
  },
  {
    id: "mozzarella-cheese",
    name: "Mozzarella Cheese",
    category: "dairy",
    servingSize: 28,
    servingUnit: "oz",
    servingLabel: "1 oz (28g)",
    calories: 85, protein: 6.3, carbs: 0.7, fat: 6.3, fiber: 0,
    caloriesPerGram: 3.036, proteinPerGram: 0.225, carbsPerGram: 0.025, fatPerGram: 0.225, fiberPerGram: 0,
    aliases: ["mozzarella", "mozz"],
  },
  {
    id: "cottage-cheese",
    name: "Cottage Cheese (low-fat)",
    category: "dairy",
    servingSize: 113,
    servingUnit: "1/2 cup",
    servingLabel: "1/2 cup (113g)",
    calories: 81, protein: 14, carbs: 3.2, fat: 1.2, fiber: 0,
    caloriesPerGram: 0.717, proteinPerGram: 0.124, carbsPerGram: 0.028, fatPerGram: 0.011, fiberPerGram: 0,
    aliases: ["cottage cheese"],
  },
  {
    id: "cream-cheese",
    name: "Cream Cheese",
    category: "dairy",
    servingSize: 28,
    servingUnit: "oz",
    servingLabel: "1 oz (28g)",
    calories: 99, protein: 1.7, carbs: 1.6, fat: 9.8, fiber: 0,
    caloriesPerGram: 3.536, proteinPerGram: 0.061, carbsPerGram: 0.057, fatPerGram: 0.350, fiberPerGram: 0,
    aliases: ["cream cheese"],
  },
  {
    id: "whey-protein",
    name: "Whey Protein Powder",
    category: "dairy",
    servingSize: 31,
    servingUnit: "scoop",
    servingLabel: "1 scoop (31g)",
    calories: 120, protein: 24, carbs: 3, fat: 1.5, fiber: 0,
    caloriesPerGram: 3.871, proteinPerGram: 0.774, carbsPerGram: 0.097, fatPerGram: 0.048, fiberPerGram: 0,
    aliases: ["whey protein", "protein powder", "protein shake"],
  },
  {
    id: "butter",
    name: "Butter",
    category: "dairy",
    servingSize: 14,
    servingUnit: "tbsp",
    servingLabel: "1 tbsp (14g)",
    calories: 102, protein: 0.1, carbs: 0, fat: 11.5, fiber: 0,
    caloriesPerGram: 7.286, proteinPerGram: 0.007, carbsPerGram: 0, fatPerGram: 0.821, fiberPerGram: 0,
    aliases: ["butter"],
  },
  {
    id: "parmesan-cheese",
    name: "Parmesan Cheese",
    category: "dairy",
    servingSize: 28,
    servingUnit: "oz",
    servingLabel: "1 oz (28g)",
    calories: 110, protein: 10, carbs: 0.9, fat: 7.3, fiber: 0,
    caloriesPerGram: 3.929, proteinPerGram: 0.357, carbsPerGram: 0.032, fatPerGram: 0.261, fiberPerGram: 0,
    aliases: ["parmesan", "parm"],
  },

  // ─── Grains ─────────────────────────────────────────────────
  {
    id: "white-rice",
    name: "White Rice (cooked)",
    category: "grain",
    servingSize: 158,
    servingUnit: "cup",
    servingLabel: "1 cup (158g)",
    calories: 206, protein: 4.3, carbs: 44.5, fat: 0.4, fiber: 0.6,
    caloriesPerGram: 1.304, proteinPerGram: 0.027, carbsPerGram: 0.282, fatPerGram: 0.003, fiberPerGram: 0.004,
    aliases: ["white rice", "rice", "steamed rice"],
  },
  {
    id: "brown-rice",
    name: "Brown Rice (cooked)",
    category: "grain",
    servingSize: 195,
    servingUnit: "cup",
    servingLabel: "1 cup (195g)",
    calories: 218, protein: 4.5, carbs: 45.8, fat: 1.6, fiber: 3.5,
    caloriesPerGram: 1.118, proteinPerGram: 0.023, carbsPerGram: 0.235, fatPerGram: 0.008, fiberPerGram: 0.018,
    aliases: ["brown rice"],
  },
  {
    id: "oatmeal",
    name: "Oatmeal (cooked)",
    category: "grain",
    servingSize: 234,
    servingUnit: "cup",
    servingLabel: "1 cup (234g)",
    calories: 154, protein: 5.4, carbs: 27.4, fat: 2.6, fiber: 4,
    caloriesPerGram: 0.658, proteinPerGram: 0.023, carbsPerGram: 0.117, fatPerGram: 0.011, fiberPerGram: 0.017,
    aliases: ["oatmeal", "oats", "porridge"],
  },
  {
    id: "whole-wheat-bread",
    name: "Whole Wheat Bread",
    category: "grain",
    servingSize: 32,
    servingUnit: "slice",
    servingLabel: "1 slice (32g)",
    calories: 82, protein: 4, carbs: 13.8, fat: 1.1, fiber: 1.9,
    caloriesPerGram: 2.563, proteinPerGram: 0.125, carbsPerGram: 0.431, fatPerGram: 0.034, fiberPerGram: 0.059,
    aliases: ["bread", "wheat bread", "toast"],
  },
  {
    id: "white-bread",
    name: "White Bread",
    category: "grain",
    servingSize: 25,
    servingUnit: "slice",
    servingLabel: "1 slice (25g)",
    calories: 67, protein: 1.9, carbs: 12.7, fat: 0.8, fiber: 0.6,
    caloriesPerGram: 2.680, proteinPerGram: 0.076, carbsPerGram: 0.508, fatPerGram: 0.032, fiberPerGram: 0.024,
    aliases: ["white bread"],
  },
  {
    id: "pasta",
    name: "Pasta (cooked)",
    category: "grain",
    servingSize: 140,
    servingUnit: "cup",
    servingLabel: "1 cup (140g)",
    calories: 220, protein: 8.1, carbs: 43.2, fat: 1.3, fiber: 2.5,
    caloriesPerGram: 1.571, proteinPerGram: 0.058, carbsPerGram: 0.309, fatPerGram: 0.009, fiberPerGram: 0.018,
    aliases: ["pasta", "spaghetti", "penne", "noodles"],
  },
  {
    id: "bagel",
    name: "Plain Bagel",
    category: "grain",
    servingSize: 105,
    servingUnit: "bagel",
    servingLabel: "1 bagel (105g)",
    calories: 270, protein: 10, carbs: 53, fat: 1.5, fiber: 2.3,
    caloriesPerGram: 2.571, proteinPerGram: 0.095, carbsPerGram: 0.505, fatPerGram: 0.014, fiberPerGram: 0.022,
    aliases: ["bagel", "plain bagel"],
  },
  {
    id: "flour-tortilla",
    name: "Flour Tortilla (large)",
    category: "grain",
    servingSize: 64,
    servingUnit: "tortilla",
    servingLabel: "1 large tortilla (64g)",
    calories: 200, protein: 5, carbs: 33, fat: 5.5, fiber: 1.5,
    caloriesPerGram: 3.125, proteinPerGram: 0.078, carbsPerGram: 0.516, fatPerGram: 0.086, fiberPerGram: 0.023,
    aliases: ["tortilla", "wrap", "burrito wrap"],
  },
  {
    id: "quinoa",
    name: "Quinoa (cooked)",
    category: "grain",
    servingSize: 185,
    servingUnit: "cup",
    servingLabel: "1 cup (185g)",
    calories: 222, protein: 8.1, carbs: 39.4, fat: 3.6, fiber: 5.2,
    caloriesPerGram: 1.200, proteinPerGram: 0.044, carbsPerGram: 0.213, fatPerGram: 0.019, fiberPerGram: 0.028,
    aliases: ["quinoa"],
  },
  {
    id: "english-muffin",
    name: "English Muffin",
    category: "grain",
    servingSize: 57,
    servingUnit: "muffin",
    servingLabel: "1 muffin (57g)",
    calories: 132, protein: 5.1, carbs: 25.6, fat: 1, fiber: 1.5,
    caloriesPerGram: 2.316, proteinPerGram: 0.089, carbsPerGram: 0.449, fatPerGram: 0.018, fiberPerGram: 0.026,
    aliases: ["english muffin"],
  },
  {
    id: "granola",
    name: "Granola",
    category: "grain",
    servingSize: 55,
    servingUnit: "1/2 cup",
    servingLabel: "1/2 cup (55g)",
    calories: 260, protein: 6, carbs: 38, fat: 10, fiber: 3.5,
    caloriesPerGram: 4.727, proteinPerGram: 0.109, carbsPerGram: 0.691, fatPerGram: 0.182, fiberPerGram: 0.064,
    aliases: ["granola"],
  },

  // ─── Fruits ─────────────────────────────────────────────────
  {
    id: "banana",
    name: "Banana",
    category: "fruit",
    servingSize: 118,
    servingUnit: "medium banana",
    servingLabel: "1 medium (118g)",
    calories: 105, protein: 1.3, carbs: 27, fat: 0.4, fiber: 3.1,
    caloriesPerGram: 0.890, proteinPerGram: 0.011, carbsPerGram: 0.229, fatPerGram: 0.003, fiberPerGram: 0.026,
    aliases: ["banana", "bananas"],
  },
  {
    id: "apple",
    name: "Apple",
    category: "fruit",
    servingSize: 182,
    servingUnit: "medium apple",
    servingLabel: "1 medium (182g)",
    calories: 95, protein: 0.5, carbs: 25.1, fat: 0.3, fiber: 4.4,
    caloriesPerGram: 0.522, proteinPerGram: 0.003, carbsPerGram: 0.138, fatPerGram: 0.002, fiberPerGram: 0.024,
    aliases: ["apple", "apples"],
  },
  {
    id: "blueberries",
    name: "Blueberries",
    category: "fruit",
    servingSize: 148,
    servingUnit: "cup",
    servingLabel: "1 cup (148g)",
    calories: 84, protein: 1.1, carbs: 21.4, fat: 0.5, fiber: 3.6,
    caloriesPerGram: 0.568, proteinPerGram: 0.007, carbsPerGram: 0.145, fatPerGram: 0.003, fiberPerGram: 0.024,
    aliases: ["blueberries", "blueberry"],
  },
  {
    id: "strawberries",
    name: "Strawberries",
    category: "fruit",
    servingSize: 152,
    servingUnit: "cup",
    servingLabel: "1 cup (152g)",
    calories: 49, protein: 1, carbs: 11.7, fat: 0.5, fiber: 3,
    caloriesPerGram: 0.322, proteinPerGram: 0.007, carbsPerGram: 0.077, fatPerGram: 0.003, fiberPerGram: 0.020,
    aliases: ["strawberries", "strawberry"],
  },
  {
    id: "orange",
    name: "Orange",
    category: "fruit",
    servingSize: 131,
    servingUnit: "medium orange",
    servingLabel: "1 medium (131g)",
    calories: 62, protein: 1.2, carbs: 15.4, fat: 0.2, fiber: 3.1,
    caloriesPerGram: 0.473, proteinPerGram: 0.009, carbsPerGram: 0.118, fatPerGram: 0.002, fiberPerGram: 0.024,
    aliases: ["orange", "oranges"],
  },
  {
    id: "grapes",
    name: "Grapes",
    category: "fruit",
    servingSize: 92,
    servingUnit: "cup",
    servingLabel: "1 cup (92g)",
    calories: 62, protein: 0.6, carbs: 16.3, fat: 0.3, fiber: 0.8,
    caloriesPerGram: 0.674, proteinPerGram: 0.007, carbsPerGram: 0.177, fatPerGram: 0.003, fiberPerGram: 0.009,
    aliases: ["grapes"],
  },
  {
    id: "mango",
    name: "Mango",
    category: "fruit",
    servingSize: 165,
    servingUnit: "cup",
    servingLabel: "1 cup (165g)",
    calories: 99, protein: 1.4, carbs: 24.7, fat: 0.6, fiber: 2.6,
    caloriesPerGram: 0.600, proteinPerGram: 0.008, carbsPerGram: 0.150, fatPerGram: 0.004, fiberPerGram: 0.016,
    aliases: ["mango"],
  },
  {
    id: "watermelon",
    name: "Watermelon",
    category: "fruit",
    servingSize: 152,
    servingUnit: "cup",
    servingLabel: "1 cup (152g)",
    calories: 46, protein: 0.9, carbs: 11.5, fat: 0.2, fiber: 0.6,
    caloriesPerGram: 0.303, proteinPerGram: 0.006, carbsPerGram: 0.076, fatPerGram: 0.001, fiberPerGram: 0.004,
    aliases: ["watermelon"],
  },

  // ─── Vegetables ─────────────────────────────────────────────
  {
    id: "broccoli",
    name: "Broccoli (cooked)",
    category: "vegetable",
    servingSize: 156,
    servingUnit: "cup",
    servingLabel: "1 cup (156g)",
    calories: 55, protein: 3.7, carbs: 11.2, fat: 0.6, fiber: 5.1,
    caloriesPerGram: 0.353, proteinPerGram: 0.024, carbsPerGram: 0.072, fatPerGram: 0.004, fiberPerGram: 0.033,
    aliases: ["broccoli"],
  },
  {
    id: "spinach",
    name: "Spinach (raw)",
    category: "vegetable",
    servingSize: 30,
    servingUnit: "cup",
    servingLabel: "1 cup (30g)",
    calories: 7, protein: 0.9, carbs: 1.1, fat: 0.1, fiber: 0.7,
    caloriesPerGram: 0.233, proteinPerGram: 0.030, carbsPerGram: 0.037, fatPerGram: 0.003, fiberPerGram: 0.023,
    aliases: ["spinach", "baby spinach"],
  },
  {
    id: "sweet-potato",
    name: "Sweet Potato (baked)",
    category: "vegetable",
    servingSize: 114,
    servingUnit: "medium",
    servingLabel: "1 medium (114g)",
    calories: 103, protein: 2.3, carbs: 24, fat: 0.1, fiber: 3.8,
    caloriesPerGram: 0.904, proteinPerGram: 0.020, carbsPerGram: 0.211, fatPerGram: 0.001, fiberPerGram: 0.033,
    aliases: ["sweet potato", "yam"],
  },
  {
    id: "white-potato",
    name: "White Potato (baked)",
    category: "vegetable",
    servingSize: 173,
    servingUnit: "medium",
    servingLabel: "1 medium (173g)",
    calories: 161, protein: 4.3, carbs: 36.6, fat: 0.2, fiber: 3.8,
    caloriesPerGram: 0.931, proteinPerGram: 0.025, carbsPerGram: 0.212, fatPerGram: 0.001, fiberPerGram: 0.022,
    aliases: ["potato", "baked potato"],
  },
  {
    id: "avocado",
    name: "Avocado",
    category: "vegetable",
    servingSize: 68,
    servingUnit: "half",
    servingLabel: "1/2 avocado (68g)",
    calories: 114, protein: 1.3, carbs: 6, fat: 10.5, fiber: 4.6,
    caloriesPerGram: 1.676, proteinPerGram: 0.019, carbsPerGram: 0.088, fatPerGram: 0.154, fiberPerGram: 0.068,
    aliases: ["avocado", "avo"],
  },
  {
    id: "cucumber",
    name: "Cucumber",
    category: "vegetable",
    servingSize: 52,
    servingUnit: "1/2 cup",
    servingLabel: "1/2 cup (52g)",
    calories: 8, protein: 0.3, carbs: 1.9, fat: 0.1, fiber: 0.3,
    caloriesPerGram: 0.154, proteinPerGram: 0.006, carbsPerGram: 0.037, fatPerGram: 0.002, fiberPerGram: 0.006,
    aliases: ["cucumber"],
  },
  {
    id: "tomato",
    name: "Tomato",
    category: "vegetable",
    servingSize: 123,
    servingUnit: "medium",
    servingLabel: "1 medium (123g)",
    calories: 22, protein: 1.1, carbs: 4.8, fat: 0.2, fiber: 1.5,
    caloriesPerGram: 0.179, proteinPerGram: 0.009, carbsPerGram: 0.039, fatPerGram: 0.002, fiberPerGram: 0.012,
    aliases: ["tomato", "tomatoes"],
  },
  {
    id: "lettuce",
    name: "Lettuce (romaine)",
    category: "vegetable",
    servingSize: 47,
    servingUnit: "cup",
    servingLabel: "1 cup (47g)",
    calories: 8, protein: 0.6, carbs: 1.5, fat: 0.1, fiber: 1,
    caloriesPerGram: 0.170, proteinPerGram: 0.013, carbsPerGram: 0.032, fatPerGram: 0.002, fiberPerGram: 0.021,
    aliases: ["lettuce", "romaine", "salad"],
  },
  {
    id: "bell-pepper",
    name: "Bell Pepper",
    category: "vegetable",
    servingSize: 119,
    servingUnit: "medium",
    servingLabel: "1 medium (119g)",
    calories: 24, protein: 1, carbs: 4.7, fat: 0.2, fiber: 1.7,
    caloriesPerGram: 0.202, proteinPerGram: 0.008, carbsPerGram: 0.039, fatPerGram: 0.002, fiberPerGram: 0.014,
    aliases: ["bell pepper", "pepper"],
  },
  {
    id: "carrot",
    name: "Carrot",
    category: "vegetable",
    servingSize: 61,
    servingUnit: "medium",
    servingLabel: "1 medium (61g)",
    calories: 25, protein: 0.6, carbs: 5.8, fat: 0.1, fiber: 1.7,
    caloriesPerGram: 0.410, proteinPerGram: 0.010, carbsPerGram: 0.095, fatPerGram: 0.002, fiberPerGram: 0.028,
    aliases: ["carrot", "carrots"],
  },
  {
    id: "corn",
    name: "Corn (cooked)",
    category: "vegetable",
    servingSize: 149,
    servingUnit: "cup",
    servingLabel: "1 cup (149g)",
    calories: 143, protein: 5.1, carbs: 31.3, fat: 2.2, fiber: 3.6,
    caloriesPerGram: 0.960, proteinPerGram: 0.034, carbsPerGram: 0.210, fatPerGram: 0.015, fiberPerGram: 0.024,
    aliases: ["corn", "sweet corn"],
  },
  {
    id: "mushrooms",
    name: "Mushrooms (cooked)",
    category: "vegetable",
    servingSize: 156,
    servingUnit: "cup",
    servingLabel: "1 cup (156g)",
    calories: 44, protein: 3.4, carbs: 8.3, fat: 0.8, fiber: 3.4,
    caloriesPerGram: 0.282, proteinPerGram: 0.022, carbsPerGram: 0.053, fatPerGram: 0.005, fiberPerGram: 0.022,
    aliases: ["mushrooms", "mushroom"],
  },
  {
    id: "green-beans",
    name: "Green Beans (cooked)",
    category: "vegetable",
    servingSize: 125,
    servingUnit: "cup",
    servingLabel: "1 cup (125g)",
    calories: 44, protein: 2.4, carbs: 9.9, fat: 0.4, fiber: 4,
    caloriesPerGram: 0.352, proteinPerGram: 0.019, carbsPerGram: 0.079, fatPerGram: 0.003, fiberPerGram: 0.032,
    aliases: ["green beans", "string beans"],
  },
  {
    id: "cauliflower",
    name: "Cauliflower (cooked)",
    category: "vegetable",
    servingSize: 124,
    servingUnit: "cup",
    servingLabel: "1 cup (124g)",
    calories: 29, protein: 2.3, carbs: 5.1, fat: 0.6, fiber: 2.9,
    caloriesPerGram: 0.234, proteinPerGram: 0.019, carbsPerGram: 0.041, fatPerGram: 0.005, fiberPerGram: 0.023,
    aliases: ["cauliflower"],
  },
  {
    id: "kale",
    name: "Kale (raw)",
    category: "vegetable",
    servingSize: 21,
    servingUnit: "cup",
    servingLabel: "1 cup (21g)",
    calories: 7, protein: 0.6, carbs: 0.9, fat: 0.3, fiber: 0.8,
    caloriesPerGram: 0.333, proteinPerGram: 0.029, carbsPerGram: 0.043, fatPerGram: 0.014, fiberPerGram: 0.038,
    aliases: ["kale"],
  },
  {
    id: "zucchini",
    name: "Zucchini (cooked)",
    category: "vegetable",
    servingSize: 180,
    servingUnit: "cup",
    servingLabel: "1 cup (180g)",
    calories: 27, protein: 2, carbs: 4.7, fat: 0.4, fiber: 1.8,
    caloriesPerGram: 0.150, proteinPerGram: 0.011, carbsPerGram: 0.026, fatPerGram: 0.002, fiberPerGram: 0.010,
    aliases: ["zucchini", "courgette"],
  },
  {
    id: "onion",
    name: "Onion",
    category: "vegetable",
    servingSize: 110,
    servingUnit: "medium",
    servingLabel: "1 medium (110g)",
    calories: 44, protein: 1.2, carbs: 10.3, fat: 0.1, fiber: 1.9,
    caloriesPerGram: 0.400, proteinPerGram: 0.011, carbsPerGram: 0.094, fatPerGram: 0.001, fiberPerGram: 0.017,
    aliases: ["onion", "onions"],
  },

  // ─── Fats / Nuts ────────────────────────────────────────────
  {
    id: "olive-oil",
    name: "Olive Oil",
    category: "fat",
    servingSize: 14,
    servingUnit: "tbsp",
    servingLabel: "1 tbsp (14ml)",
    calories: 119, protein: 0, carbs: 0, fat: 13.5, fiber: 0,
    caloriesPerGram: 8.500, proteinPerGram: 0, carbsPerGram: 0, fatPerGram: 0.964, fiberPerGram: 0,
    aliases: ["olive oil", "evoo", "oil"],
  },
  {
    id: "peanut-butter",
    name: "Peanut Butter",
    category: "fat",
    servingSize: 32,
    servingUnit: "2 tbsp",
    servingLabel: "2 tbsp (32g)",
    calories: 188, protein: 7, carbs: 7.7, fat: 16, fiber: 1.6,
    caloriesPerGram: 5.875, proteinPerGram: 0.219, carbsPerGram: 0.241, fatPerGram: 0.500, fiberPerGram: 0.050,
    aliases: ["peanut butter", "pb"],
  },
  {
    id: "almonds",
    name: "Almonds",
    category: "fat",
    servingSize: 28,
    servingUnit: "oz",
    servingLabel: "1 oz (28g)",
    calories: 164, protein: 6, carbs: 6.1, fat: 14.2, fiber: 3.5,
    caloriesPerGram: 5.857, proteinPerGram: 0.214, carbsPerGram: 0.218, fatPerGram: 0.507, fiberPerGram: 0.125,
    aliases: ["almonds", "almond"],
  },
  {
    id: "walnuts",
    name: "Walnuts",
    category: "fat",
    servingSize: 28,
    servingUnit: "oz",
    servingLabel: "1 oz (28g)",
    calories: 185, protein: 4.3, carbs: 3.9, fat: 18.5, fiber: 1.9,
    caloriesPerGram: 6.607, proteinPerGram: 0.154, carbsPerGram: 0.139, fatPerGram: 0.661, fiberPerGram: 0.068,
    aliases: ["walnuts", "walnut"],
  },
  {
    id: "mixed-nuts",
    name: "Mixed Nuts",
    category: "fat",
    servingSize: 28,
    servingUnit: "oz",
    servingLabel: "1 oz (28g)",
    calories: 172, protein: 5, carbs: 7, fat: 15, fiber: 1.9,
    caloriesPerGram: 6.143, proteinPerGram: 0.179, carbsPerGram: 0.250, fatPerGram: 0.536, fiberPerGram: 0.068,
    aliases: ["mixed nuts", "nuts", "trail mix"],
  },
  {
    id: "coconut-oil",
    name: "Coconut Oil",
    category: "fat",
    servingSize: 14,
    servingUnit: "tbsp",
    servingLabel: "1 tbsp (14ml)",
    calories: 121, protein: 0, carbs: 0, fat: 13.5, fiber: 0,
    caloriesPerGram: 8.643, proteinPerGram: 0, carbsPerGram: 0, fatPerGram: 0.964, fiberPerGram: 0,
    aliases: ["coconut oil"],
  },

  // ─── Legumes ────────────────────────────────────────────────
  {
    id: "black-beans",
    name: "Black Beans (cooked)",
    category: "protein",
    servingSize: 172,
    servingUnit: "cup",
    servingLabel: "1 cup (172g)",
    calories: 227, protein: 15.2, carbs: 40.8, fat: 0.9, fiber: 15,
    caloriesPerGram: 1.320, proteinPerGram: 0.088, carbsPerGram: 0.237, fatPerGram: 0.005, fiberPerGram: 0.087,
    aliases: ["black beans", "beans"],
  },
  {
    id: "chickpeas",
    name: "Chickpeas (cooked)",
    category: "protein",
    servingSize: 164,
    servingUnit: "cup",
    servingLabel: "1 cup (164g)",
    calories: 269, protein: 14.5, carbs: 45, fat: 4.2, fiber: 12.5,
    caloriesPerGram: 1.640, proteinPerGram: 0.088, carbsPerGram: 0.274, fatPerGram: 0.026, fiberPerGram: 0.076,
    aliases: ["chickpeas", "garbanzo beans"],
  },
  {
    id: "lentils",
    name: "Lentils (cooked)",
    category: "protein",
    servingSize: 198,
    servingUnit: "cup",
    servingLabel: "1 cup (198g)",
    calories: 230, protein: 17.9, carbs: 39.9, fat: 0.8, fiber: 15.6,
    caloriesPerGram: 1.162, proteinPerGram: 0.090, carbsPerGram: 0.202, fatPerGram: 0.004, fiberPerGram: 0.079,
    aliases: ["lentils"],
  },
  {
    id: "kidney-beans",
    name: "Kidney Beans (cooked)",
    category: "protein",
    servingSize: 177,
    servingUnit: "cup",
    servingLabel: "1 cup (177g)",
    calories: 225, protein: 15.3, carbs: 40.4, fat: 0.9, fiber: 11.3,
    caloriesPerGram: 1.271, proteinPerGram: 0.086, carbsPerGram: 0.228, fatPerGram: 0.005, fiberPerGram: 0.064,
    aliases: ["kidney beans", "red beans"],
  },

  // ─── Condiments / Extras ────────────────────────────────────
  {
    id: "honey",
    name: "Honey",
    category: "condiment",
    servingSize: 21,
    servingUnit: "tbsp",
    servingLabel: "1 tbsp (21g)",
    calories: 64, protein: 0.1, carbs: 17.3, fat: 0, fiber: 0,
    caloriesPerGram: 3.048, proteinPerGram: 0.005, carbsPerGram: 0.824, fatPerGram: 0, fiberPerGram: 0,
    aliases: ["honey"],
  },
  {
    id: "maple-syrup",
    name: "Maple Syrup",
    category: "condiment",
    servingSize: 20,
    servingUnit: "tbsp",
    servingLabel: "1 tbsp (20g)",
    calories: 52, protein: 0, carbs: 13.4, fat: 0, fiber: 0,
    caloriesPerGram: 2.600, proteinPerGram: 0, carbsPerGram: 0.670, fatPerGram: 0, fiberPerGram: 0,
    aliases: ["maple syrup", "syrup"],
  },
  {
    id: "sugar",
    name: "Sugar",
    category: "condiment",
    servingSize: 12,
    servingUnit: "tbsp",
    servingLabel: "1 tbsp (12g)",
    calories: 49, protein: 0, carbs: 12.6, fat: 0, fiber: 0,
    caloriesPerGram: 4.083, proteinPerGram: 0, carbsPerGram: 1.050, fatPerGram: 0, fiberPerGram: 0,
    aliases: ["sugar", "table sugar"],
  },
  {
    id: "ketchup",
    name: "Ketchup",
    category: "condiment",
    servingSize: 17,
    servingUnit: "tbsp",
    servingLabel: "1 tbsp (17g)",
    calories: 20, protein: 0.2, carbs: 5.3, fat: 0, fiber: 0,
    caloriesPerGram: 1.176, proteinPerGram: 0.012, carbsPerGram: 0.312, fatPerGram: 0, fiberPerGram: 0,
    aliases: ["ketchup", "catsup"],
  },
  {
    id: "mayo",
    name: "Mayo",
    category: "condiment",
    servingSize: 14,
    servingUnit: "tbsp",
    servingLabel: "1 tbsp (14g)",
    calories: 94, protein: 0.1, carbs: 0.1, fat: 10.3, fiber: 0,
    caloriesPerGram: 6.714, proteinPerGram: 0.007, carbsPerGram: 0.007, fatPerGram: 0.736, fiberPerGram: 0,
    aliases: ["mayo", "mayonnaise"],
  },
  {
    id: "ranch-dressing",
    name: "Ranch Dressing",
    category: "condiment",
    servingSize: 30,
    servingUnit: "2 tbsp",
    servingLabel: "2 tbsp (30g)",
    calories: 129, protein: 0.4, carbs: 1.8, fat: 13.4, fiber: 0,
    caloriesPerGram: 4.300, proteinPerGram: 0.013, carbsPerGram: 0.060, fatPerGram: 0.447, fiberPerGram: 0,
    aliases: ["ranch", "ranch dressing"],
  },
  {
    id: "soy-sauce",
    name: "Soy Sauce",
    category: "condiment",
    servingSize: 16,
    servingUnit: "tbsp",
    servingLabel: "1 tbsp (16ml)",
    calories: 9, protein: 0.9, carbs: 1, fat: 0, fiber: 0.1,
    caloriesPerGram: 0.563, proteinPerGram: 0.056, carbsPerGram: 0.063, fatPerGram: 0, fiberPerGram: 0.006,
    aliases: ["soy sauce", "soya sauce"],
  },
  {
    id: "hummus",
    name: "Hummus",
    category: "condiment",
    servingSize: 30,
    servingUnit: "2 tbsp",
    servingLabel: "2 tbsp (30g)",
    calories: 49, protein: 2.4, carbs: 4.6, fat: 2.6, fiber: 1.8,
    caloriesPerGram: 1.633, proteinPerGram: 0.080, carbsPerGram: 0.153, fatPerGram: 0.087, fiberPerGram: 0.060,
    aliases: ["hummus"],
  },
  {
    id: "salsa",
    name: "Salsa",
    category: "condiment",
    servingSize: 36,
    servingUnit: "2 tbsp",
    servingLabel: "2 tbsp (36g)",
    calories: 10, protein: 0.5, carbs: 2.2, fat: 0.1, fiber: 0.6,
    caloriesPerGram: 0.278, proteinPerGram: 0.014, carbsPerGram: 0.061, fatPerGram: 0.003, fiberPerGram: 0.017,
    aliases: ["salsa"],
  },

  // ─── Beverages ──────────────────────────────────────────────
  {
    id: "black-coffee",
    name: "Black Coffee",
    category: "beverage",
    servingSize: 240,
    servingUnit: "cup",
    servingLabel: "1 cup (240ml)",
    calories: 2, protein: 0.3, carbs: 0, fat: 0, fiber: 0,
    caloriesPerGram: 0.008, proteinPerGram: 0.001, carbsPerGram: 0, fatPerGram: 0, fiberPerGram: 0,
    aliases: ["black coffee", "coffee", "drip coffee"],
  },
  {
    id: "almond-milk",
    name: "Almond Milk (unsweetened)",
    category: "beverage",
    servingSize: 240,
    servingUnit: "cup",
    servingLabel: "1 cup (240ml)",
    calories: 30, protein: 1, carbs: 1, fat: 2.5, fiber: 0,
    caloriesPerGram: 0.125, proteinPerGram: 0.004, carbsPerGram: 0.004, fatPerGram: 0.010, fiberPerGram: 0,
    aliases: ["almond milk"],
  },
  {
    id: "oat-milk",
    name: "Oat Milk",
    category: "beverage",
    servingSize: 240,
    servingUnit: "cup",
    servingLabel: "1 cup (240ml)",
    calories: 120, protein: 3, carbs: 16, fat: 5, fiber: 2,
    caloriesPerGram: 0.500, proteinPerGram: 0.013, carbsPerGram: 0.067, fatPerGram: 0.021, fiberPerGram: 0.008,
    aliases: ["oat milk"],
  },
  {
    id: "orange-juice",
    name: "Orange Juice",
    category: "beverage",
    servingSize: 248,
    servingUnit: "cup",
    servingLabel: "1 cup (248ml)",
    calories: 112, protein: 1.7, carbs: 25.8, fat: 0.5, fiber: 0.5,
    caloriesPerGram: 0.452, proteinPerGram: 0.007, carbsPerGram: 0.104, fatPerGram: 0.002, fiberPerGram: 0.002,
    aliases: ["orange juice", "oj"],
  },

  // ─── Snacks ─────────────────────────────────────────────────
  {
    id: "protein-bar",
    name: "Protein Bar (average)",
    category: "snack",
    servingSize: 60,
    servingUnit: "bar",
    servingLabel: "1 bar (60g)",
    calories: 210, protein: 20, carbs: 24, fat: 7, fiber: 3,
    caloriesPerGram: 3.500, proteinPerGram: 0.333, carbsPerGram: 0.400, fatPerGram: 0.117, fiberPerGram: 0.050,
    aliases: ["protein bar", "quest bar", "kind bar"],
  },
  {
    id: "rice-cake",
    name: "Rice Cake",
    category: "snack",
    servingSize: 9,
    servingUnit: "cake",
    servingLabel: "1 cake (9g)",
    calories: 35, protein: 0.7, carbs: 7.3, fat: 0.3, fiber: 0.4,
    caloriesPerGram: 3.889, proteinPerGram: 0.078, carbsPerGram: 0.811, fatPerGram: 0.033, fiberPerGram: 0.044,
    aliases: ["rice cake", "rice cakes"],
  },
  {
    id: "dark-chocolate",
    name: "Dark Chocolate (70%)",
    category: "snack",
    servingSize: 28,
    servingUnit: "oz",
    servingLabel: "1 oz (28g)",
    calories: 170, protein: 2.2, carbs: 13, fat: 12, fiber: 3.1,
    caloriesPerGram: 6.071, proteinPerGram: 0.079, carbsPerGram: 0.464, fatPerGram: 0.429, fiberPerGram: 0.111,
    aliases: ["dark chocolate", "chocolate"],
  },
];

export function searchCommonFoods(query: string): CommonFood[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];

  const scored: { food: CommonFood; score: number }[] = [];

  for (const food of commonFoods) {
    let score = 0;
    const nameLower = food.name.toLowerCase();

    // Exact name match
    if (nameLower === q) { score += 100; }
    // Name starts with query
    else if (nameLower.startsWith(q)) { score += 50; }
    // Name contains query
    else if (nameLower.includes(q)) { score += 30; }

    // Alias exact match
    if (food.aliases.some(a => a === q)) { score += 80; }
    // Alias starts with query
    else if (food.aliases.some(a => a.startsWith(q))) { score += 40; }
    // Alias contains query
    else if (food.aliases.some(a => a.includes(q))) { score += 20; }
    // Query contains alias (e.g., "scrambled egg" contains alias "egg")
    else if (food.aliases.some(a => q.includes(a) && a.length >= 3)) { score += 15; }

    if (score > 0) {
      // Prefer shorter names (more specific) as tiebreaker
      score += Math.max(0, 10 - food.name.length / 5);
      scored.push({ food, score });
    }
  }

  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, 10).map(s => s.food);
}

export function parseQueryQuantity(query: string): {
  cleanQuery: string;
  quantity?: number;
  grams?: number;
  oz?: number;
} {
  let cleanQuery = query;
  let quantity: number | undefined;
  let grams: number | undefined;
  let oz: number | undefined;

  // Match "Xg" or "X grams" patterns
  const gramMatch = query.match(/(\d+\.?\d*)\s*(?:g|grams?)\b\s*(.*)/i);
  if (gramMatch) {
    grams = parseFloat(gramMatch[1]);
    cleanQuery = gramMatch[2] || query.replace(gramMatch[0], "").trim();
    return { cleanQuery: cleanQuery || query.replace(/\d+\.?\d*\s*(?:g|grams?)/i, "").trim(), grams };
  }

  // Match "Xoz" or "X ounces"
  const ozMatch = query.match(/(\d+\.?\d*)\s*(?:oz|ounces?)\b\s*(.*)/i);
  if (ozMatch) {
    oz = parseFloat(ozMatch[1]);
    cleanQuery = ozMatch[2] || query.replace(ozMatch[0], "").trim();
    return { cleanQuery: cleanQuery || query.replace(/\d+\.?\d*\s*(?:oz|ounces?)/i, "").trim(), oz };
  }

  // Match "X lbs"
  const lbsMatch = query.match(/(\d+\.?\d*)\s*(?:lbs?|pounds?)\b\s*(.*)/i);
  if (lbsMatch) {
    oz = parseFloat(lbsMatch[1]) * 16;
    cleanQuery = lbsMatch[2] || query.replace(lbsMatch[0], "").trim();
    return { cleanQuery: cleanQuery || query.replace(/\d+\.?\d*\s*(?:lbs?|pounds?)/i, "").trim(), oz };
  }

  // Match count patterns like "2 eggs", "3 chicken breast"
  const countMatch = query.match(/^(\d+\.?\d*)\s+(.+)/);
  if (countMatch) {
    quantity = parseFloat(countMatch[1]);
    cleanQuery = countMatch[2];
  }

  return { cleanQuery: cleanQuery.trim() || query, quantity, grams, oz };
}
