// =============================================================================
// Pulse NYC — Curated NYC Food Nutrition Database
// 300+ entries covering street food, bodegas, pizza shops, chains, and iconic spots
// =============================================================================

export type NycFoodCategory =
  | "Street Food & Carts"
  | "Bodega"
  | "Pizza"
  | "Bagels & Bakery"
  | "Coffee & Drinks"
  | "Boba & Juice"
  | "Fast Food"
  | "Fast Casual"
  | "Salads & Bowls"
  | "Sandwich & Deli"
  | "Chinese & Noodles"
  | "Mexican & Tacos"
  | "Japanese & Sushi"
  | "Korean"
  | "Indian & South Asian"
  | "Middle Eastern"
  | "Dessert & Snacks"
  | "Iconic NYC Spots"
  | "Grocery & Prepared";

export interface NycFoodVariant {
  name: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
}

export interface NycFoodItem {
  id: string;
  name: string;
  description?: string;
  category: NycFoodCategory;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  sodium?: number;
  saturatedFat?: number;
  sugar?: number;
  servingSize: string;
  servingWeightG?: number;
  tags: string[];
  chain?: string;
  verified: boolean;
  variants?: NycFoodVariant[];
  tip?: string;
}

// =============================================================================
// DATABASE
// =============================================================================

export const NYC_FOOD_DATABASE: NycFoodItem[] = [
  // ---------------------------------------------------------------------------
  // STREET FOOD & CARTS
  // ---------------------------------------------------------------------------
  {
    id: "street_halal_chicken_rice",
    name: "Halal Cart — Chicken over Rice",
    description: "Full platter with white and red sauce from a Midtown halal cart",
    category: "Street Food & Carts",
    calories: 780,
    protein: 42,
    carbs: 68,
    fat: 35,
    fiber: 3,
    servingSize: "1 platter",
    tags: ["halal", "street-food", "midtown", "late-night", "chicken", "rice"],
    verified: false,
    variants: [
      { name: "No sauce", calories: 560, protein: 38, carbs: 65, fat: 12, fiber: 3 },
      { name: "White sauce only", calories: 670, protein: 40, carbs: 66, fat: 24, fiber: 3 },
      { name: "Red sauce only", calories: 600, protein: 39, carbs: 68, fat: 16, fiber: 3 },
    ],
    tip: "Skip the white sauce to save ~180 cal",
  },
  {
    id: "street_halal_lamb_rice",
    name: "Halal Cart — Lamb over Rice",
    category: "Street Food & Carts",
    calories: 850,
    protein: 38,
    carbs: 70,
    fat: 42,
    fiber: 3,
    servingSize: "1 platter",
    tags: ["halal", "street-food", "midtown", "late-night", "lamb", "rice"],
    verified: false,
  },
  {
    id: "street_halal_combo",
    name: "Halal Cart — Combo Platter (Chicken + Lamb)",
    category: "Street Food & Carts",
    calories: 920,
    protein: 45,
    carbs: 72,
    fat: 48,
    fiber: 3,
    servingSize: "1 platter",
    tags: ["halal", "street-food", "midtown", "late-night", "chicken", "lamb", "rice"],
    verified: false,
  },
  {
    id: "street_halal_falafel_rice",
    name: "Halal Cart — Falafel over Rice",
    category: "Street Food & Carts",
    calories: 680,
    protein: 18,
    carbs: 82,
    fat: 28,
    fiber: 8,
    servingSize: "1 platter",
    tags: ["halal", "street-food", "midtown", "vegan", "falafel", "rice"],
    verified: false,
  },
  {
    id: "street_halal_chicken_gyro",
    name: "Halal Cart — Chicken Gyro",
    category: "Street Food & Carts",
    calories: 520,
    protein: 28,
    carbs: 42,
    fat: 24,
    fiber: 2,
    servingSize: "1 wrap",
    tags: ["halal", "street-food", "midtown", "late-night", "wrap", "chicken"],
    verified: false,
  },
  {
    id: "street_dollar_slice_plain",
    name: "Dollar Slice — Plain Cheese",
    category: "Street Food & Carts",
    calories: 290,
    protein: 12,
    carbs: 36,
    fat: 10,
    fiber: 2,
    servingSize: "1 slice",
    tags: ["pizza", "dollar-slice", "cheap-eats", "late-night"],
    verified: false,
  },
  {
    id: "street_dollar_slice_pepperoni",
    name: "Dollar Slice — Pepperoni",
    category: "Street Food & Carts",
    calories: 340,
    protein: 14,
    carbs: 36,
    fat: 14,
    fiber: 2,
    servingSize: "1 slice",
    tags: ["pizza", "dollar-slice", "cheap-eats", "late-night", "pepperoni"],
    verified: false,
  },
  {
    id: "street_pretzel",
    name: "Street Pretzel (Soft, Salted)",
    category: "Street Food & Carts",
    calories: 340,
    protein: 8,
    carbs: 66,
    fat: 4,
    fiber: 2,
    servingSize: "1 pretzel",
    tags: ["street-food", "snack", "pretzel"],
    verified: false,
  },
  {
    id: "street_dirty_water_dog",
    name: "Hot Dog — Dirty Water Dog",
    description: "Classic NYC street hot dog with bun and mustard",
    category: "Street Food & Carts",
    calories: 290,
    protein: 10,
    carbs: 24,
    fat: 16,
    fiber: 1,
    servingSize: "1 hot dog",
    tags: ["street-food", "hot-dog", "classic-nyc"],
    verified: false,
  },
  {
    id: "street_hot_dog_sauerkraut",
    name: "Hot Dog — With Sauerkraut + Mustard",
    category: "Street Food & Carts",
    calories: 310,
    protein: 11,
    carbs: 28,
    fat: 16,
    fiber: 2,
    servingSize: "1 hot dog",
    tags: ["street-food", "hot-dog", "classic-nyc"],
    verified: false,
  },
  {
    id: "street_knish_potato",
    name: "Knish — Potato",
    category: "Street Food & Carts",
    calories: 330,
    protein: 6,
    carbs: 50,
    fat: 12,
    fiber: 3,
    servingSize: "1 knish",
    tags: ["street-food", "jewish-deli", "snack", "classic-nyc"],
    verified: false,
  },
  {
    id: "street_elote",
    name: "Elote — Mexican Street Corn",
    category: "Street Food & Carts",
    calories: 280,
    protein: 6,
    carbs: 28,
    fat: 16,
    fiber: 3,
    servingSize: "1 ear",
    tags: ["street-food", "mexican", "corn", "snack"],
    verified: false,
  },
  {
    id: "street_churro",
    name: "Churro (from a Cart)",
    category: "Street Food & Carts",
    calories: 240,
    protein: 3,
    carbs: 32,
    fat: 12,
    fiber: 1,
    servingSize: "1 churro",
    tags: ["street-food", "dessert", "snack", "churro"],
    verified: false,
  },
  {
    id: "street_mango_chili",
    name: "Mango with Chili + Lime (Fruit Cart)",
    category: "Street Food & Carts",
    calories: 120,
    protein: 1,
    carbs: 30,
    fat: 0,
    fiber: 3,
    servingSize: "1 cup",
    tags: ["street-food", "fruit", "healthy", "snack", "low-calorie"],
    verified: false,
  },
  {
    id: "street_fruit_cup",
    name: "Fruit Cup — Mixed (Large)",
    category: "Street Food & Carts",
    calories: 90,
    protein: 1,
    carbs: 22,
    fat: 0,
    fiber: 3,
    servingSize: "1 large cup",
    tags: ["street-food", "fruit", "healthy", "snack", "low-calorie"],
    verified: false,
  },
  {
    id: "street_roasted_peanuts",
    name: "Roasted Peanuts (Street Vendor Bag)",
    category: "Street Food & Carts",
    calories: 320,
    protein: 14,
    carbs: 10,
    fat: 28,
    fiber: 4,
    servingSize: "1 bag",
    tags: ["street-food", "snack", "nuts", "protein"],
    verified: false,
  },
  {
    id: "street_roasted_chestnuts",
    name: "Roasted Chestnuts (Bag)",
    category: "Street Food & Carts",
    calories: 210,
    protein: 3,
    carbs: 44,
    fat: 2,
    fiber: 4,
    servingSize: "1 bag",
    tags: ["street-food", "snack", "winter", "chestnuts"],
    verified: false,
  },

  // ---------------------------------------------------------------------------
  // BODEGA
  // ---------------------------------------------------------------------------
  {
    id: "bodega_bec_roll",
    name: "Bacon Egg & Cheese on a Roll",
    category: "Bodega",
    calories: 480,
    protein: 22,
    carbs: 36,
    fat: 26,
    fiber: 1,
    servingSize: "1 sandwich",
    tags: ["bodega", "breakfast", "sandwich", "bec", "classic-nyc"],
    verified: false,
  },
  {
    id: "bodega_bec_hero",
    name: "Bacon Egg & Cheese on a Hero",
    category: "Bodega",
    calories: 620,
    protein: 28,
    carbs: 52,
    fat: 32,
    fiber: 2,
    servingSize: "1 sandwich",
    tags: ["bodega", "breakfast", "sandwich", "bec", "hero"],
    verified: false,
  },
  {
    id: "bodega_bec_everything",
    name: "Bacon Egg & Cheese on Everything Bagel",
    category: "Bodega",
    calories: 580,
    protein: 26,
    carbs: 56,
    fat: 28,
    fiber: 2,
    servingSize: "1 sandwich",
    tags: ["bodega", "breakfast", "sandwich", "bec", "bagel"],
    verified: false,
  },
  {
    id: "bodega_sec_roll",
    name: "Sausage Egg & Cheese on a Roll",
    category: "Bodega",
    calories: 540,
    protein: 24,
    carbs: 36,
    fat: 32,
    fiber: 1,
    servingSize: "1 sandwich",
    tags: ["bodega", "breakfast", "sandwich", "sausage"],
    verified: false,
  },
  {
    id: "bodega_turkey_egg_white",
    name: "Turkey Sausage Egg White & Cheese",
    category: "Bodega",
    calories: 380,
    protein: 28,
    carbs: 36,
    fat: 14,
    fiber: 1,
    servingSize: "1 sandwich",
    tags: ["bodega", "breakfast", "sandwich", "healthy", "high-protein"],
    verified: false,
    tip: "Best high-protein bodega option",
  },
  {
    id: "bodega_chopped_cheese",
    name: "Chopped Cheese (Classic, on Hero)",
    description: "NYC's signature bodega sandwich — seasoned beef, melted cheese, lettuce, tomato on a hero",
    category: "Bodega",
    calories: 680,
    protein: 32,
    carbs: 54,
    fat: 36,
    fiber: 3,
    servingSize: "1 sandwich",
    tags: ["bodega", "sandwich", "chopped-cheese", "classic-nyc", "late-night"],
    verified: false,
  },
  {
    id: "bodega_chopped_cheese_lt",
    name: "Chopped Cheese — Lettuce & Tomato",
    category: "Bodega",
    calories: 720,
    protein: 34,
    carbs: 56,
    fat: 38,
    fiber: 4,
    servingSize: "1 sandwich",
    tags: ["bodega", "sandwich", "chopped-cheese", "classic-nyc"],
    verified: false,
  },
  {
    id: "bodega_turkey_cheese_hero",
    name: "Turkey & Cheese Hero",
    category: "Bodega",
    calories: 520,
    protein: 28,
    carbs: 50,
    fat: 20,
    fiber: 2,
    servingSize: "1 sandwich",
    tags: ["bodega", "sandwich", "turkey", "deli"],
    verified: false,
  },
  {
    id: "bodega_ham_cheese_roll",
    name: "Ham & Cheese on a Roll",
    category: "Bodega",
    calories: 450,
    protein: 22,
    carbs: 38,
    fat: 22,
    fiber: 1,
    servingSize: "1 sandwich",
    tags: ["bodega", "sandwich", "ham"],
    verified: false,
  },
  {
    id: "bodega_tuna_sandwich",
    name: "Bodega Tuna Sandwich",
    category: "Bodega",
    calories: 560,
    protein: 24,
    carbs: 44,
    fat: 30,
    fiber: 2,
    servingSize: "1 sandwich",
    tags: ["bodega", "sandwich", "tuna"],
    verified: false,
  },
  {
    id: "bodega_coffee_light_sweet",
    name: "Bodega Coffee — Light & Sweet (Medium)",
    category: "Bodega",
    calories: 120,
    protein: 2,
    carbs: 18,
    fat: 4,
    fiber: 0,
    servingSize: "1 medium cup",
    tags: ["bodega", "coffee", "drink", "morning"],
    verified: false,
  },
  {
    id: "bodega_iced_coffee",
    name: "Bodega Iced Coffee — Milk & Sugar (Large)",
    category: "Bodega",
    calories: 180,
    protein: 3,
    carbs: 32,
    fat: 4,
    fiber: 0,
    servingSize: "1 large cup",
    tags: ["bodega", "coffee", "drink", "iced-coffee"],
    verified: false,
  },
  {
    id: "bodega_arizona",
    name: "Arizona Iced Tea (23oz Can)",
    category: "Bodega",
    calories: 270,
    protein: 0,
    carbs: 70,
    fat: 0,
    fiber: 0,
    servingSize: "1 can (23oz)",
    tags: ["bodega", "drink", "tea", "sugary"],
    verified: false,
  },
  {
    id: "bodega_jumex",
    name: "Jumex Nectar (11.3oz)",
    category: "Bodega",
    calories: 160,
    protein: 0,
    carbs: 40,
    fat: 0,
    fiber: 0,
    servingSize: "1 can (11.3oz)",
    tags: ["bodega", "drink", "juice", "sugary"],
    verified: false,
  },
  {
    id: "bodega_snapple",
    name: "Snapple Peach Tea (16oz)",
    category: "Bodega",
    calories: 160,
    protein: 0,
    carbs: 40,
    fat: 0,
    fiber: 0,
    servingSize: "1 bottle (16oz)",
    tags: ["bodega", "drink", "tea", "sugary"],
    verified: false,
  },

  // ---------------------------------------------------------------------------
  // PIZZA — NYC SHOPS
  // ---------------------------------------------------------------------------
  {
    id: "pizza_joes_plain",
    name: "Joe's Pizza — Plain Cheese Slice",
    category: "Pizza",
    calories: 350,
    protein: 14,
    carbs: 40,
    fat: 14,
    fiber: 2,
    servingSize: "1 slice",
    tags: ["pizza", "slice", "joe's", "greenwich-village", "classic-nyc"],
    chain: "Joe's Pizza",
    verified: false,
  },
  {
    id: "pizza_joes_fresh_mozz",
    name: "Joe's Pizza — Fresh Mozzarella Slice",
    category: "Pizza",
    calories: 410,
    protein: 16,
    carbs: 40,
    fat: 18,
    fiber: 2,
    servingSize: "1 slice",
    tags: ["pizza", "slice", "joe's", "greenwich-village"],
    chain: "Joe's Pizza",
    verified: false,
  },
  {
    id: "pizza_joes_pepperoni",
    name: "Joe's Pizza — Pepperoni Slice",
    category: "Pizza",
    calories: 400,
    protein: 16,
    carbs: 40,
    fat: 18,
    fiber: 2,
    servingSize: "1 slice",
    tags: ["pizza", "slice", "joe's", "pepperoni"],
    chain: "Joe's Pizza",
    verified: false,
  },
  {
    id: "pizza_prince_spicy_spring",
    name: "Prince Street Pizza — Spicy Spring Pepperoni (Square)",
    category: "Pizza",
    calories: 480,
    protein: 18,
    carbs: 42,
    fat: 26,
    fiber: 2,
    servingSize: "1 square slice",
    tags: ["pizza", "slice", "prince-street", "nolita", "spicy", "pepperoni", "classic-nyc"],
    chain: "Prince Street Pizza",
    verified: false,
  },
  {
    id: "pizza_artichoke_artichoke",
    name: "Artichoke Basille — Artichoke Slice",
    category: "Pizza",
    calories: 560,
    protein: 18,
    carbs: 48,
    fat: 32,
    fiber: 3,
    servingSize: "1 slice",
    tags: ["pizza", "slice", "artichoke", "late-night", "classic-nyc"],
    chain: "Artichoke Basille's",
    verified: false,
  },
  {
    id: "pizza_artichoke_margherita",
    name: "Artichoke Basille — Margherita Slice",
    category: "Pizza",
    calories: 380,
    protein: 14,
    carbs: 40,
    fat: 16,
    fiber: 2,
    servingSize: "1 slice",
    tags: ["pizza", "slice", "artichoke", "margherita"],
    chain: "Artichoke Basille's",
    verified: false,
  },
  {
    id: "pizza_scarrs_cheese",
    name: "Scarr's Pizza — Cheese Slice",
    category: "Pizza",
    calories: 320,
    protein: 12,
    carbs: 38,
    fat: 12,
    fiber: 2,
    servingSize: "1 slice",
    tags: ["pizza", "slice", "scarrs", "les", "classic-nyc"],
    chain: "Scarr's Pizza",
    verified: false,
  },
  {
    id: "pizza_lb_sicilian",
    name: "L&B Spumoni Gardens — Sicilian Square",
    category: "Pizza",
    calories: 460,
    protein: 18,
    carbs: 50,
    fat: 20,
    fiber: 3,
    servingSize: "1 square slice",
    tags: ["pizza", "slice", "sicilian", "brooklyn", "classic-nyc"],
    chain: "L&B Spumoni Gardens",
    verified: false,
  },
  {
    id: "pizza_99cent_cheese",
    name: "99 Cent Fresh Pizza — Cheese Slice",
    category: "Pizza",
    calories: 260,
    protein: 10,
    carbs: 34,
    fat: 8,
    fiber: 2,
    servingSize: "1 slice",
    tags: ["pizza", "slice", "dollar-slice", "cheap-eats"],
    chain: "99 Cent Fresh Pizza",
    verified: false,
  },
  {
    id: "pizza_generic_cheese",
    name: "NY Slice — Average Cheese (Generic NYC)",
    category: "Pizza",
    calories: 300,
    protein: 12,
    carbs: 36,
    fat: 10,
    fiber: 2,
    servingSize: "1 slice",
    tags: ["pizza", "slice", "generic"],
    verified: false,
  },

  // ---------------------------------------------------------------------------
  // BAGELS & BAKERY
  // ---------------------------------------------------------------------------
  {
    id: "bagel_plain_cc",
    name: "Plain Bagel with Cream Cheese",
    category: "Bagels & Bakery",
    calories: 450,
    protein: 12,
    carbs: 54,
    fat: 18,
    fiber: 2,
    servingSize: "1 bagel",
    tags: ["bagel", "breakfast", "cream-cheese", "classic-nyc"],
    verified: false,
  },
  {
    id: "bagel_everything_cc",
    name: "Everything Bagel with Cream Cheese",
    category: "Bagels & Bakery",
    calories: 470,
    protein: 12,
    carbs: 56,
    fat: 20,
    fiber: 2,
    servingSize: "1 bagel",
    tags: ["bagel", "breakfast", "cream-cheese", "everything-bagel", "classic-nyc"],
    verified: false,
  },
  {
    id: "bagel_butter",
    name: "Bagel with Butter",
    category: "Bagels & Bakery",
    calories: 380,
    protein: 10,
    carbs: 54,
    fat: 14,
    fiber: 2,
    servingSize: "1 bagel",
    tags: ["bagel", "breakfast"],
    verified: false,
  },
  {
    id: "bagel_lox_cc",
    name: "Bagel with Lox + Cream Cheese",
    category: "Bagels & Bakery",
    calories: 620,
    protein: 28,
    carbs: 60,
    fat: 28,
    fiber: 3,
    servingSize: "1 bagel",
    tags: ["bagel", "breakfast", "lox", "smoked-salmon", "classic-nyc"],
    verified: false,
  },
  {
    id: "bagel_pb",
    name: "Bagel with Peanut Butter",
    category: "Bagels & Bakery",
    calories: 520,
    protein: 18,
    carbs: 58,
    fat: 24,
    fiber: 4,
    servingSize: "1 bagel",
    tags: ["bagel", "breakfast", "peanut-butter"],
    verified: false,
  },
  {
    id: "bakery_croissant_plain",
    name: "Croissant — Plain",
    category: "Bagels & Bakery",
    calories: 310,
    protein: 6,
    carbs: 32,
    fat: 18,
    fiber: 1,
    servingSize: "1 croissant",
    tags: ["bakery", "breakfast", "croissant", "pastry"],
    verified: false,
  },
  {
    id: "bakery_croissant_almond",
    name: "Croissant — Almond",
    category: "Bagels & Bakery",
    calories: 440,
    protein: 8,
    carbs: 42,
    fat: 26,
    fiber: 2,
    servingSize: "1 croissant",
    tags: ["bakery", "breakfast", "croissant", "pastry", "almond"],
    verified: false,
  },
  {
    id: "bakery_black_white_cookie",
    name: "Black & White Cookie",
    category: "Bagels & Bakery",
    calories: 400,
    protein: 4,
    carbs: 64,
    fat: 14,
    fiber: 1,
    servingSize: "1 cookie",
    tags: ["bakery", "cookie", "classic-nyc", "dessert"],
    verified: false,
  },
  {
    id: "bakery_levain_choc_walnut",
    name: "Levain Bakery — Chocolate Chip Walnut Cookie",
    category: "Bagels & Bakery",
    calories: 550,
    protein: 8,
    carbs: 64,
    fat: 30,
    fiber: 2,
    servingSize: "1 cookie",
    tags: ["bakery", "cookie", "levain", "classic-nyc", "dessert"],
    chain: "Levain Bakery",
    verified: false,
  },
  {
    id: "bakery_insomnia_choc_chunk",
    name: "Insomnia Cookies — Classic Chocolate Chunk",
    category: "Bagels & Bakery",
    calories: 440,
    protein: 5,
    carbs: 56,
    fat: 22,
    fiber: 1,
    servingSize: "1 cookie",
    tags: ["bakery", "cookie", "insomnia", "late-night", "dessert"],
    chain: "Insomnia Cookies",
    verified: false,
  },
  {
    id: "bakery_crumbl_pink_sugar",
    name: "Crumbl — Classic Pink Sugar",
    category: "Bagels & Bakery",
    calories: 510,
    protein: 5,
    carbs: 72,
    fat: 22,
    fiber: 0,
    servingSize: "1 cookie",
    tags: ["bakery", "cookie", "crumbl", "dessert"],
    chain: "Crumbl",
    verified: false,
  },

  // ---------------------------------------------------------------------------
  // COFFEE & DRINKS
  // ---------------------------------------------------------------------------
  {
    id: "coffee_sbux_iced_caramel_macchiato",
    name: "Starbucks — Iced Caramel Macchiato (Grande)",
    category: "Coffee & Drinks",
    calories: 250,
    protein: 10,
    carbs: 34,
    fat: 7,
    fiber: 0,
    servingSize: "grande (16oz)",
    tags: ["coffee", "drink", "morning", "starbucks", "iced"],
    chain: "Starbucks",
    verified: true,
  },
  {
    id: "coffee_sbux_vsccb",
    name: "Starbucks — Vanilla Sweet Cream Cold Brew (Grande)",
    category: "Coffee & Drinks",
    calories: 200,
    protein: 2,
    carbs: 28,
    fat: 10,
    fiber: 0,
    servingSize: "grande (16oz)",
    tags: ["coffee", "drink", "morning", "starbucks", "cold-brew"],
    chain: "Starbucks",
    verified: true,
  },
  {
    id: "coffee_sbux_pike_black",
    name: "Starbucks — Pike Place (Grande, Black)",
    category: "Coffee & Drinks",
    calories: 5,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    servingSize: "grande (16oz)",
    tags: ["coffee", "drink", "morning", "starbucks", "black-coffee", "low-calorie"],
    chain: "Starbucks",
    verified: true,
  },
  {
    id: "coffee_sbux_psl",
    name: "Starbucks — Pumpkin Spice Latte (Grande, 2%)",
    category: "Coffee & Drinks",
    calories: 390,
    protein: 14,
    carbs: 52,
    fat: 14,
    fiber: 0,
    servingSize: "grande (16oz)",
    tags: ["coffee", "drink", "starbucks", "seasonal", "pumpkin-spice"],
    chain: "Starbucks",
    verified: true,
  },
  {
    id: "coffee_sbux_matcha_latte",
    name: "Starbucks — Matcha Latte (Grande, 2%)",
    category: "Coffee & Drinks",
    calories: 240,
    protein: 12,
    carbs: 34,
    fat: 5,
    fiber: 1,
    servingSize: "grande (16oz)",
    tags: ["coffee", "drink", "starbucks", "matcha"],
    chain: "Starbucks",
    verified: true,
  },
  {
    id: "coffee_dunkin_iced",
    name: "Dunkin — Iced Coffee (Med, Cream + Sugar)",
    category: "Coffee & Drinks",
    calories: 170,
    protein: 2,
    carbs: 30,
    fat: 4,
    fiber: 0,
    servingSize: "medium (24oz)",
    tags: ["coffee", "drink", "morning", "dunkin", "iced"],
    chain: "Dunkin",
    verified: true,
  },
  {
    id: "coffee_dunkin_hot_latte",
    name: "Dunkin — Medium Hot Latte",
    category: "Coffee & Drinks",
    calories: 120,
    protein: 10,
    carbs: 12,
    fat: 4,
    fiber: 0,
    servingSize: "medium (14oz)",
    tags: ["coffee", "drink", "morning", "dunkin", "latte"],
    chain: "Dunkin",
    verified: true,
  },
  {
    id: "coffee_dunkin_glazed_donut",
    name: "Dunkin — Glazed Donut",
    category: "Coffee & Drinks",
    calories: 240,
    protein: 3,
    carbs: 31,
    fat: 11,
    fiber: 0,
    servingSize: "1 donut",
    tags: ["dunkin", "donut", "breakfast", "snack"],
    chain: "Dunkin",
    verified: true,
  },
  {
    id: "coffee_dunkin_everything_bagel",
    name: "Dunkin — Everything Bagel w/ CC",
    category: "Coffee & Drinks",
    calories: 460,
    protein: 14,
    carbs: 62,
    fat: 16,
    fiber: 2,
    servingSize: "1 bagel",
    tags: ["dunkin", "bagel", "breakfast", "cream-cheese"],
    chain: "Dunkin",
    verified: true,
  },
  {
    id: "coffee_blank_street_iced_latte",
    name: "Blank Street — Iced Latte (Oat, Medium)",
    category: "Coffee & Drinks",
    calories: 180,
    protein: 3,
    carbs: 24,
    fat: 8,
    fiber: 1,
    servingSize: "medium (16oz)",
    tags: ["coffee", "drink", "blank-street", "oat-milk", "iced"],
    chain: "Blank Street",
    verified: true,
  },
  {
    id: "coffee_blank_street_cold_brew",
    name: "Blank Street — Cold Brew (Black)",
    category: "Coffee & Drinks",
    calories: 5,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    servingSize: "medium (16oz)",
    tags: ["coffee", "drink", "blank-street", "cold-brew", "low-calorie"],
    chain: "Blank Street",
    verified: true,
  },
  {
    id: "coffee_gregorys_cortado",
    name: "Gregory's Coffee — Cortado",
    category: "Coffee & Drinks",
    calories: 60,
    protein: 3,
    carbs: 5,
    fat: 3,
    fiber: 0,
    servingSize: "1 cortado (4oz)",
    tags: ["coffee", "drink", "gregorys", "cortado"],
    chain: "Gregory's Coffee",
    verified: false,
  },
  {
    id: "coffee_devocion_cortado",
    name: "Devocion — Cortado",
    category: "Coffee & Drinks",
    calories: 60,
    protein: 3,
    carbs: 5,
    fat: 3,
    fiber: 0,
    servingSize: "1 cortado (4oz)",
    tags: ["coffee", "drink", "devocion", "cortado", "brooklyn"],
    chain: "Devocion",
    verified: false,
  },

  // ---------------------------------------------------------------------------
  // BOBA & JUICE
  // ---------------------------------------------------------------------------
  {
    id: "boba_classic_milk_tea",
    name: "Boba — Classic Milk Tea w/ Tapioca (Large)",
    category: "Boba & Juice",
    calories: 420,
    protein: 2,
    carbs: 78,
    fat: 8,
    fiber: 0,
    servingSize: "1 large cup",
    tags: ["boba", "drink", "milk-tea", "tapioca"],
    verified: false,
  },
  {
    id: "boba_taro_milk_tea",
    name: "Boba — Taro Milk Tea w/ Tapioca (Large)",
    category: "Boba & Juice",
    calories: 480,
    protein: 2,
    carbs: 88,
    fat: 10,
    fiber: 0,
    servingSize: "1 large cup",
    tags: ["boba", "drink", "milk-tea", "taro", "tapioca"],
    verified: false,
  },
  {
    id: "boba_matcha_milk_tea",
    name: "Boba — Matcha Milk Tea w/ Tapioca (Large)",
    category: "Boba & Juice",
    calories: 380,
    protein: 3,
    carbs: 68,
    fat: 8,
    fiber: 1,
    servingSize: "1 large cup",
    tags: ["boba", "drink", "milk-tea", "matcha", "tapioca"],
    verified: false,
  },
  {
    id: "boba_fruit_tea",
    name: "Boba — Fruit Tea (No Milk, Large)",
    category: "Boba & Juice",
    calories: 280,
    protein: 0,
    carbs: 68,
    fat: 0,
    fiber: 0,
    servingSize: "1 large cup",
    tags: ["boba", "drink", "fruit-tea"],
    verified: false,
  },
  {
    id: "juice_press_green",
    name: "Juice Press — Green Juice (16oz)",
    category: "Boba & Juice",
    calories: 120,
    protein: 4,
    carbs: 24,
    fat: 1,
    fiber: 2,
    servingSize: "1 bottle (16oz)",
    tags: ["juice", "drink", "healthy", "green-juice", "low-calorie"],
    chain: "Juice Press",
    verified: false,
  },
  {
    id: "juice_press_acai_bowl",
    name: "Juice Press — Acai Bowl",
    category: "Boba & Juice",
    calories: 480,
    protein: 8,
    carbs: 72,
    fat: 18,
    fiber: 8,
    servingSize: "1 bowl",
    tags: ["juice", "acai", "bowl", "healthy", "breakfast"],
    chain: "Juice Press",
    verified: false,
  },
  {
    id: "juice_joe_tunacado",
    name: "Joe & The Juice — Tunacado Sandwich",
    category: "Boba & Juice",
    calories: 520,
    protein: 28,
    carbs: 42,
    fat: 24,
    fiber: 6,
    servingSize: "1 sandwich",
    tags: ["juice", "sandwich", "tuna", "avocado", "joe-and-the-juice"],
    chain: "Joe & The Juice",
    verified: false,
  },

  // ---------------------------------------------------------------------------
  // FAST FOOD — McDONALD'S
  // ---------------------------------------------------------------------------
  {
    id: "ff_mcdonalds_big_mac",
    name: "McDonald's — Big Mac",
    category: "Fast Food",
    calories: 550,
    protein: 25,
    carbs: 45,
    fat: 30,
    fiber: 3,
    servingSize: "1 sandwich",
    tags: ["fast-food", "mcdonalds", "burger"],
    chain: "McDonald's",
    verified: true,
  },
  {
    id: "ff_mcdonalds_qpc",
    name: "McDonald's — Quarter Pounder w/ Cheese",
    category: "Fast Food",
    calories: 520,
    protein: 30,
    carbs: 42,
    fat: 26,
    fiber: 2,
    servingSize: "1 sandwich",
    tags: ["fast-food", "mcdonalds", "burger"],
    chain: "McDonald's",
    verified: true,
  },
  {
    id: "ff_mcdonalds_mcchicken",
    name: "McDonald's — McChicken",
    category: "Fast Food",
    calories: 400,
    protein: 14,
    carbs: 40,
    fat: 21,
    fiber: 1,
    servingSize: "1 sandwich",
    tags: ["fast-food", "mcdonalds", "chicken"],
    chain: "McDonald's",
    verified: true,
  },
  {
    id: "ff_mcdonalds_10pc_nuggets",
    name: "McDonald's — 10-pc Chicken McNuggets",
    category: "Fast Food",
    calories: 410,
    protein: 25,
    carbs: 26,
    fat: 24,
    fiber: 1,
    servingSize: "10 pieces",
    tags: ["fast-food", "mcdonalds", "nuggets", "chicken"],
    chain: "McDonald's",
    verified: true,
  },
  {
    id: "ff_mcdonalds_med_fries",
    name: "McDonald's — Medium Fries",
    category: "Fast Food",
    calories: 320,
    protein: 5,
    carbs: 43,
    fat: 15,
    fiber: 4,
    servingSize: "1 medium",
    tags: ["fast-food", "mcdonalds", "fries", "side"],
    chain: "McDonald's",
    verified: true,
  },
  {
    id: "ff_mcdonalds_egg_mcmuffin",
    name: "McDonald's — Egg McMuffin",
    category: "Fast Food",
    calories: 300,
    protein: 17,
    carbs: 30,
    fat: 12,
    fiber: 2,
    servingSize: "1 sandwich",
    tags: ["fast-food", "mcdonalds", "breakfast"],
    chain: "McDonald's",
    verified: true,
  },
  {
    id: "ff_mcdonalds_sausage_mcmuffin",
    name: "McDonald's — Sausage McMuffin w/ Egg",
    category: "Fast Food",
    calories: 480,
    protein: 21,
    carbs: 30,
    fat: 30,
    fiber: 2,
    servingSize: "1 sandwich",
    tags: ["fast-food", "mcdonalds", "breakfast", "sausage"],
    chain: "McDonald's",
    verified: true,
  },
  {
    id: "ff_mcdonalds_mcflurry_oreo",
    name: "McDonald's — McFlurry (Oreo, Regular)",
    category: "Fast Food",
    calories: 510,
    protein: 12,
    carbs: 80,
    fat: 17,
    fiber: 1,
    servingSize: "1 regular",
    tags: ["fast-food", "mcdonalds", "dessert", "ice-cream"],
    chain: "McDonald's",
    verified: true,
  },

  // ---------------------------------------------------------------------------
  // FAST FOOD — CHICK-FIL-A
  // ---------------------------------------------------------------------------
  {
    id: "ff_cfa_original",
    name: "Chick-fil-A — Chicken Sandwich (Original)",
    category: "Fast Food",
    calories: 440,
    protein: 28,
    carbs: 40,
    fat: 18,
    fiber: 1,
    servingSize: "1 sandwich",
    tags: ["fast-food", "chick-fil-a", "chicken"],
    chain: "Chick-fil-A",
    verified: true,
  },
  {
    id: "ff_cfa_spicy",
    name: "Chick-fil-A — Spicy Chicken Sandwich",
    category: "Fast Food",
    calories: 450,
    protein: 28,
    carbs: 42,
    fat: 18,
    fiber: 2,
    servingSize: "1 sandwich",
    tags: ["fast-food", "chick-fil-a", "chicken", "spicy"],
    chain: "Chick-fil-A",
    verified: true,
  },
  {
    id: "ff_cfa_8ct_nuggets",
    name: "Chick-fil-A — 8-ct Nuggets",
    category: "Fast Food",
    calories: 250,
    protein: 27,
    carbs: 11,
    fat: 11,
    fiber: 0,
    servingSize: "8 pieces",
    tags: ["fast-food", "chick-fil-a", "nuggets", "chicken"],
    chain: "Chick-fil-A",
    verified: true,
  },
  {
    id: "ff_cfa_12ct_nuggets",
    name: "Chick-fil-A — 12-ct Nuggets",
    category: "Fast Food",
    calories: 380,
    protein: 40,
    carbs: 16,
    fat: 17,
    fiber: 0,
    servingSize: "12 pieces",
    tags: ["fast-food", "chick-fil-a", "nuggets", "chicken"],
    chain: "Chick-fil-A",
    verified: true,
  },
  {
    id: "ff_cfa_waffle_fries",
    name: "Chick-fil-A — Waffle Fries (Medium)",
    category: "Fast Food",
    calories: 420,
    protein: 5,
    carbs: 44,
    fat: 24,
    fiber: 5,
    servingSize: "1 medium",
    tags: ["fast-food", "chick-fil-a", "fries", "side"],
    chain: "Chick-fil-A",
    verified: true,
  },
  {
    id: "ff_cfa_chicken_biscuit",
    name: "Chick-fil-A — Chicken Biscuit",
    category: "Fast Food",
    calories: 440,
    protein: 18,
    carbs: 44,
    fat: 20,
    fiber: 1,
    servingSize: "1 biscuit",
    tags: ["fast-food", "chick-fil-a", "breakfast", "chicken"],
    chain: "Chick-fil-A",
    verified: true,
  },
  {
    id: "ff_cfa_grilled_nuggets",
    name: "Chick-fil-A — Grilled Nuggets (8ct)",
    category: "Fast Food",
    calories: 130,
    protein: 25,
    carbs: 1,
    fat: 3,
    fiber: 0,
    servingSize: "8 pieces",
    tags: ["fast-food", "chick-fil-a", "nuggets", "chicken", "healthy", "high-protein", "low-calorie"],
    chain: "Chick-fil-A",
    verified: true,
    tip: "Best low-cal fast food protein option",
  },
  {
    id: "ff_cfa_cobb_salad",
    name: "Chick-fil-A — Cobb Salad w/ Nuggets",
    category: "Fast Food",
    calories: 510,
    protein: 42,
    carbs: 27,
    fat: 27,
    fiber: 4,
    servingSize: "1 salad",
    tags: ["fast-food", "chick-fil-a", "salad", "chicken", "high-protein"],
    chain: "Chick-fil-A",
    verified: true,
  },

  // ---------------------------------------------------------------------------
  // FAST FOOD — POPEYES
  // ---------------------------------------------------------------------------
  {
    id: "ff_popeyes_classic_sandwich",
    name: "Popeyes — Chicken Sandwich (Classic)",
    category: "Fast Food",
    calories: 700,
    protein: 28,
    carbs: 50,
    fat: 42,
    fiber: 2,
    servingSize: "1 sandwich",
    tags: ["fast-food", "popeyes", "chicken"],
    chain: "Popeyes",
    verified: true,
  },
  {
    id: "ff_popeyes_spicy_sandwich",
    name: "Popeyes — Spicy Chicken Sandwich",
    category: "Fast Food",
    calories: 700,
    protein: 28,
    carbs: 50,
    fat: 42,
    fiber: 3,
    servingSize: "1 sandwich",
    tags: ["fast-food", "popeyes", "chicken", "spicy"],
    chain: "Popeyes",
    verified: true,
  },
  {
    id: "ff_popeyes_3pc_tenders",
    name: "Popeyes — 3pc Tenders (Mild)",
    category: "Fast Food",
    calories: 340,
    protein: 24,
    carbs: 14,
    fat: 21,
    fiber: 1,
    servingSize: "3 pieces",
    tags: ["fast-food", "popeyes", "chicken", "tenders"],
    chain: "Popeyes",
    verified: true,
  },
  {
    id: "ff_popeyes_red_beans",
    name: "Popeyes — Red Beans & Rice (Regular)",
    category: "Fast Food",
    calories: 230,
    protein: 7,
    carbs: 30,
    fat: 8,
    fiber: 7,
    servingSize: "1 regular",
    tags: ["fast-food", "popeyes", "side", "beans", "rice"],
    chain: "Popeyes",
    verified: true,
  },

  // ---------------------------------------------------------------------------
  // FAST FOOD — FIVE GUYS
  // ---------------------------------------------------------------------------
  {
    id: "ff_five_guys_little_cheeseburger",
    name: "Five Guys — Cheeseburger (Little)",
    category: "Fast Food",
    calories: 550,
    protein: 27,
    carbs: 40,
    fat: 32,
    fiber: 2,
    servingSize: "1 burger",
    tags: ["fast-food", "five-guys", "burger", "cheeseburger"],
    chain: "Five Guys",
    verified: true,
  },
  {
    id: "ff_five_guys_reg_cheeseburger",
    name: "Five Guys — Cheeseburger (Regular, 2 Patties)",
    category: "Fast Food",
    calories: 840,
    protein: 47,
    carbs: 40,
    fat: 55,
    fiber: 2,
    servingSize: "1 burger",
    tags: ["fast-food", "five-guys", "burger", "cheeseburger"],
    chain: "Five Guys",
    verified: true,
  },
  {
    id: "ff_five_guys_reg_fries",
    name: "Five Guys — Regular Fries",
    category: "Fast Food",
    calories: 530,
    protein: 8,
    carbs: 48,
    fat: 34,
    fiber: 6,
    servingSize: "1 regular",
    tags: ["fast-food", "five-guys", "fries", "side"],
    chain: "Five Guys",
    verified: true,
  },
  {
    id: "ff_five_guys_cajun_fries",
    name: "Five Guys — Cajun Fries",
    category: "Fast Food",
    calories: 530,
    protein: 8,
    carbs: 48,
    fat: 34,
    fiber: 6,
    servingSize: "1 regular",
    tags: ["fast-food", "five-guys", "fries", "side", "cajun"],
    chain: "Five Guys",
    verified: true,
  },
  {
    id: "ff_five_guys_hot_dog",
    name: "Five Guys — Hot Dog",
    category: "Fast Food",
    calories: 545,
    protein: 18,
    carbs: 40,
    fat: 35,
    fiber: 2,
    servingSize: "1 hot dog",
    tags: ["fast-food", "five-guys", "hot-dog"],
    chain: "Five Guys",
    verified: true,
  },

  // ---------------------------------------------------------------------------
  // FAST FOOD — WENDY'S
  // ---------------------------------------------------------------------------
  {
    id: "ff_wendys_daves_single",
    name: "Wendy's — Dave's Single",
    category: "Fast Food",
    calories: 590,
    protein: 30,
    carbs: 46,
    fat: 34,
    fiber: 3,
    servingSize: "1 burger",
    tags: ["fast-food", "wendys", "burger"],
    chain: "Wendy's",
    verified: true,
  },
  {
    id: "ff_wendys_baconator",
    name: "Wendy's — Baconator",
    category: "Fast Food",
    calories: 950,
    protein: 57,
    carbs: 40,
    fat: 62,
    fiber: 2,
    servingSize: "1 burger",
    tags: ["fast-food", "wendys", "burger", "bacon"],
    chain: "Wendy's",
    verified: true,
  },
  {
    id: "ff_wendys_10pc_nuggs",
    name: "Wendy's — 10-pc Nuggs",
    category: "Fast Food",
    calories: 430,
    protein: 21,
    carbs: 25,
    fat: 28,
    fiber: 0,
    servingSize: "10 pieces",
    tags: ["fast-food", "wendys", "nuggets", "chicken"],
    chain: "Wendy's",
    verified: true,
  },
  {
    id: "ff_wendys_jr_bacon",
    name: "Wendy's — Jr. Bacon Cheeseburger",
    category: "Fast Food",
    calories: 370,
    protein: 17,
    carbs: 28,
    fat: 22,
    fiber: 1,
    servingSize: "1 burger",
    tags: ["fast-food", "wendys", "burger", "bacon", "value"],
    chain: "Wendy's",
    verified: true,
  },
  {
    id: "ff_wendys_frosty",
    name: "Wendy's — Frosty (Medium, Chocolate)",
    category: "Fast Food",
    calories: 460,
    protein: 11,
    carbs: 66,
    fat: 16,
    fiber: 1,
    servingSize: "1 medium",
    tags: ["fast-food", "wendys", "dessert", "ice-cream"],
    chain: "Wendy's",
    verified: true,
  },

  // ---------------------------------------------------------------------------
  // FAST FOOD — WINGSTOP
  // ---------------------------------------------------------------------------
  {
    id: "ff_wingstop_10_bone_in",
    name: "Wingstop — 10 Bone-In Wings (Soy Garlic)",
    category: "Fast Food",
    calories: 780,
    protein: 56,
    carbs: 10,
    fat: 58,
    fiber: 2,
    servingSize: "10 wings",
    tags: ["fast-food", "wingstop", "wings", "chicken"],
    chain: "Wingstop",
    verified: true,
  },
  {
    id: "ff_wingstop_6_boneless",
    name: "Wingstop — 6 Boneless Wings",
    category: "Fast Food",
    calories: 480,
    protein: 26,
    carbs: 34,
    fat: 26,
    fiber: 2,
    servingSize: "6 pieces",
    tags: ["fast-food", "wingstop", "wings", "chicken", "boneless"],
    chain: "Wingstop",
    verified: true,
  },
  {
    id: "ff_wingstop_fries",
    name: "Wingstop — Regular Fries",
    category: "Fast Food",
    calories: 350,
    protein: 4,
    carbs: 44,
    fat: 18,
    fiber: 4,
    servingSize: "1 regular",
    tags: ["fast-food", "wingstop", "fries", "side"],
    chain: "Wingstop",
    verified: true,
  },

  // ---------------------------------------------------------------------------
  // FAST FOOD — BURGER KING
  // ---------------------------------------------------------------------------
  {
    id: "ff_bk_whopper",
    name: "Burger King — Whopper",
    category: "Fast Food",
    calories: 660,
    protein: 28,
    carbs: 49,
    fat: 40,
    fiber: 2,
    servingSize: "1 burger",
    tags: ["fast-food", "burger-king", "burger"],
    chain: "Burger King",
    verified: true,
  },
  {
    id: "ff_bk_original_chicken",
    name: "Burger King — Original Chicken Sandwich",
    category: "Fast Food",
    calories: 660,
    protein: 28,
    carbs: 48,
    fat: 40,
    fiber: 2,
    servingSize: "1 sandwich",
    tags: ["fast-food", "burger-king", "chicken"],
    chain: "Burger King",
    verified: true,
  },
  {
    id: "ff_bk_chicken_fries",
    name: "Burger King — Chicken Fries (9pc)",
    category: "Fast Food",
    calories: 280,
    protein: 13,
    carbs: 19,
    fat: 17,
    fiber: 1,
    servingSize: "9 pieces",
    tags: ["fast-food", "burger-king", "chicken", "snack"],
    chain: "Burger King",
    verified: true,
  },
  {
    id: "ff_bk_onion_rings",
    name: "Burger King — Onion Rings (Medium)",
    category: "Fast Food",
    calories: 320,
    protein: 4,
    carbs: 40,
    fat: 16,
    fiber: 2,
    servingSize: "1 medium",
    tags: ["fast-food", "burger-king", "side", "onion-rings"],
    chain: "Burger King",
    verified: true,
  },

  // ---------------------------------------------------------------------------
  // FAST CASUAL — SWEETGREEN
  // ---------------------------------------------------------------------------
  {
    id: "fc_sweetgreen_harvest",
    name: "Sweetgreen — Harvest Bowl",
    category: "Fast Casual",
    calories: 705,
    protein: 28,
    carbs: 48,
    fat: 44,
    fiber: 9,
    servingSize: "1 bowl",
    tags: ["fast-casual", "sweetgreen", "salad", "bowl", "healthy"],
    chain: "Sweetgreen",
    verified: true,
  },
  {
    id: "fc_sweetgreen_kale_caesar",
    name: "Sweetgreen — Kale Caesar",
    category: "Fast Casual",
    calories: 450,
    protein: 16,
    carbs: 30,
    fat: 30,
    fiber: 5,
    servingSize: "1 salad",
    tags: ["fast-casual", "sweetgreen", "salad", "kale", "caesar"],
    chain: "Sweetgreen",
    verified: true,
  },
  {
    id: "fc_sweetgreen_shroomami",
    name: "Sweetgreen — Shroomami",
    category: "Fast Casual",
    calories: 570,
    protein: 15,
    carbs: 52,
    fat: 34,
    fiber: 8,
    servingSize: "1 bowl",
    tags: ["fast-casual", "sweetgreen", "bowl", "mushroom", "vegetarian"],
    chain: "Sweetgreen",
    verified: true,
  },
  {
    id: "fc_sweetgreen_buffalo_chicken",
    name: "Sweetgreen — Buffalo Chicken Bowl",
    category: "Fast Casual",
    calories: 620,
    protein: 42,
    carbs: 42,
    fat: 32,
    fiber: 7,
    servingSize: "1 bowl",
    tags: ["fast-casual", "sweetgreen", "bowl", "chicken", "buffalo", "high-protein"],
    chain: "Sweetgreen",
    verified: true,
  },
  {
    id: "fc_sweetgreen_crispy_rice",
    name: "Sweetgreen — Crispy Rice Bowl",
    category: "Fast Casual",
    calories: 710,
    protein: 28,
    carbs: 72,
    fat: 34,
    fiber: 5,
    servingSize: "1 bowl",
    tags: ["fast-casual", "sweetgreen", "bowl", "rice"],
    chain: "Sweetgreen",
    verified: true,
  },
  {
    id: "fc_sweetgreen_guac_greens",
    name: "Sweetgreen — Guacamole Greens",
    category: "Fast Casual",
    calories: 580,
    protein: 12,
    carbs: 36,
    fat: 42,
    fiber: 12,
    servingSize: "1 salad",
    tags: ["fast-casual", "sweetgreen", "salad", "guacamole", "vegetarian"],
    chain: "Sweetgreen",
    verified: true,
  },

  // ---------------------------------------------------------------------------
  // FAST CASUAL — DIG
  // ---------------------------------------------------------------------------
  {
    id: "fc_dig_charred_chicken",
    name: "Dig — Charred Chicken + 2 Sides",
    category: "Fast Casual",
    calories: 550,
    protein: 45,
    carbs: 38,
    fat: 22,
    fiber: 6,
    servingSize: "1 plate",
    tags: ["fast-casual", "dig", "chicken", "healthy", "high-protein"],
    chain: "Dig",
    verified: true,
  },
  {
    id: "fc_dig_braised_beef",
    name: "Dig — Braised Beef + Brown Rice + Broccoli",
    category: "Fast Casual",
    calories: 620,
    protein: 38,
    carbs: 52,
    fat: 28,
    fiber: 5,
    servingSize: "1 plate",
    tags: ["fast-casual", "dig", "beef", "brown-rice"],
    chain: "Dig",
    verified: true,
  },
  {
    id: "fc_dig_roasted_salmon",
    name: "Dig — Roasted Salmon + Sweet Potatoes + Kale",
    category: "Fast Casual",
    calories: 580,
    protein: 35,
    carbs: 42,
    fat: 26,
    fiber: 7,
    servingSize: "1 plate",
    tags: ["fast-casual", "dig", "salmon", "healthy", "omega-3"],
    chain: "Dig",
    verified: true,
  },
  {
    id: "fc_dig_market_plate",
    name: "Dig — Market Plate (Avg)",
    category: "Fast Casual",
    calories: 500,
    protein: 30,
    carbs: 45,
    fat: 20,
    fiber: 8,
    servingSize: "1 plate",
    tags: ["fast-casual", "dig", "vegetarian", "healthy"],
    chain: "Dig",
    verified: true,
  },

  // ---------------------------------------------------------------------------
  // FAST CASUAL — CHOPT
  // ---------------------------------------------------------------------------
  {
    id: "fc_chopt_mexican_caesar",
    name: "Chopt — Mexican Caesar",
    category: "Fast Casual",
    calories: 590,
    protein: 12,
    carbs: 44,
    fat: 42,
    fiber: 8,
    servingSize: "1 salad",
    tags: ["fast-casual", "chopt", "salad", "caesar", "mexican"],
    chain: "Chopt",
    verified: true,
  },
  {
    id: "fc_chopt_harvest",
    name: "Chopt — Harvest Bowl",
    category: "Fast Casual",
    calories: 640,
    protein: 15,
    carbs: 58,
    fat: 38,
    fiber: 9,
    servingSize: "1 bowl",
    tags: ["fast-casual", "chopt", "bowl", "harvest"],
    chain: "Chopt",
    verified: true,
  },
  {
    id: "fc_chopt_classic_cobb",
    name: "Chopt — Classic Cobb",
    category: "Fast Casual",
    calories: 680,
    protein: 32,
    carbs: 22,
    fat: 52,
    fiber: 6,
    servingSize: "1 salad",
    tags: ["fast-casual", "chopt", "salad", "cobb"],
    chain: "Chopt",
    verified: true,
  },
  {
    id: "fc_chopt_kale_caesar",
    name: "Chopt — Kale Caesar",
    category: "Fast Casual",
    calories: 440,
    protein: 12,
    carbs: 28,
    fat: 32,
    fiber: 5,
    servingSize: "1 salad",
    tags: ["fast-casual", "chopt", "salad", "kale", "caesar"],
    chain: "Chopt",
    verified: true,
  },

  // ---------------------------------------------------------------------------
  // FAST CASUAL — JUST SALAD
  // ---------------------------------------------------------------------------
  {
    id: "fc_justsalad_thai_chicken",
    name: "Just Salad — Thai Chicken Crunch",
    category: "Fast Casual",
    calories: 520,
    protein: 32,
    carbs: 38,
    fat: 26,
    fiber: 6,
    servingSize: "1 salad",
    tags: ["fast-casual", "just-salad", "salad", "chicken", "thai"],
    chain: "Just Salad",
    verified: true,
  },
  {
    id: "fc_justsalad_classic_caesar",
    name: "Just Salad — Classic Caesar (w/ Chicken)",
    category: "Fast Casual",
    calories: 480,
    protein: 35,
    carbs: 22,
    fat: 28,
    fiber: 4,
    servingSize: "1 salad",
    tags: ["fast-casual", "just-salad", "salad", "caesar", "chicken", "high-protein"],
    chain: "Just Salad",
    verified: true,
  },
  {
    id: "fc_justsalad_buffalo_chicken",
    name: "Just Salad — Buffalo Chicken",
    category: "Fast Casual",
    calories: 460,
    protein: 36,
    carbs: 24,
    fat: 24,
    fiber: 5,
    servingSize: "1 salad",
    tags: ["fast-casual", "just-salad", "salad", "chicken", "buffalo"],
    chain: "Just Salad",
    verified: true,
  },

  // ---------------------------------------------------------------------------
  // FAST CASUAL — CAVA
  // ---------------------------------------------------------------------------
  {
    id: "fc_cava_greens_chicken",
    name: "Cava — Greens + Grilled Chicken Bowl",
    category: "Fast Casual",
    calories: 560,
    protein: 42,
    carbs: 36,
    fat: 28,
    fiber: 8,
    servingSize: "1 bowl",
    tags: ["fast-casual", "cava", "bowl", "chicken", "mediterranean", "high-protein"],
    chain: "Cava",
    verified: true,
  },
  {
    id: "fc_cava_pita_falafel",
    name: "Cava — Pita + Falafel",
    category: "Fast Casual",
    calories: 620,
    protein: 18,
    carbs: 72,
    fat: 28,
    fiber: 8,
    servingSize: "1 pita",
    tags: ["fast-casual", "cava", "pita", "falafel", "mediterranean", "vegetarian"],
    chain: "Cava",
    verified: true,
  },
  {
    id: "fc_cava_rightrice",
    name: "Cava — RightRice Bowl",
    category: "Fast Casual",
    calories: 580,
    protein: 30,
    carbs: 62,
    fat: 22,
    fiber: 6,
    servingSize: "1 bowl",
    tags: ["fast-casual", "cava", "bowl", "rice", "mediterranean"],
    chain: "Cava",
    verified: true,
  },

  // ---------------------------------------------------------------------------
  // FAST CASUAL — PANERA
  // ---------------------------------------------------------------------------
  {
    id: "fc_panera_broccoli_cheddar",
    name: "Panera — Broccoli Cheddar Soup (Bowl)",
    category: "Fast Casual",
    calories: 360,
    protein: 15,
    carbs: 30,
    fat: 21,
    fiber: 3,
    servingSize: "1 bowl",
    tags: ["fast-casual", "panera", "soup", "broccoli", "comfort-food"],
    chain: "Panera",
    verified: true,
  },
  {
    id: "fc_panera_fuji_apple_salad",
    name: "Panera — Fuji Apple Chicken Salad (Whole)",
    category: "Fast Casual",
    calories: 570,
    protein: 30,
    carbs: 58,
    fat: 24,
    fiber: 7,
    servingSize: "1 salad",
    tags: ["fast-casual", "panera", "salad", "chicken", "apple"],
    chain: "Panera",
    verified: true,
  },
  {
    id: "fc_panera_turkey_avo_blt",
    name: "Panera — Turkey Avocado BLT",
    category: "Fast Casual",
    calories: 630,
    protein: 32,
    carbs: 52,
    fat: 32,
    fiber: 4,
    servingSize: "1 sandwich",
    tags: ["fast-casual", "panera", "sandwich", "turkey", "avocado"],
    chain: "Panera",
    verified: true,
  },
  {
    id: "fc_panera_mac_cheese",
    name: "Panera — Mac & Cheese (Bowl)",
    category: "Fast Casual",
    calories: 520,
    protein: 20,
    carbs: 50,
    fat: 26,
    fiber: 2,
    servingSize: "1 bowl",
    tags: ["fast-casual", "panera", "mac-and-cheese", "comfort-food"],
    chain: "Panera",
    verified: true,
  },

  // ---------------------------------------------------------------------------
  // FAST CASUAL — PRET A MANGER
  // ---------------------------------------------------------------------------
  {
    id: "fc_pret_chicken_caesar_wrap",
    name: "Pret a Manger — Chicken Caesar Wrap",
    category: "Fast Casual",
    calories: 480,
    protein: 28,
    carbs: 42,
    fat: 22,
    fiber: 3,
    servingSize: "1 wrap",
    tags: ["fast-casual", "pret", "wrap", "chicken", "caesar"],
    chain: "Pret a Manger",
    verified: true,
  },
  {
    id: "fc_pret_tuna_baguette",
    name: "Pret a Manger — Tuna Baguette",
    category: "Fast Casual",
    calories: 520,
    protein: 26,
    carbs: 48,
    fat: 24,
    fiber: 2,
    servingSize: "1 baguette",
    tags: ["fast-casual", "pret", "sandwich", "tuna"],
    chain: "Pret a Manger",
    verified: true,
  },
  {
    id: "fc_pret_egg_salad",
    name: "Pret a Manger — Egg Salad Sandwich",
    category: "Fast Casual",
    calories: 440,
    protein: 18,
    carbs: 40,
    fat: 22,
    fiber: 2,
    servingSize: "1 sandwich",
    tags: ["fast-casual", "pret", "sandwich", "egg"],
    chain: "Pret a Manger",
    verified: true,
  },

  // ---------------------------------------------------------------------------
  // CHIPOTLE
  // ---------------------------------------------------------------------------
  {
    id: "fc_chipotle_chicken_burrito",
    name: "Chipotle — Chicken Burrito",
    description: "White rice, black beans, salsa, cheese, sour cream",
    category: "Fast Casual",
    calories: 1050,
    protein: 56,
    carbs: 108,
    fat: 38,
    fiber: 12,
    servingSize: "1 burrito",
    tags: ["fast-casual", "chipotle", "burrito", "chicken", "mexican"],
    chain: "Chipotle",
    verified: true,
  },
  {
    id: "fc_chipotle_chicken_bowl",
    name: "Chipotle — Chicken Bowl",
    description: "White rice, black beans, salsa, guacamole",
    category: "Fast Casual",
    calories: 780,
    protein: 48,
    carbs: 78,
    fat: 28,
    fiber: 14,
    servingSize: "1 bowl",
    tags: ["fast-casual", "chipotle", "bowl", "chicken", "mexican"],
    chain: "Chipotle",
    verified: true,
  },
  {
    id: "fc_chipotle_steak_bowl",
    name: "Chipotle — Steak Bowl",
    description: "Brown rice, pinto beans, corn, cheese",
    category: "Fast Casual",
    calories: 820,
    protein: 50,
    carbs: 82,
    fat: 28,
    fiber: 10,
    servingSize: "1 bowl",
    tags: ["fast-casual", "chipotle", "bowl", "steak", "mexican"],
    chain: "Chipotle",
    verified: true,
  },
  {
    id: "fc_chipotle_veggie_bowl",
    name: "Chipotle — Veggie Bowl (Sofritas)",
    description: "Sofritas, rice, beans, guacamole",
    category: "Fast Casual",
    calories: 720,
    protein: 22,
    carbs: 82,
    fat: 32,
    fiber: 16,
    servingSize: "1 bowl",
    tags: ["fast-casual", "chipotle", "bowl", "vegetarian", "sofritas", "mexican"],
    chain: "Chipotle",
    verified: true,
  },
  {
    id: "fc_chipotle_chicken_quesadilla",
    name: "Chipotle — Chicken Quesadilla",
    category: "Fast Casual",
    calories: 740,
    protein: 42,
    carbs: 52,
    fat: 38,
    fiber: 2,
    servingSize: "1 quesadilla",
    tags: ["fast-casual", "chipotle", "quesadilla", "chicken", "mexican"],
    chain: "Chipotle",
    verified: true,
  },
  {
    id: "fc_chipotle_chips_guac",
    name: "Chipotle — Chips & Guac",
    category: "Fast Casual",
    calories: 770,
    protein: 8,
    carbs: 72,
    fat: 50,
    fiber: 12,
    servingSize: "1 order",
    tags: ["fast-casual", "chipotle", "chips", "guacamole", "side", "snack"],
    chain: "Chipotle",
    verified: true,
  },
  {
    id: "fc_chipotle_chips_queso",
    name: "Chipotle — Chips & Queso",
    category: "Fast Casual",
    calories: 480,
    protein: 12,
    carbs: 42,
    fat: 28,
    fiber: 2,
    servingSize: "1 order",
    tags: ["fast-casual", "chipotle", "chips", "queso", "side", "snack"],
    chain: "Chipotle",
    verified: true,
  },

  // ---------------------------------------------------------------------------
  // SHAKE SHACK
  // ---------------------------------------------------------------------------
  {
    id: "fc_shakeshack_shackburger",
    name: "Shake Shack — ShackBurger (Single)",
    category: "Fast Casual",
    calories: 530,
    protein: 28,
    carbs: 27,
    fat: 34,
    fiber: 0,
    servingSize: "1 burger",
    tags: ["fast-casual", "shake-shack", "burger", "classic-nyc"],
    chain: "Shake Shack",
    verified: true,
  },
  {
    id: "fc_shakeshack_smokeshack",
    name: "Shake Shack — SmokeShack",
    category: "Fast Casual",
    calories: 610,
    protein: 30,
    carbs: 28,
    fat: 39,
    fiber: 1,
    servingSize: "1 burger",
    tags: ["fast-casual", "shake-shack", "burger", "bacon", "cherry-pepper"],
    chain: "Shake Shack",
    verified: true,
  },
  {
    id: "fc_shakeshack_chicken_shack",
    name: "Shake Shack — Chicken Shack",
    category: "Fast Casual",
    calories: 580,
    protein: 30,
    carbs: 44,
    fat: 30,
    fiber: 2,
    servingSize: "1 sandwich",
    tags: ["fast-casual", "shake-shack", "chicken"],
    chain: "Shake Shack",
    verified: true,
  },
  {
    id: "fc_shakeshack_shackcago_dog",
    name: "Shake Shack — Shack-cago Dog",
    category: "Fast Casual",
    calories: 420,
    protein: 14,
    carbs: 30,
    fat: 28,
    fiber: 1,
    servingSize: "1 hot dog",
    tags: ["fast-casual", "shake-shack", "hot-dog"],
    chain: "Shake Shack",
    verified: true,
  },
  {
    id: "fc_shakeshack_cheese_fries",
    name: "Shake Shack — Cheese Fries",
    category: "Fast Casual",
    calories: 590,
    protein: 12,
    carbs: 48,
    fat: 40,
    fiber: 4,
    servingSize: "1 order",
    tags: ["fast-casual", "shake-shack", "fries", "cheese"],
    chain: "Shake Shack",
    verified: true,
  },
  {
    id: "fc_shakeshack_concrete",
    name: "Shake Shack — Concrete (Shack Attack, Regular)",
    category: "Fast Casual",
    calories: 810,
    protein: 16,
    carbs: 98,
    fat: 40,
    fiber: 2,
    servingSize: "1 regular",
    tags: ["fast-casual", "shake-shack", "dessert", "ice-cream", "concrete"],
    chain: "Shake Shack",
    verified: true,
  },
  {
    id: "fc_shakeshack_vanilla_shake",
    name: "Shake Shack — Vanilla Shake (Regular)",
    category: "Fast Casual",
    calories: 620,
    protein: 12,
    carbs: 78,
    fat: 28,
    fiber: 0,
    servingSize: "1 regular",
    tags: ["fast-casual", "shake-shack", "milkshake", "dessert"],
    chain: "Shake Shack",
    verified: true,
  },

  // ---------------------------------------------------------------------------
  // SANDWICH & DELI — SUBWAY
  // ---------------------------------------------------------------------------
  {
    id: "deli_subway_turkey_6",
    name: "Subway — 6\" Turkey Breast",
    category: "Sandwich & Deli",
    calories: 270,
    protein: 18,
    carbs: 40,
    fat: 4,
    fiber: 5,
    servingSize: "1 6-inch sub",
    tags: ["sandwich", "deli", "subway", "turkey", "healthy"],
    chain: "Subway",
    verified: true,
  },
  {
    id: "deli_subway_italian_bmt_6",
    name: "Subway — 6\" Italian BMT",
    category: "Sandwich & Deli",
    calories: 370,
    protein: 16,
    carbs: 42,
    fat: 14,
    fiber: 5,
    servingSize: "1 6-inch sub",
    tags: ["sandwich", "deli", "subway", "italian"],
    chain: "Subway",
    verified: true,
  },
  {
    id: "deli_subway_chicken_teriyaki_6",
    name: "Subway — 6\" Chicken Teriyaki",
    category: "Sandwich & Deli",
    calories: 330,
    protein: 22,
    carbs: 44,
    fat: 6,
    fiber: 5,
    servingSize: "1 6-inch sub",
    tags: ["sandwich", "deli", "subway", "chicken", "teriyaki"],
    chain: "Subway",
    verified: true,
  },
  {
    id: "deli_subway_meatball_6",
    name: "Subway — 6\" Meatball Marinara",
    category: "Sandwich & Deli",
    calories: 450,
    protein: 20,
    carbs: 50,
    fat: 18,
    fiber: 5,
    servingSize: "1 6-inch sub",
    tags: ["sandwich", "deli", "subway", "meatball"],
    chain: "Subway",
    verified: true,
  },
  {
    id: "deli_subway_turkey_footlong",
    name: "Subway — Footlong Turkey Breast",
    category: "Sandwich & Deli",
    calories: 540,
    protein: 36,
    carbs: 80,
    fat: 8,
    fiber: 10,
    servingSize: "1 footlong sub",
    tags: ["sandwich", "deli", "subway", "turkey", "footlong"],
    chain: "Subway",
    verified: true,
  },

  // ---------------------------------------------------------------------------
  // SANDWICH & DELI — JERSEY MIKE'S
  // ---------------------------------------------------------------------------
  {
    id: "deli_jm_turkey_provolone",
    name: "Jersey Mike's — Regular Turkey & Provolone",
    category: "Sandwich & Deli",
    calories: 630,
    protein: 32,
    carbs: 52,
    fat: 32,
    fiber: 2,
    servingSize: "1 regular sub",
    tags: ["sandwich", "deli", "jersey-mikes", "turkey"],
    chain: "Jersey Mike's",
    verified: true,
  },
  {
    id: "deli_jm_italian",
    name: "Jersey Mike's — Regular Italian",
    category: "Sandwich & Deli",
    calories: 750,
    protein: 34,
    carbs: 52,
    fat: 42,
    fiber: 2,
    servingSize: "1 regular sub",
    tags: ["sandwich", "deli", "jersey-mikes", "italian"],
    chain: "Jersey Mike's",
    verified: true,
  },
  {
    id: "deli_jm_chicken_cheesesteak",
    name: "Jersey Mike's — Regular Chicken Cheesesteak",
    category: "Sandwich & Deli",
    calories: 680,
    protein: 42,
    carbs: 52,
    fat: 28,
    fiber: 3,
    servingSize: "1 regular sub",
    tags: ["sandwich", "deli", "jersey-mikes", "chicken", "cheesesteak"],
    chain: "Jersey Mike's",
    verified: true,
  },

  // ---------------------------------------------------------------------------
  // SANDWICH & DELI — NYC DELI
  // ---------------------------------------------------------------------------
  {
    id: "deli_chicken_cutlet_hero",
    name: "Chicken Cutlet Hero",
    category: "Sandwich & Deli",
    calories: 680,
    protein: 42,
    carbs: 52,
    fat: 30,
    fiber: 2,
    servingSize: "1 hero",
    tags: ["sandwich", "deli", "chicken", "hero", "classic-nyc"],
    verified: false,
  },
  {
    id: "deli_grilled_chicken_wrap",
    name: "Grilled Chicken Wrap",
    category: "Sandwich & Deli",
    calories: 520,
    protein: 35,
    carbs: 42,
    fat: 20,
    fiber: 3,
    servingSize: "1 wrap",
    tags: ["sandwich", "deli", "chicken", "wrap", "lunch"],
    verified: false,
  },
  {
    id: "deli_tuna_salad_sandwich",
    name: "Tuna Salad Sandwich",
    category: "Sandwich & Deli",
    calories: 580,
    protein: 22,
    carbs: 44,
    fat: 34,
    fiber: 2,
    servingSize: "1 sandwich",
    tags: ["sandwich", "deli", "tuna"],
    verified: false,
  },
  {
    id: "deli_italian_sub",
    name: "Italian Sub/Hero",
    category: "Sandwich & Deli",
    calories: 720,
    protein: 32,
    carbs: 56,
    fat: 38,
    fiber: 2,
    servingSize: "1 hero",
    tags: ["sandwich", "deli", "italian", "hero", "classic-nyc"],
    verified: false,
  },
  {
    id: "deli_chicken_parm_hero",
    name: "Chicken Parm Hero",
    category: "Sandwich & Deli",
    calories: 780,
    protein: 42,
    carbs: 62,
    fat: 34,
    fiber: 3,
    servingSize: "1 hero",
    tags: ["sandwich", "deli", "chicken", "parm", "hero", "classic-nyc"],
    verified: false,
  },

  // ---------------------------------------------------------------------------
  // CHINESE & NOODLES
  // ---------------------------------------------------------------------------
  {
    id: "chinese_pork_bao",
    name: "Pork Bao (Steamed, 1 Bun)",
    category: "Chinese & Noodles",
    calories: 280,
    protein: 12,
    carbs: 34,
    fat: 10,
    fiber: 1,
    servingSize: "1 bun",
    tags: ["chinese", "bao", "pork", "steamed", "dim-sum"],
    verified: false,
  },
  {
    id: "chinese_xlb_single",
    name: "Soup Dumpling / XLB (1 Piece)",
    category: "Chinese & Noodles",
    calories: 55,
    protein: 3,
    carbs: 5,
    fat: 2,
    fiber: 0,
    servingSize: "1 piece",
    tags: ["chinese", "dumpling", "soup-dumpling", "xlb", "dim-sum"],
    verified: false,
  },
  {
    id: "chinese_xlb_8pc",
    name: "Soup Dumplings (8 Piece)",
    category: "Chinese & Noodles",
    calories: 440,
    protein: 24,
    carbs: 40,
    fat: 16,
    fiber: 0,
    servingSize: "8 pieces",
    tags: ["chinese", "dumpling", "soup-dumpling", "xlb", "dim-sum"],
    verified: false,
  },
  {
    id: "chinese_roast_pork_rice",
    name: "Roast Pork over Rice (Chinatown BBQ)",
    category: "Chinese & Noodles",
    calories: 680,
    protein: 35,
    carbs: 72,
    fat: 24,
    fiber: 1,
    servingSize: "1 plate",
    tags: ["chinese", "bbq", "pork", "rice", "chinatown"],
    verified: false,
  },
  {
    id: "chinese_roast_duck_rice",
    name: "Roast Duck over Rice",
    category: "Chinese & Noodles",
    calories: 720,
    protein: 32,
    carbs: 72,
    fat: 28,
    fiber: 1,
    servingSize: "1 plate",
    tags: ["chinese", "bbq", "duck", "rice", "chinatown"],
    verified: false,
  },
  {
    id: "chinese_peking_duck_wrap",
    name: "Peking Duck Wrap (Per Wrap)",
    category: "Chinese & Noodles",
    calories: 240,
    protein: 12,
    carbs: 22,
    fat: 12,
    fiber: 1,
    servingSize: "1 wrap",
    tags: ["chinese", "duck", "peking-duck"],
    verified: false,
  },
  {
    id: "chinese_scallion_pancake",
    name: "Scallion Pancake",
    category: "Chinese & Noodles",
    calories: 230,
    protein: 4,
    carbs: 28,
    fat: 12,
    fiber: 1,
    servingSize: "1 pancake",
    tags: ["chinese", "snack", "appetizer", "scallion"],
    verified: false,
  },
  {
    id: "chinese_xian_hand_pulled",
    name: "Xi'an Famous Foods — Hand-Pulled Noodles (Beef)",
    category: "Chinese & Noodles",
    calories: 580,
    protein: 28,
    carbs: 72,
    fat: 18,
    fiber: 4,
    servingSize: "1 bowl",
    tags: ["chinese", "noodles", "xian", "hand-pulled", "beef", "classic-nyc"],
    chain: "Xi'an Famous Foods",
    verified: false,
  },
  {
    id: "chinese_xian_cumin_lamb",
    name: "Xi'an Famous Foods — Spicy Cumin Lamb Burger",
    category: "Chinese & Noodles",
    calories: 520,
    protein: 22,
    carbs: 48,
    fat: 26,
    fiber: 3,
    servingSize: "1 burger",
    tags: ["chinese", "xian", "lamb", "cumin", "spicy"],
    chain: "Xi'an Famous Foods",
    verified: false,
  },
  {
    id: "chinese_xian_liang_pi",
    name: "Xi'an Famous Foods — Liang Pi Cold Skin Noodles",
    category: "Chinese & Noodles",
    calories: 420,
    protein: 12,
    carbs: 58,
    fat: 16,
    fiber: 3,
    servingSize: "1 bowl",
    tags: ["chinese", "noodles", "xian", "cold-noodles", "spicy"],
    chain: "Xi'an Famous Foods",
    verified: false,
  },
  {
    id: "chinese_general_tsos",
    name: "General Tso's Chicken (1 Pint Takeout)",
    category: "Chinese & Noodles",
    calories: 620,
    protein: 28,
    carbs: 52,
    fat: 32,
    fiber: 2,
    servingSize: "1 pint",
    tags: ["chinese", "chicken", "takeout", "fried"],
    verified: false,
  },
  {
    id: "chinese_lo_mein",
    name: "Lo Mein (1 Pint)",
    category: "Chinese & Noodles",
    calories: 540,
    protein: 18,
    carbs: 68,
    fat: 22,
    fiber: 3,
    servingSize: "1 pint",
    tags: ["chinese", "noodles", "takeout"],
    verified: false,
  },
  {
    id: "chinese_fried_rice",
    name: "Fried Rice (1 Pint)",
    category: "Chinese & Noodles",
    calories: 480,
    protein: 14,
    carbs: 62,
    fat: 18,
    fiber: 2,
    servingSize: "1 pint",
    tags: ["chinese", "rice", "takeout"],
    verified: false,
  },
  {
    id: "chinese_wonton_soup",
    name: "Wonton Soup (Bowl)",
    category: "Chinese & Noodles",
    calories: 260,
    protein: 14,
    carbs: 28,
    fat: 10,
    fiber: 1,
    servingSize: "1 bowl",
    tags: ["chinese", "soup", "wonton"],
    verified: false,
  },
  {
    id: "chinese_egg_drop_soup",
    name: "Egg Drop Soup (Bowl)",
    category: "Chinese & Noodles",
    calories: 120,
    protein: 6,
    carbs: 12,
    fat: 4,
    fiber: 0,
    servingSize: "1 bowl",
    tags: ["chinese", "soup", "egg", "low-calorie"],
    verified: false,
  },

  // ---------------------------------------------------------------------------
  // MEXICAN & TACOS
  // ---------------------------------------------------------------------------
  {
    id: "mexican_lostacos_adobada",
    name: "Los Tacos No. 1 — Adobada Taco",
    category: "Mexican & Tacos",
    calories: 220,
    protein: 12,
    carbs: 18,
    fat: 10,
    fiber: 2,
    servingSize: "1 taco",
    tags: ["mexican", "taco", "los-tacos", "chelsea-market", "adobada", "classic-nyc"],
    chain: "Los Tacos No. 1",
    verified: false,
  },
  {
    id: "mexican_lostacos_carne_asada",
    name: "Los Tacos No. 1 — Carne Asada Taco",
    category: "Mexican & Tacos",
    calories: 250,
    protein: 16,
    carbs: 18,
    fat: 12,
    fiber: 2,
    servingSize: "1 taco",
    tags: ["mexican", "taco", "los-tacos", "chelsea-market", "carne-asada", "steak"],
    chain: "Los Tacos No. 1",
    verified: false,
  },
  {
    id: "mexican_lostacos_nopal",
    name: "Los Tacos No. 1 — Nopal (Cactus) Taco",
    category: "Mexican & Tacos",
    calories: 180,
    protein: 6,
    carbs: 22,
    fat: 8,
    fiber: 4,
    servingSize: "1 taco",
    tags: ["mexican", "taco", "los-tacos", "cactus", "vegetarian", "healthy"],
    chain: "Los Tacos No. 1",
    verified: false,
  },
  {
    id: "mexican_truck_carnitas",
    name: "Generic NYC Taco Truck — Carnitas (1 Taco)",
    category: "Mexican & Tacos",
    calories: 230,
    protein: 14,
    carbs: 20,
    fat: 10,
    fiber: 2,
    servingSize: "1 taco",
    tags: ["mexican", "taco", "street-food", "carnitas", "pork"],
    verified: false,
  },
  {
    id: "mexican_truck_al_pastor",
    name: "Generic NYC Taco Truck — Al Pastor (1 Taco)",
    category: "Mexican & Tacos",
    calories: 220,
    protein: 12,
    carbs: 22,
    fat: 10,
    fiber: 2,
    servingSize: "1 taco",
    tags: ["mexican", "taco", "street-food", "al-pastor", "pork"],
    verified: false,
  },
  {
    id: "mexican_burrito_cart",
    name: "Burrito (Average Food Cart, Beef)",
    category: "Mexican & Tacos",
    calories: 680,
    protein: 32,
    carbs: 72,
    fat: 28,
    fiber: 8,
    servingSize: "1 burrito",
    tags: ["mexican", "burrito", "street-food", "beef"],
    verified: false,
  },
  {
    id: "mexican_quesadilla_cart",
    name: "Quesadilla (Food Cart, Chicken)",
    category: "Mexican & Tacos",
    calories: 520,
    protein: 28,
    carbs: 42,
    fat: 24,
    fiber: 2,
    servingSize: "1 quesadilla",
    tags: ["mexican", "quesadilla", "street-food", "chicken"],
    verified: false,
  },
  {
    id: "mexican_chips_guac",
    name: "Chips & Guac (Restaurant)",
    category: "Mexican & Tacos",
    calories: 480,
    protein: 6,
    carbs: 42,
    fat: 32,
    fiber: 10,
    servingSize: "1 appetizer",
    tags: ["mexican", "chips", "guacamole", "appetizer", "snack"],
    verified: false,
  },
  {
    id: "mexican_tamale_pork",
    name: "Tamale (1 Pork)",
    category: "Mexican & Tacos",
    calories: 280,
    protein: 10,
    carbs: 26,
    fat: 14,
    fiber: 3,
    servingSize: "1 tamale",
    tags: ["mexican", "tamale", "pork", "street-food"],
    verified: false,
  },

  // ---------------------------------------------------------------------------
  // JAPANESE & SUSHI
  // ---------------------------------------------------------------------------
  {
    id: "japanese_spicy_tuna_roll",
    name: "Spicy Tuna Roll (8pc)",
    category: "Japanese & Sushi",
    calories: 350,
    protein: 15,
    carbs: 48,
    fat: 8,
    fiber: 2,
    servingSize: "8 pieces",
    tags: ["japanese", "sushi", "tuna", "spicy"],
    verified: false,
  },
  {
    id: "japanese_california_roll",
    name: "California Roll (8pc)",
    category: "Japanese & Sushi",
    calories: 310,
    protein: 8,
    carbs: 44,
    fat: 10,
    fiber: 2,
    servingSize: "8 pieces",
    tags: ["japanese", "sushi", "crab", "avocado"],
    verified: false,
  },
  {
    id: "japanese_salmon_avo_roll",
    name: "Salmon Avocado Roll (8pc)",
    category: "Japanese & Sushi",
    calories: 360,
    protein: 14,
    carbs: 44,
    fat: 12,
    fiber: 3,
    servingSize: "8 pieces",
    tags: ["japanese", "sushi", "salmon", "avocado"],
    verified: false,
  },
  {
    id: "japanese_dragon_roll",
    name: "Dragon Roll (8pc)",
    category: "Japanese & Sushi",
    calories: 500,
    protein: 14,
    carbs: 56,
    fat: 22,
    fiber: 3,
    servingSize: "8 pieces",
    tags: ["japanese", "sushi", "eel", "avocado", "specialty"],
    verified: false,
  },
  {
    id: "japanese_ramen_tonkotsu",
    name: "Ramen — Tonkotsu (Full Bowl)",
    category: "Japanese & Sushi",
    calories: 680,
    protein: 28,
    carbs: 72,
    fat: 28,
    fiber: 2,
    servingSize: "1 bowl",
    tags: ["japanese", "ramen", "tonkotsu", "pork", "noodles"],
    verified: false,
  },
  {
    id: "japanese_ramen_shoyu",
    name: "Ramen — Shoyu (Full Bowl)",
    category: "Japanese & Sushi",
    calories: 520,
    protein: 24,
    carbs: 68,
    fat: 16,
    fiber: 2,
    servingSize: "1 bowl",
    tags: ["japanese", "ramen", "shoyu", "noodles"],
    verified: false,
  },
  {
    id: "japanese_chicken_teriyaki_bowl",
    name: "Chicken Teriyaki Bowl",
    category: "Japanese & Sushi",
    calories: 580,
    protein: 35,
    carbs: 68,
    fat: 14,
    fiber: 2,
    servingSize: "1 bowl",
    tags: ["japanese", "chicken", "teriyaki", "rice", "bowl"],
    verified: false,
  },
  {
    id: "japanese_poke_bowl",
    name: "Poke Bowl (Tuna, Rice, Avg Toppings)",
    category: "Japanese & Sushi",
    calories: 520,
    protein: 28,
    carbs: 58,
    fat: 16,
    fiber: 4,
    servingSize: "1 bowl",
    tags: ["japanese", "poke", "tuna", "rice", "bowl", "healthy"],
    verified: false,
  },
  {
    id: "japanese_onigiri",
    name: "Onigiri (1 Rice Ball, Salmon)",
    category: "Japanese & Sushi",
    calories: 210,
    protein: 8,
    carbs: 36,
    fat: 2,
    fiber: 1,
    servingSize: "1 rice ball",
    tags: ["japanese", "onigiri", "salmon", "snack", "rice"],
    verified: false,
  },
  {
    id: "japanese_edamame",
    name: "Edamame (Appetizer)",
    category: "Japanese & Sushi",
    calories: 180,
    protein: 16,
    carbs: 14,
    fat: 8,
    fiber: 8,
    servingSize: "1 appetizer",
    tags: ["japanese", "edamame", "appetizer", "healthy", "protein", "vegetarian"],
    verified: false,
  },

  // ---------------------------------------------------------------------------
  // KOREAN
  // ---------------------------------------------------------------------------
  {
    id: "korean_bonchon_soy_garlic",
    name: "Bonchon — 8pc Wings (Soy Garlic)",
    category: "Korean",
    calories: 680,
    protein: 42,
    carbs: 32,
    fat: 38,
    fiber: 0,
    servingSize: "8 wings",
    tags: ["korean", "chicken", "wings", "bonchon", "soy-garlic", "fried"],
    chain: "Bonchon",
    verified: true,
  },
  {
    id: "korean_bonchon_spicy",
    name: "Bonchon — 8pc Wings (Spicy)",
    category: "Korean",
    calories: 720,
    protein: 42,
    carbs: 36,
    fat: 40,
    fiber: 0,
    servingSize: "8 wings",
    tags: ["korean", "chicken", "wings", "bonchon", "spicy", "fried"],
    chain: "Bonchon",
    verified: true,
  },
  {
    id: "korean_bibimbap",
    name: "Bibimbap (Mixed Rice Bowl)",
    category: "Korean",
    calories: 560,
    protein: 24,
    carbs: 72,
    fat: 18,
    fiber: 4,
    servingSize: "1 bowl",
    tags: ["korean", "rice", "bowl", "bibimbap", "mixed"],
    verified: false,
  },
  {
    id: "korean_kfc_sandwich",
    name: "Korean Fried Chicken Sandwich",
    category: "Korean",
    calories: 620,
    protein: 28,
    carbs: 48,
    fat: 34,
    fiber: 2,
    servingSize: "1 sandwich",
    tags: ["korean", "chicken", "fried", "sandwich"],
    verified: false,
  },
  {
    id: "korean_kimchi_jjigae",
    name: "Kimchi Jjigae (Stew, 1 Bowl)",
    category: "Korean",
    calories: 380,
    protein: 22,
    carbs: 28,
    fat: 18,
    fiber: 4,
    servingSize: "1 bowl",
    tags: ["korean", "stew", "kimchi", "spicy", "comfort-food"],
    verified: false,
  },
  {
    id: "korean_japchae",
    name: "Japchae (Glass Noodles)",
    category: "Korean",
    calories: 360,
    protein: 10,
    carbs: 52,
    fat: 12,
    fiber: 3,
    servingSize: "1 plate",
    tags: ["korean", "noodles", "japchae", "glass-noodles"],
    verified: false,
  },
  {
    id: "korean_tteokbokki",
    name: "Tteokbokki (Rice Cakes)",
    category: "Korean",
    calories: 380,
    protein: 8,
    carbs: 68,
    fat: 8,
    fiber: 2,
    servingSize: "1 serving",
    tags: ["korean", "rice-cakes", "tteokbokki", "spicy", "snack"],
    verified: false,
  },

  // ---------------------------------------------------------------------------
  // INDIAN & SOUTH ASIAN
  // ---------------------------------------------------------------------------
  {
    id: "indian_chicken_tikka_masala",
    name: "Chicken Tikka Masala (w/ Rice)",
    category: "Indian & South Asian",
    calories: 620,
    protein: 32,
    carbs: 58,
    fat: 26,
    fiber: 3,
    servingSize: "1 plate",
    tags: ["indian", "chicken", "tikka-masala", "curry", "rice"],
    verified: false,
  },
  {
    id: "indian_saag_paneer",
    name: "Saag Paneer",
    category: "Indian & South Asian",
    calories: 340,
    protein: 16,
    carbs: 14,
    fat: 24,
    fiber: 4,
    servingSize: "1 serving",
    tags: ["indian", "paneer", "spinach", "vegetarian"],
    verified: false,
  },
  {
    id: "indian_lamb_biryani",
    name: "Lamb Biryani",
    category: "Indian & South Asian",
    calories: 680,
    protein: 28,
    carbs: 78,
    fat: 26,
    fiber: 3,
    servingSize: "1 plate",
    tags: ["indian", "lamb", "biryani", "rice"],
    verified: false,
  },
  {
    id: "indian_samosa",
    name: "Samosa (1 Piece)",
    category: "Indian & South Asian",
    calories: 260,
    protein: 6,
    carbs: 28,
    fat: 14,
    fiber: 2,
    servingSize: "1 samosa",
    tags: ["indian", "samosa", "appetizer", "fried", "vegetarian"],
    verified: false,
  },
  {
    id: "indian_naan",
    name: "Naan (1 Piece)",
    category: "Indian & South Asian",
    calories: 260,
    protein: 8,
    carbs: 44,
    fat: 5,
    fiber: 2,
    servingSize: "1 naan",
    tags: ["indian", "bread", "naan"],
    verified: false,
  },
  {
    id: "indian_garlic_naan",
    name: "Garlic Naan",
    category: "Indian & South Asian",
    calories: 300,
    protein: 8,
    carbs: 48,
    fat: 8,
    fiber: 2,
    servingSize: "1 naan",
    tags: ["indian", "bread", "naan", "garlic"],
    verified: false,
  },
  {
    id: "indian_butter_chicken",
    name: "Butter Chicken",
    category: "Indian & South Asian",
    calories: 490,
    protein: 30,
    carbs: 18,
    fat: 32,
    fiber: 2,
    servingSize: "1 serving",
    tags: ["indian", "chicken", "butter-chicken", "curry"],
    verified: false,
  },
  {
    id: "indian_chana_masala",
    name: "Chana Masala",
    category: "Indian & South Asian",
    calories: 320,
    protein: 12,
    carbs: 44,
    fat: 10,
    fiber: 8,
    servingSize: "1 serving",
    tags: ["indian", "chickpea", "vegan", "healthy", "high-fiber"],
    verified: false,
  },
  {
    id: "indian_dosa",
    name: "Dosa (1, Plain)",
    category: "Indian & South Asian",
    calories: 180,
    protein: 4,
    carbs: 32,
    fat: 4,
    fiber: 2,
    servingSize: "1 dosa",
    tags: ["indian", "south-indian", "dosa", "crepe", "vegetarian"],
    verified: false,
  },

  // ---------------------------------------------------------------------------
  // MIDDLE EASTERN
  // ---------------------------------------------------------------------------
  {
    id: "mideast_mamouns_falafel",
    name: "Mamoun's — Falafel Sandwich",
    category: "Middle Eastern",
    calories: 450,
    protein: 14,
    carbs: 52,
    fat: 20,
    fiber: 8,
    servingSize: "1 sandwich",
    tags: ["middle-eastern", "falafel", "mamouns", "greenwich-village", "vegetarian", "classic-nyc"],
    chain: "Mamoun's",
    verified: false,
  },
  {
    id: "mideast_mamouns_shawarma",
    name: "Mamoun's — Shawarma Sandwich (Chicken)",
    category: "Middle Eastern",
    calories: 520,
    protein: 28,
    carbs: 48,
    fat: 22,
    fiber: 3,
    servingSize: "1 sandwich",
    tags: ["middle-eastern", "shawarma", "chicken", "mamouns"],
    chain: "Mamoun's",
    verified: false,
  },
  {
    id: "mideast_mamouns_lamb_platter",
    name: "Mamoun's — Lamb Platter",
    category: "Middle Eastern",
    calories: 680,
    protein: 32,
    carbs: 52,
    fat: 36,
    fiber: 4,
    servingSize: "1 platter",
    tags: ["middle-eastern", "lamb", "mamouns", "platter"],
    chain: "Mamoun's",
    verified: false,
  },
  {
    id: "mideast_hummus_pita",
    name: "Hummus + Pita (Appetizer)",
    category: "Middle Eastern",
    calories: 340,
    protein: 10,
    carbs: 42,
    fat: 14,
    fiber: 6,
    servingSize: "1 appetizer",
    tags: ["middle-eastern", "hummus", "pita", "appetizer", "vegetarian"],
    verified: false,
  },
  {
    id: "mideast_falafel_plate",
    name: "Falafel Plate (4 Balls + Sides)",
    category: "Middle Eastern",
    calories: 620,
    protein: 18,
    carbs: 68,
    fat: 30,
    fiber: 10,
    servingSize: "1 plate",
    tags: ["middle-eastern", "falafel", "vegetarian", "high-fiber"],
    verified: false,
  },
  {
    id: "mideast_baba_ganoush_pita",
    name: "Baba Ganoush + Pita",
    category: "Middle Eastern",
    calories: 320,
    protein: 6,
    carbs: 38,
    fat: 16,
    fiber: 5,
    servingSize: "1 appetizer",
    tags: ["middle-eastern", "baba-ganoush", "eggplant", "pita", "vegetarian"],
    verified: false,
  },
  {
    id: "mideast_shakshuka",
    name: "Shakshuka",
    category: "Middle Eastern",
    calories: 320,
    protein: 16,
    carbs: 18,
    fat: 20,
    fiber: 4,
    servingSize: "1 serving",
    tags: ["middle-eastern", "shakshuka", "egg", "brunch", "vegetarian"],
    verified: false,
  },

  // ---------------------------------------------------------------------------
  // DESSERT & SNACKS
  // ---------------------------------------------------------------------------
  {
    id: "dessert_van_leeuwen_scoop",
    name: "Van Leeuwen — 1 Scoop (Avg)",
    category: "Dessert & Snacks",
    calories: 220,
    protein: 3,
    carbs: 22,
    fat: 14,
    fiber: 0,
    servingSize: "1 scoop",
    tags: ["dessert", "ice-cream", "van-leeuwen", "classic-nyc"],
    chain: "Van Leeuwen",
    verified: false,
  },
  {
    id: "dessert_milk_bar_cereal_milk",
    name: "Milk Bar — Cereal Milk Soft Serve (Regular)",
    category: "Dessert & Snacks",
    calories: 340,
    protein: 6,
    carbs: 42,
    fat: 16,
    fiber: 0,
    servingSize: "1 regular",
    tags: ["dessert", "ice-cream", "milk-bar", "cereal-milk", "classic-nyc"],
    chain: "Milk Bar",
    verified: false,
  },
  {
    id: "dessert_milk_bar_birthday_truffle",
    name: "Milk Bar — Birthday Cake Truffle (1)",
    category: "Dessert & Snacks",
    calories: 180,
    protein: 2,
    carbs: 20,
    fat: 10,
    fiber: 0,
    servingSize: "1 truffle",
    tags: ["dessert", "cake", "milk-bar", "truffle"],
    chain: "Milk Bar",
    verified: false,
  },
  {
    id: "dessert_mister_softee",
    name: "Mister Softee — Medium Cone (Vanilla)",
    category: "Dessert & Snacks",
    calories: 280,
    protein: 4,
    carbs: 38,
    fat: 12,
    fiber: 0,
    servingSize: "1 medium cone",
    tags: ["dessert", "ice-cream", "mister-softee", "summer", "classic-nyc"],
    verified: false,
  },
  {
    id: "dessert_nyc_diner_cheesecake",
    name: "NYC Diner Cheesecake (1 Slice)",
    category: "Dessert & Snacks",
    calories: 480,
    protein: 8,
    carbs: 42,
    fat: 32,
    fiber: 0,
    servingSize: "1 slice",
    tags: ["dessert", "cheesecake", "diner", "classic-nyc"],
    verified: false,
  },
  {
    id: "dessert_magnolia_banana_pudding",
    name: "Magnolia Bakery — Banana Pudding (Individual)",
    category: "Dessert & Snacks",
    calories: 380,
    protein: 4,
    carbs: 48,
    fat: 18,
    fiber: 1,
    servingSize: "1 individual cup",
    tags: ["dessert", "banana-pudding", "magnolia", "classic-nyc"],
    chain: "Magnolia Bakery",
    verified: false,
  },

  // ---------------------------------------------------------------------------
  // ICONIC NYC SPOTS
  // ---------------------------------------------------------------------------
  {
    id: "iconic_katzs_pastrami",
    name: "Katz's Deli — Pastrami on Rye",
    description: "NYC's most famous deli sandwich since 1888",
    category: "Iconic NYC Spots",
    calories: 780,
    protein: 48,
    carbs: 38,
    fat: 46,
    fiber: 2,
    servingSize: "1 sandwich",
    tags: ["iconic", "deli", "pastrami", "katzs", "les", "classic-nyc"],
    chain: "Katz's Deli",
    verified: false,
  },
  {
    id: "iconic_katzs_corned_beef",
    name: "Katz's Deli — Corned Beef on Rye",
    category: "Iconic NYC Spots",
    calories: 720,
    protein: 44,
    carbs: 38,
    fat: 40,
    fiber: 2,
    servingSize: "1 sandwich",
    tags: ["iconic", "deli", "corned-beef", "katzs", "les", "classic-nyc"],
    chain: "Katz's Deli",
    verified: false,
  },
  {
    id: "iconic_russ_daughters_lox_bagel",
    name: "Russ & Daughters — Classic Bagel w/ Lox + CC",
    category: "Iconic NYC Spots",
    calories: 620,
    protein: 28,
    carbs: 60,
    fat: 28,
    fiber: 3,
    servingSize: "1 bagel",
    tags: ["iconic", "bagel", "lox", "smoked-salmon", "russ-daughters", "les", "classic-nyc"],
    chain: "Russ & Daughters",
    verified: false,
  },
  {
    id: "iconic_grays_papaya",
    name: "Gray's Papaya — 2 Dogs + Papaya Drink",
    category: "Iconic NYC Spots",
    calories: 680,
    protein: 20,
    carbs: 82,
    fat: 28,
    fiber: 2,
    servingSize: "1 combo",
    tags: ["iconic", "hot-dog", "grays-papaya", "uws", "classic-nyc", "cheap-eats"],
    chain: "Gray's Papaya",
    verified: false,
  },
  {
    id: "iconic_halal_guys_chicken",
    name: "Halal Guys (Brick & Mortar) — Chicken Platter",
    category: "Iconic NYC Spots",
    calories: 820,
    protein: 44,
    carbs: 70,
    fat: 38,
    fiber: 3,
    servingSize: "1 platter",
    tags: ["iconic", "halal", "chicken", "rice", "halal-guys", "midtown", "classic-nyc"],
    chain: "The Halal Guys",
    verified: false,
  },
  {
    id: "iconic_peter_luger_steak",
    name: "Peter Luger — Steak for One",
    category: "Iconic NYC Spots",
    calories: 980,
    protein: 72,
    carbs: 0,
    fat: 74,
    fiber: 0,
    servingSize: "1 steak",
    tags: ["iconic", "steak", "peter-luger", "williamsburg", "brooklyn", "classic-nyc"],
    chain: "Peter Luger",
    verified: false,
  },
  {
    id: "iconic_grimaldis_cheese",
    name: "Grimaldi's — Cheese Slice (Coal-Fired)",
    category: "Iconic NYC Spots",
    calories: 340,
    protein: 14,
    carbs: 38,
    fat: 14,
    fiber: 2,
    servingSize: "1 slice",
    tags: ["iconic", "pizza", "grimaldis", "dumbo", "brooklyn", "coal-fired", "classic-nyc"],
    chain: "Grimaldi's",
    verified: false,
  },
  {
    id: "iconic_julianas_margherita",
    name: "Juliana's — Margherita Slice",
    category: "Iconic NYC Spots",
    calories: 320,
    protein: 12,
    carbs: 36,
    fat: 12,
    fiber: 2,
    servingSize: "1 slice",
    tags: ["iconic", "pizza", "julianas", "dumbo", "brooklyn", "classic-nyc"],
    chain: "Juliana's",
    verified: false,
  },

  // ---------------------------------------------------------------------------
  // GROCERY & PREPARED
  // ---------------------------------------------------------------------------
  {
    id: "grocery_wf_hot_bar",
    name: "Whole Foods Hot Bar — Per Pound (Avg)",
    category: "Grocery & Prepared",
    calories: 200,
    protein: 12,
    carbs: 18,
    fat: 10,
    fiber: 3,
    servingSize: "per pound (avg portion ~0.5 lb)",
    tags: ["grocery", "whole-foods", "hot-bar", "prepared"],
    chain: "Whole Foods",
    verified: false,
  },
  {
    id: "grocery_wf_sushi_spicy_tuna",
    name: "Whole Foods Sushi Roll — Spicy Tuna (8pc)",
    category: "Grocery & Prepared",
    calories: 350,
    protein: 15,
    carbs: 48,
    fat: 8,
    fiber: 2,
    servingSize: "8 pieces",
    tags: ["grocery", "whole-foods", "sushi", "tuna"],
    chain: "Whole Foods",
    verified: false,
  },
  {
    id: "grocery_tj_tikka_masala",
    name: "Trader Joe's — Chicken Tikka Masala (1 Package)",
    category: "Grocery & Prepared",
    calories: 340,
    protein: 22,
    carbs: 42,
    fat: 8,
    fiber: 2,
    servingSize: "1 package",
    tags: ["grocery", "trader-joes", "indian", "chicken", "frozen"],
    chain: "Trader Joe's",
    verified: false,
  },
  {
    id: "grocery_tj_orange_chicken",
    name: "Trader Joe's — Orange Chicken (1 Serving)",
    category: "Grocery & Prepared",
    calories: 320,
    protein: 16,
    carbs: 38,
    fat: 12,
    fiber: 1,
    servingSize: "1 serving",
    tags: ["grocery", "trader-joes", "chicken", "chinese", "frozen"],
    chain: "Trader Joe's",
    verified: false,
  },
  {
    id: "grocery_tj_cauliflower_gnocchi",
    name: "Trader Joe's — Cauliflower Gnocchi (1 Serving)",
    category: "Grocery & Prepared",
    calories: 140,
    protein: 2,
    carbs: 22,
    fat: 5,
    fiber: 2,
    servingSize: "1 serving",
    tags: ["grocery", "trader-joes", "cauliflower", "gnocchi", "low-calorie", "vegetarian"],
    chain: "Trader Joe's",
    verified: false,
  },
  {
    id: "grocery_salad_bar",
    name: "Salad Bar — Mixed Greens + Protein (12oz)",
    category: "Grocery & Prepared",
    calories: 350,
    protein: 25,
    carbs: 20,
    fat: 18,
    fiber: 5,
    servingSize: "12oz container",
    tags: ["grocery", "salad", "healthy", "lunch", "high-protein"],
    verified: false,
  },
  {
    id: "grocery_rotisserie_chicken_quarter",
    name: "Deli Counter — Rotisserie Chicken (1/4)",
    category: "Grocery & Prepared",
    calories: 320,
    protein: 38,
    carbs: 0,
    fat: 18,
    fiber: 0,
    servingSize: "1/4 chicken",
    tags: ["grocery", "chicken", "rotisserie", "high-protein"],
    verified: false,
  },
];

// =============================================================================
// SEARCH FUNCTION
// =============================================================================

export function searchNycDatabase(query: string): NycFoodItem[] {
  if (!query || query.trim().length === 0) return [];

  const lowerQuery = query.toLowerCase().trim();
  const words = lowerQuery.split(/\s+/).filter((w) => w.length > 0);

  const scored: { item: NycFoodItem; score: number }[] = [];

  for (const item of NYC_FOOD_DATABASE) {
    let score = 0;
    const lowerName = item.name.toLowerCase();
    const lowerDesc = (item.description ?? "").toLowerCase();
    const lowerChain = (item.chain ?? "").toLowerCase();
    const lowerCategory = item.category.toLowerCase();
    const lowerTags = item.tags.map((t) => t.toLowerCase());

    // Exact full-name match
    if (lowerName === lowerQuery) {
      score += 10;
    }

    // Per-word scoring
    for (const word of words) {
      if (lowerName.includes(word)) {
        score += 5;
      }
      if (lowerChain.includes(word)) {
        score += 3;
      }
      for (const tag of lowerTags) {
        if (tag.includes(word) || word.includes(tag)) {
          score += 2;
          break; // only count once per word per item
        }
      }
      if (lowerCategory.includes(word)) {
        score += 1;
      }
      if (lowerDesc.includes(word)) {
        score += 1;
      }
    }

    if (score > 0) {
      scored.push({ item, score });
    }
  }

  scored.sort((a, b) => b.score - a.score);

  return scored.slice(0, 15).map((s) => s.item);
}
