/**
 * NYC Popular Food Database — common street foods, bodega items, and cultural staples
 * that people search for but don't appear in USDA/OFF databases accurately.
 *
 * Nutrition values are estimates based on averaged published sources (Nutritionix, CalorieKing,
 * chain-published data, and USDA composites). Serving sizes reflect NYC typical portions.
 */

export interface PopularFood {
  name: string;
  aliases: string[];        // search terms that should match this food
  brand: string;            // e.g. "NYC Halal Cart", "Bodega Classic", "Street Food"
  servingSize: string;
  calories: number;
  protein: number;
  fat: number;
  carbs: number;
  sodium: number;
  fiber: number;
  sugar: number;
  category: string;         // for grouping
  popularity: number;       // 1-10, used for ranking
}

export const POPULAR_FOODS: PopularFood[] = [
  // ── HALAL CART ──────────────────────────────────────────────
  {
    name: "Chicken Over Rice (Halal Cart)",
    aliases: ["chicken over rice", "halal chicken", "halal cart chicken", "halal chicken platter", "chicken rice platter", "halal platter", "chicken and rice halal", "chicken over rice halal cart", "halal guys chicken"],
    brand: "NYC Halal Cart",
    servingSize: "1 platter (~680g)",
    calories: 900,
    protein: 48,
    fat: 32,
    carbs: 100,
    sodium: 1800,
    fiber: 3,
    sugar: 6,
    category: "Street Food",
    popularity: 10,
  },
  {
    name: "Lamb Over Rice (Halal Cart)",
    aliases: ["lamb over rice", "halal lamb", "lamb rice platter", "halal lamb platter", "gyro platter", "lamb and rice"],
    brand: "NYC Halal Cart",
    servingSize: "1 platter (~700g)",
    calories: 1050,
    protein: 45,
    fat: 45,
    carbs: 105,
    sodium: 2100,
    fiber: 3,
    sugar: 5,
    category: "Street Food",
    popularity: 9,
  },
  {
    name: "Combo Over Rice (Halal Cart)",
    aliases: ["combo over rice", "chicken lamb over rice", "combo platter halal", "mixed platter halal"],
    brand: "NYC Halal Cart",
    servingSize: "1 platter (~700g)",
    calories: 980,
    protein: 46,
    fat: 38,
    carbs: 102,
    sodium: 1950,
    fiber: 3,
    sugar: 5,
    category: "Street Food",
    popularity: 8,
  },
  {
    name: "Falafel Over Rice",
    aliases: ["falafel over rice", "falafel platter", "halal falafel", "falafel rice"],
    brand: "NYC Halal Cart",
    servingSize: "1 platter (~600g)",
    calories: 750,
    protein: 22,
    fat: 28,
    carbs: 105,
    sodium: 1400,
    fiber: 8,
    sugar: 5,
    category: "Street Food",
    popularity: 7,
  },
  {
    name: "Chicken Gyro (Halal Cart)",
    aliases: ["chicken gyro", "halal chicken gyro", "chicken wrap halal"],
    brand: "NYC Halal Cart",
    servingSize: "1 wrap",
    calories: 550,
    protein: 30,
    fat: 22,
    carbs: 55,
    sodium: 1200,
    fiber: 3,
    sugar: 4,
    category: "Street Food",
    popularity: 8,
  },

  // ── BODEGA / DELI ──────────────────────────────────────────
  {
    name: "Bacon Egg & Cheese (Bodega)",
    aliases: ["bacon egg and cheese", "bec", "bacon egg cheese", "bodega breakfast", "baconeggandcheese", "bacon egg cheese roll", "bec on a roll"],
    brand: "NYC Bodega",
    servingSize: "1 sandwich on roll",
    calories: 520,
    protein: 24,
    fat: 28,
    carbs: 42,
    sodium: 1150,
    fiber: 1,
    sugar: 4,
    category: "Bodega",
    popularity: 10,
  },
  {
    name: "Sausage Egg & Cheese (Bodega)",
    aliases: ["sausage egg and cheese", "sec", "sausage egg cheese", "sausage egg cheese roll"],
    brand: "NYC Bodega",
    servingSize: "1 sandwich on roll",
    calories: 580,
    protein: 26,
    fat: 34,
    carbs: 42,
    sodium: 1300,
    fiber: 1,
    sugar: 4,
    category: "Bodega",
    popularity: 7,
  },
  {
    name: "Chopped Cheese",
    aliases: ["chopped cheese", "chop cheese", "chopped cheese sandwich", "harlem chopped cheese"],
    brand: "NYC Bodega",
    servingSize: "1 sandwich on hero",
    calories: 780,
    protein: 38,
    fat: 42,
    carbs: 60,
    sodium: 1600,
    fiber: 3,
    sugar: 6,
    category: "Bodega",
    popularity: 9,
  },
  {
    name: "Bodega Turkey & Cheese Sandwich",
    aliases: ["turkey and cheese", "turkey sandwich bodega", "deli turkey sandwich", "turkey hero"],
    brand: "NYC Bodega",
    servingSize: "1 hero (~12\")",
    calories: 620,
    protein: 35,
    fat: 24,
    carbs: 64,
    sodium: 1800,
    fiber: 3,
    sugar: 6,
    category: "Bodega",
    popularity: 6,
  },

  // ── PIZZA ──────────────────────────────────────────────────
  {
    name: "NYC Cheese Slice",
    aliases: ["cheese slice", "plain slice", "pizza slice", "nyc pizza", "cheese pizza slice", "regular slice", "new york slice", "ny slice", "dollar slice"],
    brand: "NYC Pizza Shop",
    servingSize: "1 large slice",
    calories: 280,
    protein: 12,
    fat: 10,
    carbs: 36,
    sodium: 640,
    fiber: 2,
    sugar: 4,
    category: "Pizza",
    popularity: 10,
  },
  {
    name: "NYC Pepperoni Slice",
    aliases: ["pepperoni slice", "pepperoni pizza slice", "pep slice"],
    brand: "NYC Pizza Shop",
    servingSize: "1 large slice",
    calories: 340,
    protein: 15,
    fat: 15,
    carbs: 36,
    sodium: 810,
    fiber: 2,
    sugar: 4,
    category: "Pizza",
    popularity: 8,
  },
  {
    name: "Sicilian Slice",
    aliases: ["sicilian slice", "sicilian pizza", "square slice", "grandma slice", "thick slice"],
    brand: "NYC Pizza Shop",
    servingSize: "1 square slice",
    calories: 420,
    protein: 16,
    fat: 18,
    carbs: 48,
    sodium: 880,
    fiber: 2,
    sugar: 5,
    category: "Pizza",
    popularity: 6,
  },

  // ── COFFEE & DRINKS ────────────────────────────────────────
  {
    name: "Iced Coffee (Medium, Black)",
    aliases: ["iced coffee", "cold brew", "iced coffee black", "dunkin iced coffee"],
    brand: "Coffee Shop",
    servingSize: "16 oz",
    calories: 5,
    protein: 0,
    fat: 0,
    carbs: 0,
    sodium: 10,
    fiber: 0,
    sugar: 0,
    category: "Coffee",
    popularity: 8,
  },
  {
    name: "Iced Coffee with Cream & Sugar",
    aliases: ["iced coffee cream sugar", "iced coffee regular", "iced coffee light and sweet", "iced regular"],
    brand: "Coffee Shop",
    servingSize: "16 oz",
    calories: 120,
    protein: 2,
    fat: 4,
    carbs: 20,
    sodium: 40,
    fiber: 0,
    sugar: 18,
    category: "Coffee",
    popularity: 7,
  },
  {
    name: "Oat Milk Latte",
    aliases: ["oat milk latte", "oatmilk latte", "oat latte", "iced oat milk latte"],
    brand: "Coffee Shop",
    servingSize: "16 oz",
    calories: 170,
    protein: 3,
    fat: 5,
    carbs: 28,
    sodium: 110,
    fiber: 2,
    sugar: 16,
    category: "Coffee",
    popularity: 8,
  },
  {
    name: "Matcha Latte",
    aliases: ["matcha latte", "matcha green tea latte", "iced matcha", "matcha oat milk"],
    brand: "Coffee Shop",
    servingSize: "16 oz",
    calories: 190,
    protein: 4,
    fat: 5,
    carbs: 32,
    sodium: 120,
    fiber: 1,
    sugar: 25,
    category: "Coffee",
    popularity: 7,
  },

  // ── BOWLS & HEALTHY ────────────────────────────────────────
  {
    name: "Açaí Bowl",
    aliases: ["acai bowl", "açaí bowl", "acai", "acai berry bowl", "playa bowls acai"],
    brand: "Juice Bar",
    servingSize: "1 regular bowl (~450g)",
    calories: 490,
    protein: 8,
    fat: 12,
    carbs: 88,
    sodium: 30,
    fiber: 8,
    sugar: 62,
    category: "Healthy",
    popularity: 8,
  },
  {
    name: "Poke Bowl (Tuna)",
    aliases: ["poke bowl", "tuna poke bowl", "poke", "raw tuna bowl", "ahi poke"],
    brand: "Poke Shop",
    servingSize: "1 regular bowl",
    calories: 550,
    protein: 32,
    fat: 18,
    carbs: 65,
    sodium: 1200,
    fiber: 4,
    sugar: 8,
    category: "Healthy",
    popularity: 7,
  },
  {
    name: "Avocado Toast",
    aliases: ["avocado toast", "avo toast", "avocado on toast", "smashed avo"],
    brand: "NYC Café",
    servingSize: "2 slices sourdough",
    calories: 380,
    protein: 10,
    fat: 22,
    carbs: 38,
    sodium: 420,
    fiber: 8,
    sugar: 2,
    category: "Healthy",
    popularity: 8,
  },
  {
    name: "Green Juice",
    aliases: ["green juice", "kale juice", "celery juice", "green smoothie juice"],
    brand: "Juice Bar",
    servingSize: "16 oz",
    calories: 120,
    protein: 4,
    fat: 1,
    carbs: 26,
    sodium: 140,
    fiber: 2,
    sugar: 18,
    category: "Healthy",
    popularity: 6,
  },
  {
    name: "Protein Smoothie",
    aliases: ["protein smoothie", "protein shake", "post workout smoothie", "whey smoothie"],
    brand: "Smoothie Shop",
    servingSize: "20 oz",
    calories: 350,
    protein: 30,
    fat: 8,
    carbs: 42,
    sodium: 200,
    fiber: 4,
    sugar: 28,
    category: "Healthy",
    popularity: 7,
  },

  // ── CHINESE / ASIAN ────────────────────────────────────────
  {
    name: "General Tso's Chicken",
    aliases: ["general tsos chicken", "general tso", "general tso's", "general chicken", "chinese chicken"],
    brand: "Chinese Takeout",
    servingSize: "1 entrée with rice",
    calories: 1020,
    protein: 42,
    fat: 38,
    carbs: 120,
    sodium: 2200,
    fiber: 3,
    sugar: 28,
    category: "Chinese",
    popularity: 8,
  },
  {
    name: "Chicken Lo Mein",
    aliases: ["chicken lo mein", "lo mein", "lo mein chicken", "chinese noodles chicken"],
    brand: "Chinese Takeout",
    servingSize: "1 pint container",
    calories: 580,
    protein: 24,
    fat: 18,
    carbs: 78,
    sodium: 1400,
    fiber: 3,
    sugar: 8,
    category: "Chinese",
    popularity: 8,
  },
  {
    name: "Pork Fried Rice",
    aliases: ["pork fried rice", "fried rice", "chinese fried rice", "house fried rice"],
    brand: "Chinese Takeout",
    servingSize: "1 pint container",
    calories: 520,
    protein: 18,
    fat: 16,
    carbs: 76,
    sodium: 1100,
    fiber: 2,
    sugar: 3,
    category: "Chinese",
    popularity: 7,
  },
  {
    name: "Sesame Chicken",
    aliases: ["sesame chicken", "sesame chicken chinese"],
    brand: "Chinese Takeout",
    servingSize: "1 entrée with rice",
    calories: 940,
    protein: 38,
    fat: 32,
    carbs: 118,
    sodium: 1800,
    fiber: 2,
    sugar: 32,
    category: "Chinese",
    popularity: 7,
  },
  {
    name: "Beef & Broccoli",
    aliases: ["beef and broccoli", "beef broccoli", "broccoli beef chinese"],
    brand: "Chinese Takeout",
    servingSize: "1 entrée with rice",
    calories: 680,
    protein: 35,
    fat: 22,
    carbs: 82,
    sodium: 1500,
    fiber: 4,
    sugar: 8,
    category: "Chinese",
    popularity: 7,
  },

  // ── DUMPLINGS / DIM SUM ────────────────────────────────────
  {
    name: "Pork Dumplings (Steamed)",
    aliases: ["pork dumplings", "steamed dumplings", "chinese dumplings", "jiaozi", "dumpling"],
    brand: "Chinese / Dim Sum",
    servingSize: "8 dumplings",
    calories: 380,
    protein: 18,
    fat: 14,
    carbs: 44,
    sodium: 850,
    fiber: 2,
    sugar: 2,
    category: "Chinese",
    popularity: 7,
  },
  {
    name: "Soup Dumplings (Xiao Long Bao)",
    aliases: ["soup dumplings", "xiao long bao", "xlb", "shanghai dumplings", "juicy dumplings"],
    brand: "Chinese / Dim Sum",
    servingSize: "8 dumplings",
    calories: 440,
    protein: 20,
    fat: 18,
    carbs: 48,
    sodium: 920,
    fiber: 1,
    sugar: 3,
    category: "Chinese",
    popularity: 8,
  },

  // ── BAGELS ─────────────────────────────────────────────────
  {
    name: "Everything Bagel with Cream Cheese",
    aliases: ["everything bagel", "bagel cream cheese", "bagel with cream cheese", "nyc bagel", "everything with cream cheese"],
    brand: "NYC Bagel Shop",
    servingSize: "1 bagel + 2 oz cream cheese",
    calories: 450,
    protein: 14,
    fat: 18,
    carbs: 56,
    sodium: 780,
    fiber: 2,
    sugar: 6,
    category: "Bagel",
    popularity: 9,
  },
  {
    name: "Bagel with Lox",
    aliases: ["bagel with lox", "lox bagel", "salmon bagel", "smoked salmon bagel", "bagel lox cream cheese"],
    brand: "NYC Bagel Shop",
    servingSize: "1 bagel + lox + cream cheese",
    calories: 530,
    protein: 24,
    fat: 20,
    carbs: 58,
    sodium: 1200,
    fiber: 2,
    sugar: 6,
    category: "Bagel",
    popularity: 7,
  },

  // ── TACOS / MEXICAN ────────────────────────────────────────
  {
    name: "Street Tacos (Chicken, 3)",
    aliases: ["street tacos", "chicken tacos", "taco truck tacos", "birria tacos", "tacos"],
    brand: "Taco Truck",
    servingSize: "3 tacos",
    calories: 480,
    protein: 30,
    fat: 18,
    carbs: 48,
    sodium: 900,
    fiber: 4,
    sugar: 3,
    category: "Mexican",
    popularity: 7,
  },
  {
    name: "Burrito (Chicken)",
    aliases: ["chicken burrito", "burrito", "mission style burrito", "burrito chicken rice beans"],
    brand: "Mexican Spot",
    servingSize: "1 large burrito",
    calories: 850,
    protein: 42,
    fat: 28,
    carbs: 102,
    sodium: 1800,
    fiber: 10,
    sugar: 4,
    category: "Mexican",
    popularity: 7,
  },
  {
    name: "Quesadilla (Cheese)",
    aliases: ["quesadilla", "cheese quesadilla", "chicken quesadilla"],
    brand: "Mexican Spot",
    servingSize: "1 large quesadilla",
    calories: 620,
    protein: 28,
    fat: 32,
    carbs: 52,
    sodium: 1200,
    fiber: 3,
    sugar: 2,
    category: "Mexican",
    popularity: 6,
  },

  // ── SUSHI ──────────────────────────────────────────────────
  {
    name: "Salmon Sushi Roll (8 pieces)",
    aliases: ["salmon roll", "salmon sushi", "salmon maki", "sushi roll"],
    brand: "Sushi Bar",
    servingSize: "8 pieces",
    calories: 310,
    protein: 14,
    fat: 8,
    carbs: 46,
    sodium: 620,
    fiber: 2,
    sugar: 6,
    category: "Japanese",
    popularity: 7,
  },
  {
    name: "Spicy Tuna Roll (8 pieces)",
    aliases: ["spicy tuna roll", "spicy tuna", "spicy tuna maki"],
    brand: "Sushi Bar",
    servingSize: "8 pieces",
    calories: 340,
    protein: 16,
    fat: 12,
    carbs: 42,
    sodium: 680,
    fiber: 2,
    sugar: 5,
    category: "Japanese",
    popularity: 7,
  },
  {
    name: "California Roll (8 pieces)",
    aliases: ["california roll", "cali roll", "california sushi"],
    brand: "Sushi Bar",
    servingSize: "8 pieces",
    calories: 260,
    protein: 8,
    fat: 6,
    carbs: 44,
    sodium: 540,
    fiber: 3,
    sugar: 6,
    category: "Japanese",
    popularity: 6,
  },
  {
    name: "Dragon Roll (8 pieces)",
    aliases: ["dragon roll", "eel avocado roll"],
    brand: "Sushi Bar",
    servingSize: "8 pieces",
    calories: 440,
    protein: 14,
    fat: 16,
    carbs: 58,
    sodium: 780,
    fiber: 3,
    sugar: 10,
    category: "Japanese",
    popularity: 6,
  },

  // ── RAMEN ──────────────────────────────────────────────────
  {
    name: "Tonkotsu Ramen",
    aliases: ["tonkotsu ramen", "ramen", "pork ramen", "ramen noodles", "japanese ramen"],
    brand: "Ramen Shop",
    servingSize: "1 bowl (~650ml)",
    calories: 780,
    protein: 35,
    fat: 32,
    carbs: 82,
    sodium: 2400,
    fiber: 3,
    sugar: 4,
    category: "Japanese",
    popularity: 8,
  },
  {
    name: "Shoyu Ramen",
    aliases: ["shoyu ramen", "soy sauce ramen"],
    brand: "Ramen Shop",
    servingSize: "1 bowl",
    calories: 620,
    protein: 28,
    fat: 22,
    carbs: 76,
    sodium: 2200,
    fiber: 2,
    sugar: 4,
    category: "Japanese",
    popularity: 6,
  },

  // ── BUBBLE TEA ─────────────────────────────────────────────
  {
    name: "Boba Milk Tea (Brown Sugar)",
    aliases: ["boba", "bubble tea", "boba tea", "milk tea boba", "brown sugar boba", "tiger sugar boba", "boba milk tea"],
    brand: "Boba Shop",
    servingSize: "16 oz with tapioca",
    calories: 380,
    protein: 4,
    fat: 8,
    carbs: 72,
    sodium: 80,
    fiber: 0,
    sugar: 48,
    category: "Drinks",
    popularity: 8,
  },
  {
    name: "Taro Milk Tea with Boba",
    aliases: ["taro milk tea", "taro boba", "taro bubble tea"],
    brand: "Boba Shop",
    servingSize: "16 oz with tapioca",
    calories: 420,
    protein: 3,
    fat: 10,
    carbs: 78,
    sodium: 90,
    fiber: 1,
    sugar: 52,
    category: "Drinks",
    popularity: 6,
  },

  // ── INDIAN ─────────────────────────────────────────────────
  {
    name: "Chicken Tikka Masala with Rice",
    aliases: ["chicken tikka masala", "tikka masala", "butter chicken", "indian chicken"],
    brand: "Indian Restaurant",
    servingSize: "1 entrée with rice",
    calories: 750,
    protein: 38,
    fat: 28,
    carbs: 82,
    sodium: 1400,
    fiber: 4,
    sugar: 8,
    category: "Indian",
    popularity: 7,
  },
  {
    name: "Saag Paneer with Naan",
    aliases: ["saag paneer", "palak paneer", "spinach paneer"],
    brand: "Indian Restaurant",
    servingSize: "1 entrée with naan",
    calories: 680,
    protein: 22,
    fat: 32,
    carbs: 72,
    sodium: 1200,
    fiber: 6,
    sugar: 5,
    category: "Indian",
    popularity: 5,
  },
  {
    name: "Chicken Biryani",
    aliases: ["chicken biryani", "biryani", "lamb biryani", "hyderabadi biryani"],
    brand: "Indian Restaurant",
    servingSize: "1 entrée",
    calories: 620,
    protein: 32,
    fat: 18,
    carbs: 82,
    sodium: 1100,
    fiber: 3,
    sugar: 4,
    category: "Indian",
    popularity: 6,
  },

  // ── DELI / SANDWICH ────────────────────────────────────────
  {
    name: "Italian Hero (Cold Cuts)",
    aliases: ["italian hero", "italian sub", "italian sandwich", "cold cuts hero", "deli hero"],
    brand: "NYC Deli",
    servingSize: "1 hero (~12\")",
    calories: 820,
    protein: 38,
    fat: 40,
    carbs: 68,
    sodium: 2400,
    fiber: 3,
    sugar: 6,
    category: "Deli",
    popularity: 6,
  },
  {
    name: "Pastrami on Rye",
    aliases: ["pastrami on rye", "pastrami sandwich", "katz pastrami", "deli pastrami"],
    brand: "NYC Deli",
    servingSize: "1 sandwich",
    calories: 680,
    protein: 42,
    fat: 30,
    carbs: 52,
    sodium: 2200,
    fiber: 4,
    sugar: 3,
    category: "Deli",
    popularity: 7,
  },

  // ── BREAKFAST ──────────────────────────────────────────────
  {
    name: "Egg & Cheese on Roll",
    aliases: ["egg and cheese", "egg cheese roll", "egg sandwich", "egg on a roll"],
    brand: "NYC Bodega",
    servingSize: "1 sandwich on roll",
    calories: 360,
    protein: 18,
    fat: 16,
    carbs: 36,
    sodium: 620,
    fiber: 1,
    sugar: 3,
    category: "Breakfast",
    popularity: 7,
  },
  {
    name: "Buttered Roll",
    aliases: ["buttered roll", "butter roll", "hard roll with butter"],
    brand: "NYC Bodega",
    servingSize: "1 roll",
    calories: 280,
    protein: 6,
    fat: 10,
    carbs: 40,
    sodium: 380,
    fiber: 1,
    sugar: 4,
    category: "Breakfast",
    popularity: 6,
  },

  // ── SNACKS ─────────────────────────────────────────────────
  {
    name: "Soft Pretzel (Street Cart)",
    aliases: ["soft pretzel", "street pretzel", "nyc pretzel", "pretzel cart"],
    brand: "NYC Street Cart",
    servingSize: "1 large pretzel",
    calories: 340,
    protein: 8,
    fat: 4,
    carbs: 68,
    sodium: 920,
    fiber: 2,
    sugar: 2,
    category: "Street Food",
    popularity: 5,
  },
  {
    name: "Hot Dog (Street Cart)",
    aliases: ["hot dog", "street hot dog", "nyc hot dog", "dirty water dog", "hot dog with mustard"],
    brand: "NYC Street Cart",
    servingSize: "1 hot dog with bun",
    calories: 280,
    protein: 10,
    fat: 16,
    carbs: 24,
    sodium: 780,
    fiber: 1,
    sugar: 4,
    category: "Street Food",
    popularity: 7,
  },
  {
    name: "Knish (Potato)",
    aliases: ["knish", "potato knish", "knish street cart"],
    brand: "NYC Street Cart",
    servingSize: "1 knish",
    calories: 330,
    protein: 8,
    fat: 14,
    carbs: 44,
    sodium: 680,
    fiber: 3,
    sugar: 2,
    category: "Street Food",
    popularity: 4,
  },
];

/**
 * Search popular foods using fuzzy matching.
 * Returns scored results sorted by relevance.
 */
export function searchPopularFoods(query: string): (PopularFood & { score: number })[] {
  const q = query.toLowerCase().trim();
  if (q.length < 2) return [];

  const words = q.split(/\s+/).filter(w => w.length >= 2);
  const results: (PopularFood & { score: number })[] = [];

  for (const food of POPULAR_FOODS) {
    let score = 0;

    // Check aliases first (most important)
    for (const alias of food.aliases) {
      const aliasLower = alias.toLowerCase();
      if (aliasLower === q) {
        score = Math.max(score, 100 + food.popularity);
        break;
      }
      if (aliasLower.includes(q)) {
        score = Math.max(score, 80 + food.popularity);
      }
      if (q.includes(aliasLower)) {
        score = Math.max(score, 70 + food.popularity);
      }
    }

    // Word-level matching
    if (score === 0) {
      let wordMatches = 0;
      for (const word of words) {
        const nameMatch = food.name.toLowerCase().includes(word);
        const aliasMatch = food.aliases.some(a => a.toLowerCase().includes(word));
        if (nameMatch || aliasMatch) wordMatches++;
      }
      if (wordMatches > 0) {
        const pct = wordMatches / words.length;
        score = Math.round(pct * 50) + food.popularity;
      }
    }

    if (score > 0) {
      results.push({ ...food, score });
    }
  }

  return results.sort((a, b) => b.score - a.score);
}
