/**
 * Comprehensive NYC restaurant chain nutrition database.
 * Sources: FDA-mandated chain nutrition disclosures (chains with 20+ locations must publish).
 * All values per standard serving as listed on chain menus.
 */

export interface MenuItem {
  name: string;
  cal: number;
  protein: number;   // grams
  fat: number;       // grams
  carbs: number;     // grams
  sodium: number;    // mg
  fiber?: number;    // grams
  sugar?: number;    // grams
  tags?: string[];   // e.g. "high-protein", "low-cal", "keto", "vegan", "vegetarian"
}

export interface RestaurantChain {
  name: string;
  slug: string;
  emoji: string;
  category: string;          // "Fast Food", "Fast Casual", "Pizza", "Coffee & Bakery", "Asian", "Mexican", "Healthy", "Sandwich", "Chicken", "Burger", "Seafood", "Breakfast", "Diner"
  nycLocations: number;      // approximate NYC locations
  priceRange: 1 | 2 | 3;    // $ $$ $$$
  orderingTip?: string;      // healthy ordering hack
  items: MenuItem[];
}

export const RESTAURANT_CHAINS: RestaurantChain[] = [
  // ─── HEALTHY / FAST CASUAL ───────────────────────────────────
  {
    name: "Sweetgreen",
    slug: "sweetgreen",
    emoji: "🥗",
    category: "Healthy",
    nycLocations: 45,
    priceRange: 2,
    orderingTip: "Build a custom bowl: greens base + grilled protein + light dressing saves 200+ cal vs premade bowls",
    items: [
      { name: "Harvest Bowl", cal: 705, protein: 30, fat: 37, carbs: 64, sodium: 620, fiber: 8, sugar: 12, tags: [] },
      { name: "Kale Caesar", cal: 450, protein: 33, fat: 25, carbs: 26, sodium: 780, fiber: 4, sugar: 3, tags: ["high-protein"] },
      { name: "Guacamole Greens", cal: 555, protein: 15, fat: 36, carbs: 47, sodium: 510, fiber: 10, sugar: 6, tags: ["vegetarian"] },
      { name: "Shroomami", cal: 570, protein: 18, fat: 28, carbs: 65, sodium: 640, fiber: 9, sugar: 8, tags: ["vegan"] },
      { name: "Hot Honey Chicken", cal: 640, protein: 38, fat: 30, carbs: 55, sodium: 890, fiber: 5, sugar: 14, tags: ["high-protein"] },
      { name: "Buffalo Chicken Bowl", cal: 575, protein: 40, fat: 28, carbs: 42, sodium: 1050, fiber: 6, sugar: 5, tags: ["high-protein"] },
      { name: "Garden Cobb", cal: 490, protein: 35, fat: 30, carbs: 22, sodium: 680, fiber: 5, sugar: 4, tags: ["high-protein", "low-carb"] },
      { name: "Crispy Rice Bowl", cal: 680, protein: 22, fat: 32, carbs: 78, sodium: 720, fiber: 4, sugar: 10, tags: [] },
      { name: "Super Green Goddess", cal: 370, protein: 8, fat: 22, carbs: 38, sodium: 450, fiber: 7, sugar: 6, tags: ["low-cal", "vegan"] },
      { name: "Chicken Pesto Parm", cal: 720, protein: 42, fat: 35, carbs: 56, sodium: 980, fiber: 4, sugar: 6, tags: ["high-protein"] },
    ],
  },
  {
    name: "Just Salad",
    slug: "just-salad",
    emoji: "🥬",
    category: "Healthy",
    nycLocations: 40,
    priceRange: 2,
    orderingTip: "Bring your own reusable bowl for a discount. Dressing on the side cuts 100-200 cal.",
    items: [
      { name: "Thai Chicken Crunch", cal: 510, protein: 35, fat: 26, carbs: 38, sodium: 820, fiber: 5, sugar: 10, tags: ["high-protein"] },
      { name: "Crispy Chicken Poblano", cal: 590, protein: 38, fat: 30, carbs: 42, sodium: 940, fiber: 6, sugar: 8, tags: ["high-protein"] },
      { name: "Grilled Chicken Caesar", cal: 430, protein: 38, fat: 24, carbs: 18, sodium: 760, fiber: 3, sugar: 2, tags: ["high-protein", "low-carb"] },
      { name: "Harvest Crunch", cal: 480, protein: 12, fat: 28, carbs: 50, sodium: 580, fiber: 7, sugar: 14, tags: ["vegetarian"] },
      { name: "The Veg Head", cal: 350, protein: 10, fat: 18, carbs: 40, sodium: 520, fiber: 8, sugar: 8, tags: ["low-cal", "vegan"] },
      { name: "Spicy Mongolian Chicken", cal: 520, protein: 36, fat: 24, carbs: 42, sodium: 1100, fiber: 4, sugar: 12, tags: ["high-protein"] },
      { name: "Grilled Steak & Blue Cheese", cal: 560, protein: 40, fat: 32, carbs: 26, sodium: 830, fiber: 4, sugar: 6, tags: ["high-protein", "low-carb"] },
    ],
  },
  {
    name: "Chopt",
    slug: "chopt",
    emoji: "🥒",
    category: "Healthy",
    nycLocations: 30,
    priceRange: 2,
    orderingTip: "Go 'naked' (no wrap) and choose vinaigrette over creamy dressing to save 200+ cal",
    items: [
      { name: "Mexican Caesar", cal: 520, protein: 32, fat: 28, carbs: 38, sodium: 780, fiber: 6, sugar: 4, tags: ["high-protein"] },
      { name: "Kebab Cobb", cal: 550, protein: 38, fat: 30, carbs: 32, sodium: 920, fiber: 5, sugar: 6, tags: ["high-protein"] },
      { name: "Palm Beach", cal: 460, protein: 30, fat: 22, carbs: 38, sodium: 680, fiber: 4, sugar: 8, tags: ["high-protein"] },
      { name: "Grilled Chicken Ranch", cal: 590, protein: 42, fat: 32, carbs: 34, sodium: 1050, fiber: 3, sugar: 4, tags: ["high-protein"] },
      { name: "Santa Fe", cal: 480, protein: 28, fat: 24, carbs: 42, sodium: 720, fiber: 7, sugar: 5, tags: [] },
      { name: "Classic Cobb", cal: 530, protein: 36, fat: 34, carbs: 22, sodium: 860, fiber: 4, sugar: 4, tags: ["high-protein", "low-carb"] },
    ],
  },
  {
    name: "CAVA",
    slug: "cava",
    emoji: "🫒",
    category: "Healthy",
    nycLocations: 20,
    priceRange: 2,
    orderingTip: "Greens + grains base with grilled chicken and tzatziki = high protein under 600 cal",
    items: [
      { name: "Grilled Chicken Bowl (greens+grains)", cal: 580, protein: 42, fat: 22, carbs: 56, sodium: 820, fiber: 6, sugar: 4, tags: ["high-protein"] },
      { name: "Grilled Meatball Bowl", cal: 640, protein: 35, fat: 28, carbs: 62, sodium: 960, fiber: 5, sugar: 6, tags: ["high-protein"] },
      { name: "Falafel Bowl", cal: 620, protein: 18, fat: 30, carbs: 72, sodium: 780, fiber: 10, sugar: 5, tags: ["vegan"] },
      { name: "Harissa Chicken Pita", cal: 520, protein: 38, fat: 18, carbs: 52, sodium: 1100, fiber: 4, sugar: 3, tags: ["high-protein"] },
      { name: "Roasted Veggie Bowl", cal: 450, protein: 12, fat: 20, carbs: 58, sodium: 640, fiber: 9, sugar: 6, tags: ["low-cal", "vegan"] },
      { name: "Lamb Meatball Pita", cal: 610, protein: 32, fat: 28, carbs: 56, sodium: 1020, fiber: 4, sugar: 5, tags: [] },
    ],
  },
  {
    name: "Dig",
    slug: "dig",
    emoji: "🍠",
    category: "Healthy",
    nycLocations: 25,
    priceRange: 2,
    orderingTip: "Build a plate: pick a protein + 3 sides. The charred chicken + sweet potatoes + Brussels sprouts is under 550 cal.",
    items: [
      { name: "Charred Chicken Plate", cal: 520, protein: 45, fat: 18, carbs: 48, sodium: 680, fiber: 7, sugar: 8, tags: ["high-protein"] },
      { name: "Roasted Salmon Plate", cal: 580, protein: 38, fat: 28, carbs: 42, sodium: 620, fiber: 6, sugar: 6, tags: ["high-protein"] },
      { name: "Braised Beef Plate", cal: 640, protein: 42, fat: 26, carbs: 55, sodium: 780, fiber: 5, sugar: 7, tags: ["high-protein"] },
      { name: "Market Veggie Plate", cal: 380, protein: 14, fat: 16, carbs: 52, sodium: 520, fiber: 10, sugar: 8, tags: ["low-cal", "vegetarian"] },
      { name: "Grilled Chicken & Brown Rice", cal: 490, protein: 40, fat: 14, carbs: 52, sodium: 580, fiber: 4, sugar: 3, tags: ["high-protein"] },
    ],
  },
  {
    name: "Tender Greens",
    slug: "tender-greens",
    emoji: "🌿",
    category: "Healthy",
    nycLocations: 5,
    priceRange: 2,
    orderingTip: "Choose a salad plate over a bowl — same food, fewer carbs from grains",
    items: [
      { name: "Chipotle Barbecue Chicken", cal: 550, protein: 42, fat: 22, carbs: 48, sodium: 820, fiber: 5, sugar: 10, tags: ["high-protein"] },
      { name: "Grilled Salmon Plate", cal: 520, protein: 36, fat: 26, carbs: 38, sodium: 640, fiber: 4, sugar: 5, tags: ["high-protein"] },
      { name: "Backyard Steak Plate", cal: 610, protein: 44, fat: 30, carbs: 40, sodium: 780, fiber: 4, sugar: 4, tags: ["high-protein"] },
      { name: "Happy Vegan Bowl", cal: 420, protein: 14, fat: 18, carbs: 56, sodium: 540, fiber: 9, sugar: 6, tags: ["low-cal", "vegan"] },
    ],
  },
  {
    name: "honeygrow",
    slug: "honeygrow",
    emoji: "🍜",
    category: "Healthy",
    nycLocations: 8,
    priceRange: 2,
    orderingTip: "Choose wheat noodles over egg noodles for more fiber; go with sesame garlic sauce (lowest cal)",
    items: [
      { name: "Sesame Garlic Stir-Fry (chicken)", cal: 510, protein: 38, fat: 16, carbs: 58, sodium: 920, fiber: 4, sugar: 8, tags: ["high-protein"] },
      { name: "Red Coconut Curry (tofu)", cal: 480, protein: 18, fat: 22, carbs: 56, sodium: 780, fiber: 5, sugar: 10, tags: ["vegan"] },
      { name: "Spicy Garlic Shrimp Stir-Fry", cal: 460, protein: 32, fat: 14, carbs: 54, sodium: 1050, fiber: 3, sugar: 6, tags: ["high-protein"] },
      { name: "Honeybar (apple walnut)", cal: 280, protein: 6, fat: 14, carbs: 36, sodium: 120, fiber: 4, sugar: 22, tags: ["vegetarian"] },
    ],
  },
  {
    name: "Naya",
    slug: "naya",
    emoji: "🧆",
    category: "Healthy",
    nycLocations: 10,
    priceRange: 2,
    orderingTip: "Grilled chicken shawarma bowl with tahini on the side — high protein, under 550 cal",
    items: [
      { name: "Chicken Shawarma Bowl", cal: 540, protein: 40, fat: 20, carbs: 52, sodium: 780, fiber: 5, sugar: 4, tags: ["high-protein"] },
      { name: "Falafel Bowl", cal: 580, protein: 16, fat: 28, carbs: 68, sodium: 720, fiber: 10, sugar: 5, tags: ["vegan"] },
      { name: "Lamb Kofta Bowl", cal: 620, protein: 36, fat: 30, carbs: 52, sodium: 860, fiber: 4, sugar: 5, tags: ["high-protein"] },
      { name: "Grilled Veggie Pita", cal: 420, protein: 12, fat: 16, carbs: 58, sodium: 640, fiber: 7, sugar: 4, tags: ["low-cal", "vegan"] },
    ],
  },

  // ─── MEXICAN ─────────────────────────────────────────────────
  {
    name: "Chipotle",
    slug: "chipotle",
    emoji: "🌯",
    category: "Mexican",
    nycLocations: 90,
    priceRange: 2,
    orderingTip: "Bowl > burrito saves 300 cal (tortilla). Skip sour cream (-110) & cheese (-100). Double protein is only +$3.",
    items: [
      { name: "Chicken Burrito Bowl", cal: 510, protein: 40, fat: 18, carbs: 50, sodium: 1230, fiber: 8, sugar: 4, tags: ["high-protein"] },
      { name: "Chicken Burrito", cal: 815, protein: 44, fat: 28, carbs: 92, sodium: 1620, fiber: 10, sugar: 5, tags: [] },
      { name: "Steak Bowl", cal: 540, protein: 42, fat: 20, carbs: 50, sodium: 1180, fiber: 8, sugar: 4, tags: ["high-protein"] },
      { name: "Sofritas Bowl", cal: 470, protein: 18, fat: 22, carbs: 52, sodium: 1050, fiber: 9, sugar: 6, tags: ["vegan"] },
      { name: "Carnitas Bowl", cal: 570, protein: 38, fat: 24, carbs: 50, sodium: 1350, fiber: 8, sugar: 4, tags: ["high-protein"] },
      { name: "Chicken Salad (no dressing)", cal: 360, protein: 38, fat: 12, carbs: 22, sodium: 780, fiber: 7, sugar: 4, tags: ["high-protein", "low-cal", "low-carb"] },
      { name: "Veggie Bowl (no sour cream)", cal: 420, protein: 14, fat: 18, carbs: 52, sodium: 820, fiber: 10, sugar: 5, tags: ["vegetarian"] },
      { name: "Chips & Guac", cal: 770, protein: 10, fat: 42, carbs: 88, sodium: 620, fiber: 12, sugar: 2, tags: ["vegan"] },
      { name: "Side of Queso Blanco", cal: 240, protein: 12, fat: 16, carbs: 14, sodium: 780, fiber: 0, sugar: 2, tags: [] },
    ],
  },
  {
    name: "Dos Toros",
    slug: "dos-toros",
    emoji: "🌮",
    category: "Mexican",
    nycLocations: 20,
    priceRange: 2,
    orderingTip: "Bowl with half rice, extra lettuce, and green salsa = lighter without losing flavor",
    items: [
      { name: "Chicken Burrito Bowl", cal: 520, protein: 38, fat: 18, carbs: 54, sodium: 1120, fiber: 7, sugar: 4, tags: ["high-protein"] },
      { name: "Steak Burrito", cal: 780, protein: 42, fat: 26, carbs: 86, sodium: 1480, fiber: 8, sugar: 4, tags: [] },
      { name: "Chicken Tacos (3)", cal: 480, protein: 34, fat: 18, carbs: 46, sodium: 920, fiber: 5, sugar: 3, tags: ["high-protein"] },
      { name: "Veggie Bowl", cal: 440, protein: 14, fat: 16, carbs: 62, sodium: 780, fiber: 9, sugar: 5, tags: ["vegetarian"] },
      { name: "Chicken Quesadilla", cal: 680, protein: 40, fat: 32, carbs: 56, sodium: 1250, fiber: 3, sugar: 2, tags: ["high-protein"] },
    ],
  },
  {
    name: "Taco Bell",
    slug: "taco-bell",
    emoji: "🔔",
    category: "Mexican",
    nycLocations: 80,
    priceRange: 1,
    orderingTip: "Go 'fresco style' — replaces cheese & sauces with pico de gallo, saves 50-80 cal per item",
    items: [
      { name: "Crunchy Taco", cal: 170, protein: 8, fat: 10, carbs: 13, sodium: 310, fiber: 2, sugar: 1, tags: ["low-cal"] },
      { name: "Soft Taco (beef)", cal: 180, protein: 9, fat: 9, carbs: 18, sodium: 500, fiber: 2, sugar: 1, tags: ["low-cal"] },
      { name: "Chicken Burrito Supreme", cal: 400, protein: 20, fat: 14, carbs: 50, sodium: 1070, fiber: 5, sugar: 4, tags: [] },
      { name: "Power Menu Bowl (chicken)", cal: 470, protein: 26, fat: 18, carbs: 50, sodium: 1180, fiber: 6, sugar: 3, tags: [] },
      { name: "Bean Burrito", cal: 350, protein: 13, fat: 10, carbs: 54, sodium: 1060, fiber: 8, sugar: 3, tags: ["vegetarian"] },
      { name: "Veggie Crunchwrap Supreme", cal: 530, protein: 15, fat: 22, carbs: 67, sodium: 1070, fiber: 6, sugar: 5, tags: ["vegetarian"] },
      { name: "Nachos BellGrande", cal: 740, protein: 16, fat: 38, carbs: 82, sodium: 1050, fiber: 8, sugar: 4, tags: [] },
      { name: "Cheesy Gordita Crunch", cal: 500, protein: 20, fat: 28, carbs: 41, sodium: 820, fiber: 3, sugar: 4, tags: [] },
    ],
  },

  // ─── BURGER ──────────────────────────────────────────────────
  {
    name: "Shake Shack",
    slug: "shake-shack",
    emoji: "🍔",
    category: "Burger",
    nycLocations: 35,
    priceRange: 2,
    orderingTip: "ShackBurger single is 530 cal; skip cheese (-80) and get lettuce wrap (-100) for a 350 cal burger",
    items: [
      { name: "ShackBurger (single)", cal: 530, protein: 28, fat: 34, carbs: 26, sodium: 1290, fiber: 1, sugar: 7, tags: [] },
      { name: "SmokeShack (single)", cal: 610, protein: 30, fat: 40, carbs: 28, sodium: 1550, fiber: 1, sugar: 7, tags: [] },
      { name: "Shack-cago Dog", cal: 370, protein: 14, fat: 24, carbs: 28, sodium: 1100, fiber: 2, sugar: 6, tags: [] },
      { name: "Chicken Shack", cal: 580, protein: 32, fat: 28, carbs: 48, sodium: 1280, fiber: 2, sugar: 6, tags: [] },
      { name: "Grilled Chicken Sandwich", cal: 410, protein: 36, fat: 16, carbs: 30, sodium: 920, fiber: 2, sugar: 5, tags: ["high-protein"] },
      { name: "Fries (regular)", cal: 420, protein: 5, fat: 20, carbs: 56, sodium: 490, fiber: 4, sugar: 0, tags: ["vegan"] },
      { name: "Cheese Fries", cal: 580, protein: 12, fat: 34, carbs: 56, sodium: 1020, fiber: 4, sugar: 0, tags: [] },
      { name: "Chocolate Shake", cal: 750, protein: 16, fat: 42, carbs: 78, sodium: 380, fiber: 2, sugar: 68, tags: [] },
      { name: "'Shroom Burger", cal: 580, protein: 20, fat: 36, carbs: 44, sodium: 1040, fiber: 3, sugar: 8, tags: ["vegetarian"] },
    ],
  },
  {
    name: "Five Guys",
    slug: "five-guys",
    emoji: "🍟",
    category: "Burger",
    nycLocations: 20,
    priceRange: 2,
    orderingTip: "Little Burger (1 patty) saves 300 cal. Get a bowl instead of a bun for low carb.",
    items: [
      { name: "Hamburger", cal: 700, protein: 39, fat: 43, carbs: 39, sodium: 430, fiber: 2, sugar: 9, tags: [] },
      { name: "Little Hamburger", cal: 480, protein: 23, fat: 26, carbs: 39, sodium: 380, fiber: 2, sugar: 9, tags: [] },
      { name: "Cheeseburger", cal: 840, protein: 47, fat: 55, carbs: 40, sodium: 1050, fiber: 2, sugar: 9, tags: [] },
      { name: "Little Cheeseburger", cal: 550, protein: 27, fat: 32, carbs: 40, sodium: 690, fiber: 2, sugar: 9, tags: [] },
      { name: "BLT", cal: 430, protein: 20, fat: 24, carbs: 37, sodium: 650, fiber: 2, sugar: 8, tags: [] },
      { name: "Veggie Sandwich", cal: 440, protein: 16, fat: 15, carbs: 60, sodium: 1040, fiber: 5, sugar: 12, tags: ["vegetarian"] },
      { name: "Regular Fries", cal: 530, protein: 8, fat: 24, carbs: 72, sodium: 500, fiber: 6, sugar: 0, tags: ["vegan"] },
      { name: "Cajun Fries", cal: 540, protein: 8, fat: 24, carbs: 72, sodium: 740, fiber: 6, sugar: 0, tags: ["vegan"] },
      { name: "Hot Dog", cal: 520, protein: 18, fat: 35, carbs: 38, sodium: 1130, fiber: 2, sugar: 8, tags: [] },
    ],
  },
  {
    name: "Smashburger",
    slug: "smashburger",
    emoji: "💥",
    category: "Burger",
    nycLocations: 10,
    priceRange: 2,
    orderingTip: "Classic Smash single is 540 cal. Sub a turkey burger (-120 cal).",
    items: [
      { name: "Classic Smash (single)", cal: 540, protein: 28, fat: 32, carbs: 36, sodium: 880, fiber: 2, sugar: 7, tags: [] },
      { name: "BBQ Bacon Smash", cal: 780, protein: 42, fat: 46, carbs: 48, sodium: 1350, fiber: 2, sugar: 12, tags: [] },
      { name: "Grilled Chicken Sandwich", cal: 440, protein: 36, fat: 18, carbs: 34, sodium: 820, fiber: 2, sugar: 4, tags: ["high-protein"] },
      { name: "Turkey Burger", cal: 420, protein: 30, fat: 18, carbs: 36, sodium: 740, fiber: 2, sugar: 7, tags: ["high-protein"] },
      { name: "SmashFries", cal: 440, protein: 5, fat: 22, carbs: 56, sodium: 720, fiber: 4, sugar: 0, tags: [] },
    ],
  },

  // ─── FAST FOOD ───────────────────────────────────────────────
  {
    name: "McDonald's",
    slug: "mcdonalds",
    emoji: "🍟",
    category: "Fast Food",
    nycLocations: 250,
    priceRange: 1,
    orderingTip: "Egg McMuffin (300 cal, 17g protein) is one of the best fast-food breakfast options. Skip the hash brown (-150).",
    items: [
      { name: "Big Mac", cal: 550, protein: 25, fat: 30, carbs: 45, sodium: 1010, fiber: 3, sugar: 9, tags: [] },
      { name: "Quarter Pounder w/ Cheese", cal: 520, protein: 30, fat: 26, carbs: 42, sodium: 1140, fiber: 2, sugar: 10, tags: [] },
      { name: "McChicken", cal: 400, protein: 14, fat: 22, carbs: 40, sodium: 660, fiber: 1, sugar: 5, tags: [] },
      { name: "6pc McNuggets", cal: 250, protein: 14, fat: 15, carbs: 15, sodium: 500, fiber: 0, sugar: 0, tags: ["low-cal"] },
      { name: "10pc McNuggets", cal: 410, protein: 24, fat: 24, carbs: 25, sodium: 840, fiber: 0, sugar: 0, tags: [] },
      { name: "Egg McMuffin", cal: 300, protein: 17, fat: 12, carbs: 30, sodium: 770, fiber: 2, sugar: 3, tags: ["low-cal", "high-protein"] },
      { name: "Filet-O-Fish", cal: 390, protein: 16, fat: 19, carbs: 39, sodium: 580, fiber: 2, sugar: 5, tags: [] },
      { name: "McDouble", cal: 400, protein: 22, fat: 20, carbs: 33, sodium: 920, fiber: 2, sugar: 7, tags: [] },
      { name: "Medium Fries", cal: 320, protein: 4, fat: 15, carbs: 43, sodium: 260, fiber: 4, sugar: 0, tags: ["vegan"] },
      { name: "Side Salad", cal: 15, protein: 1, fat: 0, carbs: 3, sodium: 10, fiber: 1, sugar: 2, tags: ["low-cal", "vegan"] },
      { name: "Grilled Chicken Sandwich", cal: 420, protein: 32, fat: 16, carbs: 38, sodium: 980, fiber: 2, sugar: 7, tags: ["high-protein"] },
      { name: "Sausage McMuffin w/ Egg", cal: 480, protein: 21, fat: 30, carbs: 30, sodium: 870, fiber: 2, sugar: 2, tags: [] },
    ],
  },
  {
    name: "Burger King",
    slug: "burger-king",
    emoji: "👑",
    category: "Fast Food",
    nycLocations: 120,
    priceRange: 1,
    orderingTip: "Impossible Whopper is 630 cal — only 30 less than regular. Better bet: Grilled Chicken Jr. at 310 cal.",
    items: [
      { name: "Whopper", cal: 660, protein: 28, fat: 40, carbs: 49, sodium: 980, fiber: 2, sugar: 11, tags: [] },
      { name: "Whopper Jr.", cal: 310, protein: 13, fat: 18, carbs: 27, sodium: 390, fiber: 1, sugar: 7, tags: ["low-cal"] },
      { name: "Impossible Whopper", cal: 630, protein: 25, fat: 34, carbs: 58, sodium: 1080, fiber: 4, sugar: 12, tags: ["vegetarian"] },
      { name: "Original Chicken Sandwich", cal: 660, protein: 28, fat: 40, carbs: 48, sodium: 1170, fiber: 2, sugar: 5, tags: [] },
      { name: "Chicken Fries (9pc)", cal: 280, protein: 16, fat: 17, carbs: 16, sodium: 780, fiber: 1, sugar: 0, tags: [] },
      { name: "Bacon King", cal: 1150, protein: 61, fat: 79, carbs: 49, sodium: 2150, fiber: 2, sugar: 10, tags: [] },
      { name: "Onion Rings (medium)", cal: 320, protein: 4, fat: 16, carbs: 40, sodium: 460, fiber: 3, sugar: 5, tags: ["vegan"] },
      { name: "Side Garden Salad", cal: 60, protein: 4, fat: 3, carbs: 4, sodium: 80, fiber: 2, sugar: 2, tags: ["low-cal", "vegetarian"] },
    ],
  },
  {
    name: "Wendy's",
    slug: "wendys",
    emoji: "🟥",
    category: "Fast Food",
    nycLocations: 40,
    priceRange: 1,
    orderingTip: "Jr. Hamburger is only 250 cal. Pair with chili (160 cal, 14g protein) for a 410 cal meal with 30g protein.",
    items: [
      { name: "Dave's Single", cal: 570, protein: 30, fat: 34, carbs: 38, sodium: 1080, fiber: 2, sugar: 9, tags: [] },
      { name: "Jr. Hamburger", cal: 250, protein: 13, fat: 12, carbs: 25, sodium: 460, fiber: 1, sugar: 5, tags: ["low-cal"] },
      { name: "Jr. Bacon Cheeseburger", cal: 380, protein: 20, fat: 22, carbs: 26, sodium: 690, fiber: 1, sugar: 5, tags: [] },
      { name: "Grilled Chicken Sandwich", cal: 370, protein: 35, fat: 10, carbs: 36, sodium: 870, fiber: 2, sugar: 8, tags: ["high-protein"] },
      { name: "Spicy Chicken Sandwich", cal: 500, protein: 30, fat: 22, carbs: 48, sodium: 1290, fiber: 2, sugar: 4, tags: [] },
      { name: "Chili (small)", cal: 160, protein: 14, fat: 5, carbs: 16, sodium: 780, fiber: 4, sugar: 5, tags: ["low-cal", "high-protein"] },
      { name: "Baked Potato (plain)", cal: 270, protein: 7, fat: 0, carbs: 61, sodium: 25, fiber: 7, sugar: 4, tags: ["low-cal", "vegan"] },
      { name: "Apple Pecan Salad (half)", cal: 340, protein: 22, fat: 14, carbs: 32, sodium: 640, fiber: 3, sugar: 16, tags: [] },
      { name: "Frosty (small chocolate)", cal: 340, protein: 9, fat: 9, carbs: 56, sodium: 220, fiber: 1, sugar: 44, tags: ["vegetarian"] },
    ],
  },

  // ─── CHICKEN ─────────────────────────────────────────────────
  {
    name: "Chick-fil-A",
    slug: "chick-fil-a",
    emoji: "🐔",
    category: "Chicken",
    nycLocations: 40,
    priceRange: 1,
    orderingTip: "Grilled Nuggets (8ct) = 130 cal, 25g protein — one of the best macro ratios in fast food",
    items: [
      { name: "Original Chicken Sandwich", cal: 440, protein: 28, fat: 18, carbs: 40, sodium: 1400, fiber: 1, sugar: 5, tags: [] },
      { name: "Grilled Chicken Sandwich", cal: 320, protein: 28, fat: 6, carbs: 36, sodium: 680, fiber: 3, sugar: 7, tags: ["low-cal", "high-protein"] },
      { name: "Spicy Chicken Sandwich", cal: 450, protein: 28, fat: 20, carbs: 42, sodium: 1620, fiber: 2, sugar: 4, tags: [] },
      { name: "Grilled Nuggets (8ct)", cal: 130, protein: 25, fat: 3, carbs: 1, sodium: 440, fiber: 0, sugar: 1, tags: ["low-cal", "high-protein", "low-carb", "keto"] },
      { name: "Chicken Nuggets (8ct)", cal: 250, protein: 27, fat: 12, carbs: 11, sodium: 1040, fiber: 0, sugar: 1, tags: ["low-cal", "high-protein"] },
      { name: "Cobb Salad", cal: 510, protein: 40, fat: 27, carbs: 26, sodium: 1420, fiber: 4, sugar: 6, tags: ["high-protein", "low-carb"] },
      { name: "Market Salad", cal: 330, protein: 28, fat: 14, carbs: 24, sodium: 580, fiber: 4, sugar: 16, tags: ["low-cal", "high-protein"] },
      { name: "Waffle Fries (medium)", cal: 420, protein: 5, fat: 24, carbs: 45, sodium: 240, fiber: 5, sugar: 1, tags: ["vegan"] },
      { name: "Chicken Biscuit", cal: 450, protein: 18, fat: 22, carbs: 46, sodium: 1210, fiber: 1, sugar: 5, tags: [] },
      { name: "Egg White Grill", cal: 290, protein: 25, fat: 7, carbs: 31, sodium: 970, fiber: 3, sugar: 1, tags: ["low-cal", "high-protein"] },
    ],
  },
  {
    name: "Popeyes",
    slug: "popeyes",
    emoji: "🍗",
    category: "Chicken",
    nycLocations: 120,
    priceRange: 1,
    orderingTip: "Blackened chicken tenders (3pc, 170 cal, 26g protein) are the hidden gem — not breaded/fried",
    items: [
      { name: "Classic Chicken Sandwich", cal: 700, protein: 28, fat: 42, carbs: 50, sodium: 1440, fiber: 2, sugar: 8, tags: [] },
      { name: "Spicy Chicken Sandwich", cal: 700, protein: 28, fat: 42, carbs: 50, sodium: 1700, fiber: 3, sugar: 7, tags: [] },
      { name: "Blackened Chicken Tenders (3pc)", cal: 170, protein: 26, fat: 3, carbs: 4, sodium: 780, fiber: 0, sugar: 0, tags: ["low-cal", "high-protein", "low-carb", "keto"] },
      { name: "Mild Chicken Leg", cal: 160, protein: 14, fat: 9, carbs: 5, sodium: 460, fiber: 0, sugar: 0, tags: ["low-cal"] },
      { name: "Mild Chicken Breast", cal: 340, protein: 28, fat: 20, carbs: 14, sodium: 860, fiber: 0, sugar: 0, tags: [] },
      { name: "Red Beans & Rice (regular)", cal: 230, protein: 7, fat: 7, carbs: 36, sodium: 680, fiber: 5, sugar: 1, tags: [] },
      { name: "Cajun Fries (regular)", cal: 260, protein: 3, fat: 14, carbs: 32, sodium: 620, fiber: 3, sugar: 0, tags: ["vegan"] },
      { name: "Coleslaw (regular)", cal: 170, protein: 1, fat: 11, carbs: 17, sodium: 260, fiber: 2, sugar: 12, tags: ["vegetarian"] },
    ],
  },
  {
    name: "Wingstop",
    slug: "wingstop",
    emoji: "🍗",
    category: "Chicken",
    nycLocations: 50,
    priceRange: 1,
    orderingTip: "Plain wings (no sauce) are 0 carbs. Atomic or Lemon Pepper are lower-cal sauce options.",
    items: [
      { name: "Classic Wings (6pc, plain)", cal: 330, protein: 30, fat: 22, carbs: 0, sodium: 540, fiber: 0, sugar: 0, tags: ["high-protein", "low-carb", "keto"] },
      { name: "Boneless Wings (6pc, plain)", cal: 360, protein: 20, fat: 18, carbs: 28, sodium: 880, fiber: 1, sugar: 0, tags: [] },
      { name: "Lemon Pepper Wings (6pc)", cal: 390, protein: 30, fat: 28, carbs: 2, sodium: 1080, fiber: 0, sugar: 0, tags: ["high-protein", "low-carb"] },
      { name: "Cajun Fried Corn", cal: 240, protein: 6, fat: 14, carbs: 28, sodium: 440, fiber: 3, sugar: 6, tags: ["vegetarian"] },
      { name: "Ranch Dip", cal: 200, protein: 1, fat: 22, carbs: 2, sodium: 280, fiber: 0, sugar: 1, tags: ["keto", "vegetarian"] },
    ],
  },
  {
    name: "Raising Cane's",
    slug: "raising-canes",
    emoji: "🐓",
    category: "Chicken",
    nycLocations: 8,
    priceRange: 1,
    orderingTip: "Sub coleslaw for extra toast to save 150 cal. The chicken tenders are the lowest-cal fried option.",
    items: [
      { name: "Box Combo (4 tenders)", cal: 1250, protein: 52, fat: 58, carbs: 128, sodium: 2280, fiber: 3, sugar: 8, tags: [] },
      { name: "3 Chicken Tenders", cal: 400, protein: 28, fat: 20, carbs: 24, sodium: 1010, fiber: 0, sugar: 0, tags: [] },
      { name: "Chicken Sandwich", cal: 550, protein: 28, fat: 22, carbs: 58, sodium: 1250, fiber: 1, sugar: 6, tags: [] },
      { name: "Crinkle-Cut Fries (regular)", cal: 310, protein: 4, fat: 14, carbs: 42, sodium: 110, fiber: 3, sugar: 0, tags: ["vegan"] },
      { name: "Coleslaw", cal: 200, protein: 1, fat: 14, carbs: 18, sodium: 240, fiber: 2, sugar: 14, tags: ["vegetarian"] },
      { name: "Cane's Sauce", cal: 190, protein: 0, fat: 18, carbs: 8, sodium: 280, fiber: 0, sugar: 5, tags: [] },
    ],
  },

  // ─── SANDWICH / SUB ──────────────────────────────────────────
  {
    name: "Subway",
    slug: "subway",
    emoji: "🥪",
    category: "Sandwich",
    nycLocations: 400,
    priceRange: 1,
    orderingTip: "6-inch on wheat with double veggies and mustard instead of mayo saves 200+ cal. Turkey breast is the lowest-cal protein.",
    items: [
      { name: "Turkey Breast 6\"", cal: 270, protein: 18, fat: 4, carbs: 44, sodium: 810, fiber: 5, sugar: 6, tags: ["low-cal", "high-protein"] },
      { name: "Oven-Roasted Chicken 6\"", cal: 320, protein: 23, fat: 6, carbs: 44, sodium: 700, fiber: 5, sugar: 6, tags: ["low-cal", "high-protein"] },
      { name: "Veggie Delite 6\"", cal: 200, protein: 8, fat: 2, carbs: 38, sodium: 310, fiber: 5, sugar: 5, tags: ["low-cal", "vegan"] },
      { name: "Italian BMT 6\"", cal: 370, protein: 17, fat: 15, carbs: 44, sodium: 1260, fiber: 5, sugar: 6, tags: [] },
      { name: "Tuna 6\"", cal: 370, protein: 20, fat: 14, carbs: 42, sodium: 550, fiber: 5, sugar: 5, tags: [] },
      { name: "Steak & Cheese 6\"", cal: 350, protein: 24, fat: 10, carbs: 44, sodium: 890, fiber: 5, sugar: 7, tags: [] },
      { name: "Meatball Marinara 6\"", cal: 480, protein: 22, fat: 20, carbs: 54, sodium: 1220, fiber: 6, sugar: 10, tags: [] },
      { name: "Chicken & Bacon Ranch 6\"", cal: 530, protein: 30, fat: 22, carbs: 48, sodium: 1100, fiber: 5, sugar: 6, tags: [] },
      { name: "Rotisserie Chicken 6\"", cal: 320, protein: 26, fat: 8, carbs: 42, sodium: 770, fiber: 5, sugar: 5, tags: ["high-protein"] },
    ],
  },
  {
    name: "Jersey Mike's",
    slug: "jersey-mikes",
    emoji: "🥖",
    category: "Sandwich",
    nycLocations: 30,
    priceRange: 2,
    orderingTip: "Order a 'Sub in a Tub' (no bread) to cut 200-300 cal. Ask for 'Mike's Way' (onions, lettuce, tomato, oil, vinegar).",
    items: [
      { name: "#7 Turkey & Provolone (regular)", cal: 540, protein: 32, fat: 22, carbs: 54, sodium: 1580, fiber: 3, sugar: 5, tags: [] },
      { name: "#13 Italian (regular)", cal: 680, protein: 34, fat: 36, carbs: 56, sodium: 2220, fiber: 3, sugar: 6, tags: [] },
      { name: "#6 Roast Beef & Provolone", cal: 570, protein: 36, fat: 24, carbs: 52, sodium: 1640, fiber: 3, sugar: 5, tags: ["high-protein"] },
      { name: "#17 Mike's Famous Philly", cal: 620, protein: 38, fat: 28, carbs: 52, sodium: 1740, fiber: 3, sugar: 6, tags: ["high-protein"] },
      { name: "Turkey Sub in a Tub", cal: 320, protein: 28, fat: 18, carbs: 12, sodium: 1180, fiber: 2, sugar: 4, tags: ["low-cal", "high-protein", "low-carb"] },
      { name: "Grilled Chicken Caesar Wrap", cal: 510, protein: 34, fat: 22, carbs: 44, sodium: 1420, fiber: 3, sugar: 3, tags: ["high-protein"] },
    ],
  },
  {
    name: "Pret A Manger",
    slug: "pret-a-manger",
    emoji: "⭐",
    category: "Sandwich",
    nycLocations: 55,
    priceRange: 2,
    orderingTip: "Protein Pots and salads are under 400 cal with 25g+ protein — skip the pastry case",
    items: [
      { name: "Chicken & Avocado Sandwich", cal: 510, protein: 30, fat: 22, carbs: 48, sodium: 780, fiber: 5, sugar: 4, tags: ["high-protein"] },
      { name: "Tuna Niçoise Salad", cal: 350, protein: 28, fat: 18, carbs: 18, sodium: 640, fiber: 4, sugar: 6, tags: ["high-protein", "low-carb"] },
      { name: "Chicken Caesar Wrap", cal: 480, protein: 32, fat: 20, carbs: 44, sodium: 920, fiber: 3, sugar: 3, tags: ["high-protein"] },
      { name: "Egg & Cheddar Protein Box", cal: 370, protein: 26, fat: 22, carbs: 18, sodium: 580, fiber: 3, sugar: 4, tags: ["high-protein", "low-carb"] },
      { name: "PB&J Smoothie", cal: 280, protein: 12, fat: 8, carbs: 42, sodium: 120, fiber: 4, sugar: 28, tags: ["vegetarian"] },
      { name: "Almond Croissant", cal: 460, protein: 10, fat: 26, carbs: 48, sodium: 280, fiber: 2, sugar: 20, tags: ["vegetarian"] },
    ],
  },

  // ─── PIZZA ───────────────────────────────────────────────────
  {
    name: "Domino's",
    slug: "dominos",
    emoji: "🍕",
    category: "Pizza",
    nycLocations: 180,
    priceRange: 1,
    orderingTip: "Thin crust saves ~80 cal/slice vs hand-tossed. Load veggies instead of extra cheese.",
    items: [
      { name: "Hand-Tossed Cheese Slice (medium)", cal: 200, protein: 8, fat: 8, carbs: 25, sodium: 460, fiber: 1, sugar: 2, tags: [] },
      { name: "Pepperoni Slice (medium)", cal: 220, protein: 9, fat: 10, carbs: 25, sodium: 530, fiber: 1, sugar: 2, tags: [] },
      { name: "Thin Crust Cheese Slice", cal: 150, protein: 6, fat: 8, carbs: 14, sodium: 320, fiber: 1, sugar: 1, tags: ["low-cal"] },
      { name: "Pacific Veggie Slice", cal: 230, protein: 9, fat: 10, carbs: 27, sodium: 520, fiber: 2, sugar: 3, tags: ["vegetarian"] },
      { name: "Chicken Alfredo Pasta Bowl", cal: 690, protein: 28, fat: 26, carbs: 84, sodium: 990, fiber: 3, sugar: 5, tags: [] },
      { name: "Classic Garden Salad", cal: 70, protein: 4, fat: 1, carbs: 14, sodium: 170, fiber: 3, sugar: 5, tags: ["low-cal", "vegetarian"] },
      { name: "Boneless Chicken (8pc)", cal: 350, protein: 20, fat: 16, carbs: 30, sodium: 1120, fiber: 1, sugar: 1, tags: [] },
    ],
  },
  {
    name: "Pizza Hut",
    slug: "pizza-hut",
    emoji: "🍕",
    category: "Pizza",
    nycLocations: 60,
    priceRange: 1,
    orderingTip: "Thin 'N Crispy crust is the lowest-cal option. Hand-tossed adds 40+ cal/slice.",
    items: [
      { name: "Hand-Tossed Cheese Slice (medium)", cal: 220, protein: 10, fat: 8, carbs: 26, sodium: 540, fiber: 1, sugar: 3, tags: [] },
      { name: "Pepperoni Lovers Slice", cal: 280, protein: 12, fat: 14, carbs: 26, sodium: 700, fiber: 1, sugar: 3, tags: [] },
      { name: "Thin 'N Crispy Cheese Slice", cal: 180, protein: 8, fat: 8, carbs: 18, sodium: 460, fiber: 1, sugar: 2, tags: ["low-cal"] },
      { name: "Veggie Lovers Slice", cal: 200, protein: 8, fat: 8, carbs: 24, sodium: 480, fiber: 2, sugar: 3, tags: ["vegetarian"] },
      { name: "Tuscani Meaty Marinara Pasta", cal: 520, protein: 22, fat: 24, carbs: 52, sodium: 1080, fiber: 3, sugar: 6, tags: [] },
      { name: "Wing Street Wings (2pc)", cal: 150, protein: 10, fat: 10, carbs: 4, sodium: 380, fiber: 0, sugar: 1, tags: ["low-cal", "low-carb"] },
    ],
  },
  {
    name: "Papa John's",
    slug: "papa-johns",
    emoji: "🍕",
    category: "Pizza",
    nycLocations: 50,
    priceRange: 1,
    orderingTip: "Skip the garlic dipping sauce — it's 150 cal of pure fat. Garden Fresh pizza is lowest-cal.",
    items: [
      { name: "Original Cheese Slice (large)", cal: 290, protein: 12, fat: 10, carbs: 38, sodium: 640, fiber: 1, sugar: 4, tags: [] },
      { name: "Pepperoni Slice (large)", cal: 320, protein: 14, fat: 14, carbs: 36, sodium: 780, fiber: 1, sugar: 4, tags: [] },
      { name: "Garden Fresh Slice", cal: 260, protein: 10, fat: 10, carbs: 34, sodium: 580, fiber: 2, sugar: 4, tags: ["vegetarian"] },
      { name: "Chicken & Bacon Slice", cal: 350, protein: 18, fat: 16, carbs: 34, sodium: 860, fiber: 1, sugar: 4, tags: [] },
      { name: "Papadias (Philly Cheesesteak)", cal: 620, protein: 30, fat: 26, carbs: 64, sodium: 1480, fiber: 2, sugar: 5, tags: [] },
      { name: "Garlic Sauce (dip cup)", cal: 150, protein: 0, fat: 17, carbs: 0, sodium: 160, fiber: 0, sugar: 0, tags: ["keto"] },
    ],
  },
  {
    name: "Joe's Pizza",
    slug: "joes-pizza",
    emoji: "🗽",
    category: "Pizza",
    nycLocations: 5,
    priceRange: 1,
    orderingTip: "A classic NYC slice is ~300 cal. Blot the grease with a napkin — saves ~40 cal.",
    items: [
      { name: "Classic Cheese Slice", cal: 300, protein: 12, fat: 10, carbs: 40, sodium: 580, fiber: 2, sugar: 3, tags: [] },
      { name: "Pepperoni Slice", cal: 340, protein: 14, fat: 14, carbs: 38, sodium: 720, fiber: 2, sugar: 3, tags: [] },
      { name: "Fresh Mozzarella Slice", cal: 350, protein: 16, fat: 14, carbs: 38, sodium: 540, fiber: 2, sugar: 3, tags: ["vegetarian"] },
      { name: "Sicilian Slice", cal: 460, protein: 16, fat: 18, carbs: 56, sodium: 780, fiber: 3, sugar: 4, tags: [] },
    ],
  },
  {
    name: "2 Bros Pizza",
    slug: "2-bros-pizza",
    emoji: "🍕",
    category: "Pizza",
    nycLocations: 30,
    priceRange: 1,
    orderingTip: "At $1/slice, it's the cheapest cal/$ in NYC. One slice + a side salad is a solid budget meal.",
    items: [
      { name: "Cheese Slice", cal: 310, protein: 12, fat: 10, carbs: 42, sodium: 600, fiber: 2, sugar: 3, tags: [] },
      { name: "Pepperoni Slice", cal: 350, protein: 14, fat: 14, carbs: 40, sodium: 740, fiber: 2, sugar: 3, tags: [] },
      { name: "Sicilian Slice", cal: 470, protein: 16, fat: 18, carbs: 58, sodium: 800, fiber: 3, sugar: 4, tags: [] },
    ],
  },

  // ─── COFFEE & BAKERY ────────────────────────────────────────
  {
    name: "Starbucks",
    slug: "starbucks",
    emoji: "☕",
    category: "Coffee & Bakery",
    nycLocations: 350,
    priceRange: 2,
    orderingTip: "Grande Caffè Americano = 15 cal. Any Grande Frappuccino = 400+. Swap to cold brew with splash of oat milk for big savings.",
    items: [
      { name: "Caffè Americano (grande)", cal: 15, protein: 1, fat: 0, carbs: 3, sodium: 10, fiber: 0, sugar: 0, tags: ["low-cal", "vegan"] },
      { name: "Cold Brew (grande, black)", cal: 5, protein: 0, fat: 0, carbs: 0, sodium: 15, fiber: 0, sugar: 0, tags: ["low-cal", "vegan"] },
      { name: "Caffè Latte (grande, 2% milk)", cal: 190, protein: 13, fat: 7, carbs: 19, sodium: 170, fiber: 0, sugar: 17, tags: ["vegetarian"] },
      { name: "Oatmilk Latte (grande)", cal: 170, protein: 4, fat: 5, carbs: 28, sodium: 170, fiber: 2, sugar: 14, tags: ["vegan"] },
      { name: "Caramel Frappuccino (grande)", cal: 380, protein: 5, fat: 16, carbs: 54, sodium: 230, fiber: 0, sugar: 50, tags: [] },
      { name: "Mocha Frappuccino (grande)", cal: 370, protein: 6, fat: 15, carbs: 54, sodium: 220, fiber: 1, sugar: 48, tags: [] },
      { name: "Protein Cold Brew (grande)", cal: 170, protein: 12, fat: 3, carbs: 23, sodium: 130, fiber: 0, sugar: 18, tags: ["high-protein"] },
      { name: "Egg & Cheddar Protein Box", cal: 460, protein: 25, fat: 24, carbs: 38, sodium: 780, fiber: 3, sugar: 12, tags: ["high-protein"] },
      { name: "Turkey Bacon Sandwich", cal: 230, protein: 14, fat: 6, carbs: 28, sodium: 560, fiber: 3, sugar: 3, tags: ["low-cal", "high-protein"] },
      { name: "Spinach & Feta Wrap", cal: 290, protein: 19, fat: 10, carbs: 34, sodium: 840, fiber: 3, sugar: 4, tags: ["high-protein", "vegetarian"] },
      { name: "Butter Croissant", cal: 260, protein: 5, fat: 14, carbs: 30, sodium: 320, fiber: 1, sugar: 4, tags: ["vegetarian"] },
      { name: "Chocolate Cake Pop", cal: 160, protein: 2, fat: 8, carbs: 22, sodium: 100, fiber: 0, sugar: 16, tags: [] },
    ],
  },
  {
    name: "Dunkin'",
    slug: "dunkin",
    emoji: "🍩",
    category: "Coffee & Bakery",
    nycLocations: 600,
    priceRange: 1,
    orderingTip: "Egg & Cheese on English Muffin = 340 cal. Avoid croissants (+120 cal vs muffin). Black coffee = 5 cal.",
    items: [
      { name: "Original Blend Coffee (medium, black)", cal: 5, protein: 0, fat: 0, carbs: 1, sodium: 10, fiber: 0, sugar: 0, tags: ["low-cal", "vegan"] },
      { name: "Iced Coffee (medium, black)", cal: 5, protein: 0, fat: 0, carbs: 0, sodium: 10, fiber: 0, sugar: 0, tags: ["low-cal", "vegan"] },
      { name: "Caramel Swirl Latte (medium)", cal: 340, protein: 8, fat: 8, carbs: 58, sodium: 220, fiber: 0, sugar: 52, tags: [] },
      { name: "Egg & Cheese on English Muffin", cal: 340, protein: 14, fat: 16, carbs: 34, sodium: 680, fiber: 2, sugar: 3, tags: [] },
      { name: "Turkey Sausage Egg & Cheese", cal: 390, protein: 22, fat: 18, carbs: 34, sodium: 920, fiber: 2, sugar: 3, tags: [] },
      { name: "Glazed Donut", cal: 260, protein: 3, fat: 14, carbs: 31, sodium: 330, fiber: 1, sugar: 12, tags: ["vegetarian"] },
      { name: "Chocolate Frosted Donut", cal: 290, protein: 3, fat: 16, carbs: 34, sodium: 340, fiber: 1, sugar: 18, tags: ["vegetarian"] },
      { name: "Wake-Up Wrap (egg & cheese)", cal: 190, protein: 8, fat: 10, carbs: 14, sodium: 410, fiber: 0, sugar: 1, tags: ["low-cal"] },
      { name: "Hash Browns (6pc)", cal: 320, protein: 3, fat: 20, carbs: 34, sodium: 660, fiber: 3, sugar: 0, tags: ["vegan"] },
      { name: "Avocado Toast", cal: 240, protein: 5, fat: 10, carbs: 32, sodium: 450, fiber: 5, sugar: 3, tags: ["vegan"] },
    ],
  },
  {
    name: "Panera",
    slug: "panera",
    emoji: "🥐",
    category: "Coffee & Bakery",
    nycLocations: 55,
    priceRange: 2,
    orderingTip: "Half sandwich + cup of soup is a balanced 400-500 cal meal. Avoid mac & cheese (980 cal full).",
    items: [
      { name: "Broccoli Cheddar Soup (cup)", cal: 230, protein: 10, fat: 14, carbs: 16, sodium: 910, fiber: 2, sugar: 4, tags: ["vegetarian"] },
      { name: "Turkey Sandwich (half)", cal: 340, protein: 20, fat: 14, carbs: 36, sodium: 780, fiber: 2, sugar: 4, tags: [] },
      { name: "Fuji Apple Chicken Salad (half)", cal: 280, protein: 16, fat: 12, carbs: 28, sodium: 380, fiber: 3, sugar: 14, tags: [] },
      { name: "Green Goddess Cobb Salad", cal: 530, protein: 35, fat: 34, carbs: 22, sodium: 1160, fiber: 5, sugar: 6, tags: ["high-protein", "low-carb"] },
      { name: "Mac & Cheese (full)", cal: 980, protein: 36, fat: 50, carbs: 92, sodium: 1620, fiber: 4, sugar: 8, tags: [] },
      { name: "Mediterranean Bowl", cal: 480, protein: 28, fat: 18, carbs: 52, sodium: 840, fiber: 6, sugar: 4, tags: ["high-protein"] },
      { name: "Chicken Tortilla Soup (cup)", cal: 180, protein: 14, fat: 6, carbs: 18, sodium: 820, fiber: 2, sugar: 4, tags: ["low-cal"] },
      { name: "Everything Bagel", cal: 290, protein: 11, fat: 3, carbs: 56, sodium: 510, fiber: 2, sugar: 5, tags: ["vegan"] },
    ],
  },
  {
    name: "Gregory's Coffee",
    slug: "gregorys-coffee",
    emoji: "☕",
    category: "Coffee & Bakery",
    nycLocations: 35,
    priceRange: 2,
    orderingTip: "NYC-local chain. Black coffee and cold brew are near-zero cal. Oat milk adds ~60 cal.",
    items: [
      { name: "Cold Brew (medium, black)", cal: 5, protein: 0, fat: 0, carbs: 0, sodium: 10, fiber: 0, sugar: 0, tags: ["low-cal", "vegan"] },
      { name: "Oat Milk Latte (medium)", cal: 180, protein: 4, fat: 5, carbs: 30, sodium: 160, fiber: 2, sugar: 14, tags: ["vegan"] },
      { name: "Matcha Latte (medium)", cal: 200, protein: 8, fat: 6, carbs: 30, sodium: 140, fiber: 1, sugar: 22, tags: ["vegetarian"] },
      { name: "Avocado Toast", cal: 250, protein: 6, fat: 12, carbs: 30, sodium: 380, fiber: 5, sugar: 2, tags: ["vegan"] },
      { name: "Egg & Cheese Croissant", cal: 420, protein: 16, fat: 24, carbs: 34, sodium: 620, fiber: 1, sugar: 4, tags: ["vegetarian"] },
    ],
  },

  // ─── ASIAN ───────────────────────────────────────────────────
  {
    name: "Panda Express",
    slug: "panda-express",
    emoji: "🐼",
    category: "Asian",
    nycLocations: 30,
    priceRange: 1,
    orderingTip: "Super Greens side is 90 cal. Grilled Teriyaki Chicken is lowest-cal entrée at 300 cal. Skip fried rice (+520).",
    items: [
      { name: "Orange Chicken", cal: 490, protein: 25, fat: 23, carbs: 51, sodium: 820, fiber: 0, sugar: 19, tags: [] },
      { name: "Grilled Teriyaki Chicken", cal: 300, protein: 36, fat: 13, carbs: 8, sodium: 530, fiber: 0, sugar: 5, tags: ["high-protein", "low-carb", "low-cal"] },
      { name: "Beijing Beef", cal: 470, protein: 14, fat: 26, carbs: 46, sodium: 660, fiber: 2, sugar: 20, tags: [] },
      { name: "Kung Pao Chicken", cal: 290, protein: 16, fat: 19, carbs: 14, sodium: 780, fiber: 2, sugar: 7, tags: ["low-cal"] },
      { name: "Broccoli Beef", cal: 150, protein: 9, fat: 7, carbs: 13, sodium: 520, fiber: 2, sugar: 5, tags: ["low-cal"] },
      { name: "Fried Rice", cal: 520, protein: 11, fat: 16, carbs: 85, sodium: 850, fiber: 1, sugar: 3, tags: [] },
      { name: "Chow Mein", cal: 510, protein: 13, fat: 22, carbs: 65, sodium: 860, fiber: 4, sugar: 8, tags: [] },
      { name: "Super Greens", cal: 90, protein: 6, fat: 3, carbs: 10, sodium: 260, fiber: 4, sugar: 3, tags: ["low-cal", "vegan"] },
      { name: "White Steamed Rice", cal: 380, protein: 7, fat: 0, carbs: 87, sodium: 0, fiber: 0, sugar: 0, tags: ["vegan"] },
      { name: "String Bean Chicken Breast", cal: 190, protein: 14, fat: 9, carbs: 13, sodium: 660, fiber: 2, sugar: 4, tags: ["low-cal"] },
    ],
  },
  {
    name: "Bon Chon",
    slug: "bon-chon",
    emoji: "🍗",
    category: "Asian",
    nycLocations: 15,
    priceRange: 2,
    orderingTip: "Wings are double-fried but smaller portions. Soy garlic sauce is lower-sugar than spicy.",
    items: [
      { name: "Soy Garlic Wings (8pc)", cal: 580, protein: 36, fat: 32, carbs: 36, sodium: 1240, fiber: 0, sugar: 12, tags: [] },
      { name: "Spicy Wings (8pc)", cal: 600, protein: 36, fat: 34, carbs: 38, sodium: 1380, fiber: 0, sugar: 14, tags: [] },
      { name: "Chicken Teriyaki Bowl", cal: 520, protein: 28, fat: 14, carbs: 68, sodium: 920, fiber: 2, sugar: 16, tags: [] },
      { name: "Japchae (glass noodles)", cal: 380, protein: 8, fat: 12, carbs: 62, sodium: 680, fiber: 3, sugar: 10, tags: ["vegetarian"] },
      { name: "Kimchi Fried Rice", cal: 480, protein: 12, fat: 16, carbs: 72, sodium: 1020, fiber: 2, sugar: 4, tags: [] },
    ],
  },
  {
    name: "Wok to Walk",
    slug: "wok-to-walk",
    emoji: "🥡",
    category: "Asian",
    nycLocations: 6,
    priceRange: 1,
    orderingTip: "Build your own: egg noodles + chicken + veggies + teriyaki = ~450 cal. Skip the fried toppings.",
    items: [
      { name: "Egg Noodles + Chicken + Teriyaki", cal: 450, protein: 28, fat: 12, carbs: 58, sodium: 880, fiber: 3, sugar: 8, tags: [] },
      { name: "Rice + Shrimp + Thai Basil", cal: 420, protein: 24, fat: 10, carbs: 62, sodium: 780, fiber: 2, sugar: 4, tags: [] },
      { name: "Glass Noodles + Tofu + Veggie", cal: 380, protein: 14, fat: 8, carbs: 64, sodium: 640, fiber: 4, sugar: 6, tags: ["vegan"] },
      { name: "Udon + Beef + Black Bean", cal: 520, protein: 30, fat: 16, carbs: 64, sodium: 1020, fiber: 3, sugar: 6, tags: [] },
    ],
  },

  // ─── SEAFOOD ─────────────────────────────────────────────────
  {
    name: "Luke's Lobster",
    slug: "lukes-lobster",
    emoji: "🦞",
    category: "Seafood",
    nycLocations: 8,
    priceRange: 3,
    orderingTip: "Lobster roll is surprisingly lean — 320 cal, 21g protein. One of the best protein-per-cal ratios in NYC.",
    items: [
      { name: "Lobster Roll", cal: 320, protein: 21, fat: 11, carbs: 33, sodium: 820, fiber: 1, sugar: 4, tags: ["high-protein"] },
      { name: "Crab Roll", cal: 290, protein: 18, fat: 10, carbs: 32, sodium: 780, fiber: 1, sugar: 4, tags: ["high-protein", "low-cal"] },
      { name: "Shrimp Roll", cal: 280, protein: 16, fat: 9, carbs: 33, sodium: 740, fiber: 1, sugar: 4, tags: ["low-cal"] },
      { name: "Lobster Bisque (cup)", cal: 220, protein: 10, fat: 14, carbs: 14, sodium: 680, fiber: 0, sugar: 2, tags: [] },
      { name: "New England Clam Chowder (cup)", cal: 240, protein: 8, fat: 16, carbs: 16, sodium: 720, fiber: 1, sugar: 2, tags: [] },
    ],
  },

  // ─── HALAL / MIDDLE EASTERN ──────────────────────────────────
  {
    name: "The Halal Guys",
    slug: "halal-guys",
    emoji: "🧆",
    category: "Middle Eastern",
    nycLocations: 25,
    priceRange: 1,
    orderingTip: "White sauce is 300+ cal. Ask for a light drizzle or switch to hot sauce (5 cal). Half rice/half salad cuts 200 cal.",
    items: [
      { name: "Chicken Over Rice (regular)", cal: 810, protein: 48, fat: 28, carbs: 88, sodium: 1620, fiber: 3, sugar: 4, tags: ["high-protein"] },
      { name: "Combo Over Rice (regular)", cal: 860, protein: 52, fat: 32, carbs: 86, sodium: 1780, fiber: 3, sugar: 4, tags: ["high-protein"] },
      { name: "Gyro Over Rice", cal: 780, protein: 38, fat: 34, carbs: 78, sodium: 1540, fiber: 3, sugar: 4, tags: [] },
      { name: "Falafel Over Rice", cal: 720, protein: 18, fat: 26, carbs: 102, sodium: 1280, fiber: 8, sugar: 4, tags: ["vegan"] },
      { name: "Chicken Over Salad", cal: 430, protein: 42, fat: 22, carbs: 18, sodium: 980, fiber: 4, sugar: 4, tags: ["high-protein", "low-carb"] },
      { name: "White Sauce (full)", cal: 330, protein: 1, fat: 34, carbs: 4, sodium: 180, fiber: 0, sugar: 2, tags: ["keto"] },
      { name: "Hot Sauce", cal: 5, protein: 0, fat: 0, carbs: 1, sodium: 140, fiber: 0, sugar: 0, tags: ["low-cal", "vegan"] },
    ],
  },

  // ─── DINER / FAMILY ──────────────────────────────────────────
  {
    name: "IHOP",
    slug: "ihop",
    emoji: "🥞",
    category: "Breakfast",
    nycLocations: 15,
    priceRange: 1,
    orderingTip: "Simple & Fit menu items are under 600 cal. Original Buttermilk stack (5) is 680 cal — go with 2 + eggs for better macros.",
    items: [
      { name: "Original Buttermilk Pancakes (short stack, 3)", cal: 410, protein: 10, fat: 14, carbs: 62, sodium: 1020, fiber: 2, sugar: 14, tags: [] },
      { name: "2 Eggs + 2 Bacon + Toast", cal: 380, protein: 24, fat: 22, carbs: 22, sodium: 680, fiber: 1, sugar: 3, tags: ["high-protein"] },
      { name: "Simple & Fit Veggie Omelette", cal: 330, protein: 28, fat: 14, carbs: 22, sodium: 740, fiber: 3, sugar: 4, tags: ["high-protein", "vegetarian"] },
      { name: "Turkey Bacon Omelette", cal: 410, protein: 36, fat: 22, carbs: 14, sodium: 1020, fiber: 1, sugar: 3, tags: ["high-protein", "low-carb"] },
      { name: "Chicken & Waffles", cal: 920, protein: 42, fat: 44, carbs: 88, sodium: 1680, fiber: 2, sugar: 24, tags: [] },
      { name: "Grilled Tilapia", cal: 350, protein: 38, fat: 14, carbs: 16, sodium: 620, fiber: 2, sugar: 4, tags: ["high-protein", "low-cal"] },
    ],
  },
  {
    name: "Denny's",
    slug: "dennys",
    emoji: "🍳",
    category: "Breakfast",
    nycLocations: 5,
    priceRange: 1,
    orderingTip: "Fit Fare menu is under 600 cal. Grand Slam can be 1,000+ cal — build your own with egg whites + turkey bacon.",
    items: [
      { name: "Fit Fare Veggie Skillet", cal: 340, protein: 22, fat: 14, carbs: 32, sodium: 780, fiber: 4, sugar: 5, tags: ["low-cal", "vegetarian"] },
      { name: "Build Your Own Grand Slam (2 egg, 2 bacon, toast)", cal: 420, protein: 26, fat: 24, carbs: 24, sodium: 840, fiber: 1, sugar: 3, tags: [] },
      { name: "Turkey BLT Sandwich", cal: 480, protein: 28, fat: 22, carbs: 42, sodium: 1220, fiber: 3, sugar: 5, tags: [] },
      { name: "Bourbon Chicken", cal: 520, protein: 42, fat: 16, carbs: 48, sodium: 1440, fiber: 3, sugar: 18, tags: ["high-protein"] },
      { name: "Loaded Veggie Omelette", cal: 480, protein: 34, fat: 28, carbs: 24, sodium: 1080, fiber: 3, sugar: 4, tags: ["high-protein", "vegetarian"] },
    ],
  },
  {
    name: "Applebee's",
    slug: "applebees",
    emoji: "🍎",
    category: "Diner",
    nycLocations: 8,
    priceRange: 2,
    orderingTip: "Irresist-A-Bowls are under 600 cal with 30g+ protein. Skip the appetizer sampler (1,800+ cal).",
    items: [
      { name: "Grilled Chicken Caesar Salad", cal: 530, protein: 42, fat: 28, carbs: 26, sodium: 1380, fiber: 4, sugar: 4, tags: ["high-protein"] },
      { name: "Blackened Cajun Salmon", cal: 520, protein: 44, fat: 28, carbs: 18, sodium: 1460, fiber: 3, sugar: 4, tags: ["high-protein", "low-carb"] },
      { name: "Top Sirloin (6oz)", cal: 280, protein: 40, fat: 12, carbs: 2, sodium: 720, fiber: 0, sugar: 0, tags: ["high-protein", "low-cal", "low-carb", "keto"] },
      { name: "Chicken Tenders Basket", cal: 950, protein: 52, fat: 52, carbs: 68, sodium: 2080, fiber: 3, sugar: 4, tags: [] },
      { name: "Southwest Steak Bowl", cal: 510, protein: 38, fat: 18, carbs: 48, sodium: 1620, fiber: 6, sugar: 6, tags: ["high-protein"] },
      { name: "Mozzarella Sticks", cal: 850, protein: 36, fat: 48, carbs: 68, sodium: 2240, fiber: 3, sugar: 8, tags: [] },
    ],
  },

  // ─── ADDITIONAL FAST CASUAL ──────────────────────────────────
  {
    name: "Chipotle-Style Bowls (Hale & Hearty)",
    slug: "hale-and-hearty",
    emoji: "🥣",
    category: "Healthy",
    nycLocations: 15,
    priceRange: 2,
    orderingTip: "Soups are surprisingly low-cal (150-280/bowl). Pair with a half salad for a 400 cal meal.",
    items: [
      { name: "Chicken Noodle Soup (bowl)", cal: 180, protein: 14, fat: 4, carbs: 22, sodium: 960, fiber: 1, sugar: 2, tags: ["low-cal"] },
      { name: "Tomato Basil Bisque (bowl)", cal: 260, protein: 6, fat: 16, carbs: 24, sodium: 820, fiber: 2, sugar: 8, tags: ["vegetarian"] },
      { name: "Lentil Soup (bowl)", cal: 220, protein: 14, fat: 4, carbs: 36, sodium: 780, fiber: 8, sugar: 4, tags: ["low-cal", "vegan"] },
      { name: "Grilled Chicken Salad", cal: 340, protein: 32, fat: 14, carbs: 22, sodium: 640, fiber: 4, sugar: 6, tags: ["high-protein", "low-cal"] },
      { name: "Turkey Chili (bowl)", cal: 280, protein: 22, fat: 8, carbs: 32, sodium: 880, fiber: 6, sugar: 4, tags: ["high-protein", "low-cal"] },
    ],
  },

  // ─── MORE CHAINS ─────────────────────────────────────────────
  {
    name: "sweetcatch poke",
    slug: "sweetcatch-poke",
    emoji: "🐟",
    category: "Healthy",
    nycLocations: 5,
    priceRange: 2,
    orderingTip: "White rice → brown rice saves nothing on cal but adds 3g fiber. Go light on sauces to keep sodium under 1000mg.",
    items: [
      { name: "Regular Poke Bowl (tuna)", cal: 520, protein: 32, fat: 14, carbs: 66, sodium: 880, fiber: 3, sugar: 8, tags: ["high-protein"] },
      { name: "Regular Poke Bowl (salmon)", cal: 540, protein: 30, fat: 18, carbs: 64, sodium: 860, fiber: 3, sugar: 8, tags: ["high-protein"] },
      { name: "Spicy Tuna Bowl", cal: 560, protein: 30, fat: 18, carbs: 68, sodium: 1020, fiber: 3, sugar: 10, tags: [] },
      { name: "Veggie Bowl (tofu)", cal: 440, protein: 16, fat: 12, carbs: 70, sodium: 640, fiber: 5, sugar: 6, tags: ["vegan"] },
    ],
  },
  {
    name: "Pokéworks",
    slug: "pokeworks",
    emoji: "🐟",
    category: "Healthy",
    nycLocations: 5,
    priceRange: 2,
    orderingTip: "Choose 'works' bowl over burrito to see your portions and avoid the oversized tortilla (+300 cal).",
    items: [
      { name: "Works Bowl (ahi tuna, regular)", cal: 510, protein: 28, fat: 14, carbs: 68, sodium: 920, fiber: 4, sugar: 10, tags: ["high-protein"] },
      { name: "Works Bowl (salmon, regular)", cal: 530, protein: 26, fat: 18, carbs: 66, sodium: 880, fiber: 4, sugar: 10, tags: [] },
      { name: "Poke Burrito (chicken)", cal: 680, protein: 34, fat: 20, carbs: 92, sodium: 1240, fiber: 4, sugar: 12, tags: [] },
      { name: "Super Greens Bowl", cal: 420, protein: 24, fat: 12, carbs: 56, sodium: 720, fiber: 6, sugar: 6, tags: ["high-protein"] },
    ],
  },
  {
    name: "Buffalo Wild Wings",
    slug: "buffalo-wild-wings",
    emoji: "🦬",
    category: "Chicken",
    nycLocations: 6,
    priceRange: 2,
    orderingTip: "Traditional wings (6pc, plain) = 430 cal, 36g protein. Avoid boneless (breaded = +200 cal). Dry rubs < wet sauces.",
    items: [
      { name: "Traditional Wings (6pc, plain)", cal: 430, protein: 36, fat: 30, carbs: 0, sodium: 240, fiber: 0, sugar: 0, tags: ["high-protein", "low-carb", "keto"] },
      { name: "Traditional Wings (6pc, honey BBQ)", cal: 530, protein: 36, fat: 30, carbs: 20, sodium: 1080, fiber: 0, sugar: 16, tags: ["high-protein"] },
      { name: "Boneless Wings (6pc, plain)", cal: 540, protein: 26, fat: 28, carbs: 44, sodium: 1420, fiber: 2, sugar: 0, tags: [] },
      { name: "Grilled Chicken Salad", cal: 480, protein: 38, fat: 24, carbs: 28, sodium: 1180, fiber: 4, sugar: 8, tags: ["high-protein"] },
      { name: "Garden Side Salad", cal: 80, protein: 4, fat: 4, carbs: 8, sodium: 120, fiber: 2, sugar: 4, tags: ["low-cal", "vegetarian"] },
    ],
  },
  {
    name: "Olive Garden",
    slug: "olive-garden",
    emoji: "🫒",
    category: "Diner",
    nycLocations: 4,
    priceRange: 2,
    orderingTip: "Each breadstick is 140 cal. Minestrone soup = 100 cal — start with soup to eat less. Grilled chicken is best entrée.",
    items: [
      { name: "Grilled Chicken Margherita", cal: 570, protein: 48, fat: 26, carbs: 32, sodium: 1380, fiber: 4, sugar: 6, tags: ["high-protein"] },
      { name: "Herb-Grilled Salmon", cal: 460, protein: 42, fat: 26, carbs: 12, sodium: 820, fiber: 2, sugar: 4, tags: ["high-protein", "low-carb"] },
      { name: "Chicken Alfredo", cal: 1010, protein: 54, fat: 48, carbs: 92, sodium: 1840, fiber: 4, sugar: 6, tags: [] },
      { name: "Minestrone Soup (bowl)", cal: 100, protein: 4, fat: 1, carbs: 18, sodium: 820, fiber: 3, sugar: 4, tags: ["low-cal", "vegan"] },
      { name: "House Salad (no dressing)", cal: 80, protein: 4, fat: 3, carbs: 10, sodium: 220, fiber: 2, sugar: 4, tags: ["low-cal", "vegetarian"] },
      { name: "Breadstick (1)", cal: 140, protein: 4, fat: 2, carbs: 26, sodium: 460, fiber: 1, sugar: 2, tags: ["vegan"] },
      { name: "Chicken Parm", cal: 1060, protein: 62, fat: 50, carbs: 86, sodium: 2700, fiber: 6, sugar: 12, tags: [] },
    ],
  },
  {
    name: "TGI Friday's",
    slug: "tgi-fridays",
    emoji: "🍽️",
    category: "Diner",
    nycLocations: 6,
    priceRange: 2,
    orderingTip: "Whiskey-Glazed burgers are 1,000+ cal. Grilled chicken or salmon entrées are 400-600 cal.",
    items: [
      { name: "Grilled Chicken & Broccoli", cal: 420, protein: 48, fat: 14, carbs: 24, sodium: 1080, fiber: 4, sugar: 4, tags: ["high-protein"] },
      { name: "Center-Cut Sirloin (6oz)", cal: 270, protein: 40, fat: 10, carbs: 4, sodium: 640, fiber: 0, sugar: 0, tags: ["high-protein", "low-cal", "low-carb"] },
      { name: "Dragon-Glazed Salmon", cal: 460, protein: 36, fat: 22, carbs: 28, sodium: 1240, fiber: 2, sugar: 16, tags: ["high-protein"] },
      { name: "BBQ Chicken Salad", cal: 540, protein: 38, fat: 26, carbs: 38, sodium: 1380, fiber: 4, sugar: 14, tags: ["high-protein"] },
      { name: "Loaded Potato Skins (half)", cal: 520, protein: 18, fat: 34, carbs: 36, sodium: 1020, fiber: 3, sugar: 2, tags: [] },
    ],
  },
  {
    name: "Cheesecake Factory",
    slug: "cheesecake-factory",
    emoji: "🍰",
    category: "Diner",
    nycLocations: 4,
    priceRange: 3,
    orderingTip: "SkinnyLicious menu items are 590 cal or less. Regular entrées average 1,500 cal. Share a dish.",
    items: [
      { name: "SkinnyLicious Chicken", cal: 570, protein: 46, fat: 20, carbs: 48, sodium: 1240, fiber: 4, sugar: 6, tags: ["high-protein"] },
      { name: "SkinnyLicious Shrimp", cal: 410, protein: 32, fat: 14, carbs: 38, sodium: 880, fiber: 4, sugar: 6, tags: ["high-protein"] },
      { name: "SkinnyLicious Turkey Burger", cal: 580, protein: 38, fat: 22, carbs: 56, sodium: 1060, fiber: 4, sugar: 8, tags: ["high-protein"] },
      { name: "Chicken Madeira", cal: 1540, protein: 88, fat: 80, carbs: 108, sodium: 3280, fiber: 6, sugar: 14, tags: [] },
      { name: "Pasta Carbonara", cal: 1920, protein: 58, fat: 98, carbs: 196, sodium: 2640, fiber: 8, sugar: 10, tags: [] },
      { name: "Original Cheesecake (slice)", cal: 830, protein: 14, fat: 56, carbs: 68, sodium: 480, fiber: 0, sugar: 52, tags: ["vegetarian"] },
      { name: "Fresh Strawberry Cheesecake", cal: 750, protein: 12, fat: 46, carbs: 72, sodium: 440, fiber: 2, sugar: 54, tags: ["vegetarian"] },
    ],
  },

  // ─── JUICE / SMOOTHIE ────────────────────────────────────────
  {
    name: "Juice Press",
    slug: "juice-press",
    emoji: "🧃",
    category: "Healthy",
    nycLocations: 20,
    priceRange: 3,
    orderingTip: "Green juices are 80-120 cal. Smoothie bowls can be 500+. Protein add-on (+$2) adds 20g.",
    items: [
      { name: "Doctor Green Juice", cal: 80, protein: 4, fat: 0, carbs: 18, sodium: 60, fiber: 0, sugar: 12, tags: ["low-cal", "vegan"] },
      { name: "Ginger Fireball", cal: 120, protein: 2, fat: 0, carbs: 28, sodium: 20, fiber: 0, sugar: 22, tags: ["low-cal", "vegan"] },
      { name: "Açaí Bowl", cal: 480, protein: 10, fat: 14, carbs: 82, sodium: 40, fiber: 8, sugar: 52, tags: ["vegan"] },
      { name: "PB&J Smoothie", cal: 420, protein: 18, fat: 16, carbs: 56, sodium: 120, fiber: 6, sugar: 36, tags: ["vegetarian"] },
      { name: "Green Protein Smoothie", cal: 320, protein: 22, fat: 8, carbs: 46, sodium: 140, fiber: 6, sugar: 28, tags: ["high-protein", "vegan"] },
    ],
  },
  {
    name: "Jamba Juice",
    slug: "jamba-juice",
    emoji: "🥤",
    category: "Healthy",
    nycLocations: 10,
    priceRange: 2,
    orderingTip: "Smoothies average 350-500 cal (small). Fresh juice or a Whirl'd White smoothie (small, 210 cal) is lighter.",
    items: [
      { name: "Caribbean Passion (small)", cal: 280, protein: 2, fat: 1, carbs: 68, sodium: 35, fiber: 3, sugar: 60, tags: ["vegan"] },
      { name: "PB & Banana Protein (small)", cal: 430, protein: 14, fat: 12, carbs: 72, sodium: 300, fiber: 4, sugar: 56, tags: ["vegetarian"] },
      { name: "Greens 'n Ginger (small)", cal: 180, protein: 3, fat: 1, carbs: 42, sodium: 80, fiber: 4, sugar: 32, tags: ["low-cal", "vegan"] },
      { name: "Mega Mango (small)", cal: 300, protein: 2, fat: 1, carbs: 72, sodium: 30, fiber: 4, sugar: 58, tags: ["vegan"] },
      { name: "Açaí Bowl", cal: 510, protein: 8, fat: 12, carbs: 96, sodium: 55, fiber: 10, sugar: 64, tags: ["vegan"] },
    ],
  },

  // ─── ADDITIONAL POPULAR NYC ──────────────────────────────────
  {
    name: "Chili's",
    slug: "chilis",
    emoji: "🌶️",
    category: "Diner",
    nycLocations: 4,
    priceRange: 2,
    orderingTip: "Guiltless Grill items are 600 cal or less. Regular burgers and fajitas are 1,200+.",
    items: [
      { name: "6oz Sirloin with Grilled Avocado", cal: 450, protein: 42, fat: 24, carbs: 14, sodium: 1040, fiber: 4, sugar: 2, tags: ["high-protein", "low-carb"] },
      { name: "Ancho Salmon", cal: 510, protein: 40, fat: 28, carbs: 20, sodium: 1440, fiber: 3, sugar: 6, tags: ["high-protein"] },
      { name: "Chicken Caesar Salad (half)", cal: 380, protein: 28, fat: 22, carbs: 18, sodium: 860, fiber: 3, sugar: 2, tags: ["high-protein"] },
      { name: "Oldtimer Burger", cal: 1080, protein: 56, fat: 62, carbs: 72, sodium: 2180, fiber: 3, sugar: 12, tags: [] },
      { name: "Chicken Crispers (5pc)", cal: 1050, protein: 42, fat: 58, carbs: 88, sodium: 2420, fiber: 3, sugar: 6, tags: [] },
    ],
  },
  {
    name: "KFC",
    slug: "kfc",
    emoji: "🍗",
    category: "Chicken",
    nycLocations: 40,
    priceRange: 1,
    orderingTip: "Grilled chicken breast (180 cal, 35g protein) is the sleeper menu item. Extra crispy adds 100+ cal.",
    items: [
      { name: "Original Recipe Breast", cal: 390, protein: 39, fat: 21, carbs: 11, sodium: 1190, fiber: 0, sugar: 0, tags: ["high-protein", "low-carb"] },
      { name: "Grilled Chicken Breast", cal: 180, protein: 35, fat: 4, carbs: 0, sodium: 650, fiber: 0, sugar: 0, tags: ["low-cal", "high-protein", "low-carb", "keto"] },
      { name: "Extra Crispy Breast", cal: 490, protein: 34, fat: 29, carbs: 17, sodium: 1190, fiber: 1, sugar: 0, tags: [] },
      { name: "Famous Bowl", cal: 710, protein: 26, fat: 34, carbs: 76, sodium: 2080, fiber: 5, sugar: 2, tags: [] },
      { name: "Coleslaw (individual)", cal: 170, protein: 1, fat: 10, carbs: 22, sodium: 180, fiber: 2, sugar: 14, tags: ["vegetarian"] },
      { name: "Mashed Potatoes & Gravy", cal: 120, protein: 2, fat: 4, carbs: 19, sodium: 520, fiber: 1, sugar: 0, tags: ["low-cal", "vegetarian"] },
      { name: "Green Beans", cal: 25, protein: 1, fat: 0, carbs: 4, sodium: 260, fiber: 2, sugar: 1, tags: ["low-cal", "vegan"] },
      { name: "Chicken Pot Pie", cal: 720, protein: 26, fat: 40, carbs: 62, sodium: 1640, fiber: 3, sugar: 6, tags: [] },
    ],
  },

  // ─── BOBA / TEA ──────────────────────────────────────────────
  {
    name: "Kung Fu Tea",
    slug: "kung-fu-tea",
    emoji: "🧋",
    category: "Coffee & Bakery",
    nycLocations: 40,
    priceRange: 1,
    orderingTip: "Ask for 25% or 0% sugar — saves 100-200 cal. Boba adds ~100 cal per serving. Plain tea = 0 cal.",
    items: [
      { name: "Classic Milk Tea (50% sugar)", cal: 280, protein: 2, fat: 4, carbs: 60, sodium: 80, fiber: 0, sugar: 48, tags: ["vegetarian"] },
      { name: "Classic Milk Tea (0% sugar)", cal: 140, protein: 2, fat: 4, carbs: 24, sodium: 80, fiber: 0, sugar: 12, tags: ["vegetarian"] },
      { name: "Mango Slush", cal: 320, protein: 1, fat: 0, carbs: 80, sodium: 20, fiber: 1, sugar: 68, tags: ["vegan"] },
      { name: "Taro Milk Tea", cal: 340, protein: 3, fat: 6, carbs: 68, sodium: 100, fiber: 1, sugar: 52, tags: ["vegetarian"] },
      { name: "Tapioca Pearls (add-on)", cal: 100, protein: 0, fat: 0, carbs: 24, sodium: 0, fiber: 0, sugar: 10, tags: ["vegan"] },
      { name: "Green Tea (plain)", cal: 0, protein: 0, fat: 0, carbs: 0, sodium: 0, fiber: 0, sugar: 0, tags: ["low-cal", "vegan"] },
    ],
  },
  {
    name: "Tiger Sugar",
    slug: "tiger-sugar",
    emoji: "🐯",
    category: "Coffee & Bakery",
    nycLocations: 8,
    priceRange: 2,
    orderingTip: "Their signature Brown Sugar Boba is 650+ cal. Ask for less sugar and sub oat milk to cut 150 cal.",
    items: [
      { name: "Brown Sugar Boba Milk", cal: 660, protein: 8, fat: 18, carbs: 118, sodium: 180, fiber: 0, sugar: 92, tags: [] },
      { name: "Brown Sugar Boba Milk (less sugar)", cal: 480, protein: 8, fat: 18, carbs: 78, sodium: 180, fiber: 0, sugar: 58, tags: [] },
      { name: "Tiger Black Tea (no sugar)", cal: 20, protein: 0, fat: 0, carbs: 4, sodium: 10, fiber: 0, sugar: 2, tags: ["low-cal", "vegan"] },
      { name: "Cream Mousse Green Tea", cal: 380, protein: 4, fat: 14, carbs: 58, sodium: 120, fiber: 0, sugar: 46, tags: ["vegetarian"] },
    ],
  },

  // ─── ACAI / BOWL ─────────────────────────────────────────────
  {
    name: "Playa Bowls",
    slug: "playa-bowls",
    emoji: "🥥",
    category: "Healthy",
    nycLocations: 12,
    priceRange: 2,
    orderingTip: "Small size is 300-400 cal. Large can be 700+. Ask for no granola to cut 150 cal.",
    items: [
      { name: "Açaí Bowl (small)", cal: 340, protein: 6, fat: 8, carbs: 64, sodium: 30, fiber: 8, sugar: 40, tags: ["vegan"] },
      { name: "Açaí Bowl (large)", cal: 620, protein: 10, fat: 14, carbs: 116, sodium: 50, fiber: 14, sugar: 72, tags: ["vegan"] },
      { name: "Pitaya Bowl (small)", cal: 310, protein: 4, fat: 4, carbs: 68, sodium: 20, fiber: 6, sugar: 44, tags: ["vegan"] },
      { name: "Green Bowl (small)", cal: 280, protein: 8, fat: 6, carbs: 52, sodium: 40, fiber: 6, sugar: 32, tags: ["vegan"] },
      { name: "Banana PB&J Smoothie", cal: 440, protein: 14, fat: 16, carbs: 64, sodium: 160, fiber: 6, sugar: 42, tags: ["vegetarian"] },
    ],
  },
];

// Remove empty/duplicate chains
export const CHAINS = RESTAURANT_CHAINS.filter(c => c.items.length > 0 && c.nycLocations > 0);

// All categories
export const CATEGORIES = [...new Set(CHAINS.map(c => c.category))].sort();

// All unique tags
export const ALL_TAGS = [...new Set(CHAINS.flatMap(c => c.items.flatMap(i => i.tags ?? [])))].sort();

// Diet filter definitions
export interface DietFilter {
  id: string;
  label: string;
  emoji: string;
  description: string;
  filter: (item: MenuItem) => boolean;
}

export const DIET_FILTERS: DietFilter[] = [
  { id: "low-cal", label: "Under 400 Cal", emoji: "🔥", description: "Meals under 400 calories", filter: i => i.cal <= 400 },
  { id: "under-600", label: "Under 600 Cal", emoji: "✅", description: "Meals under 600 calories", filter: i => i.cal <= 600 },
  { id: "high-protein", label: "High Protein", emoji: "💪", description: "25g+ protein per serving", filter: i => i.protein >= 25 },
  { id: "low-carb", label: "Low Carb", emoji: "🥑", description: "Under 30g carbs", filter: i => i.carbs <= 30 },
  { id: "keto", label: "Keto Friendly", emoji: "🥓", description: "Under 20g carbs, high fat", filter: i => i.carbs <= 20 },
  { id: "low-sodium", label: "Low Sodium", emoji: "🧂", description: "Under 600mg sodium", filter: i => i.sodium <= 600 },
  { id: "vegan", label: "Vegan", emoji: "🌱", description: "No animal products", filter: i => i.tags?.includes("vegan") ?? false },
  { id: "vegetarian", label: "Vegetarian", emoji: "🥚", description: "No meat", filter: i => (i.tags?.includes("vegetarian") || i.tags?.includes("vegan")) ?? false },
];

// Stats
export const RESTAURANT_STATS = {
  totalChains: CHAINS.length,
  totalItems: CHAINS.reduce((s, c) => s + c.items.length, 0),
  totalNycLocations: CHAINS.reduce((s, c) => s + c.nycLocations, 0),
  avgCalories: Math.round(CHAINS.flatMap(c => c.items).reduce((s, i) => s + i.cal, 0) / CHAINS.flatMap(c => c.items).length),
  lowestCalItem: CHAINS.flatMap(c => c.items.map(i => ({ ...i, chain: c.name }))).sort((a, b) => a.cal - b.cal)[0],
  highestProteinItem: CHAINS.flatMap(c => c.items.map(i => ({ ...i, chain: c.name }))).sort((a, b) => b.protein - a.protein)[0],
};
