/* Shared route data — importable from both server and client components */

export interface Route {
  name: string;
  borough: "Manhattan" | "Brooklyn" | "Queens" | "Bronx" | "Staten Island";
  distance: string;
  distanceMi: number;
  surface: "Paved" | "Dirt" | "Boardwalk" | "Elevated" | "Mixed";
  difficulty: "Easy" | "Moderate" | "Hilly";
  description: string;
  carFree: boolean;
  icon: string;
  lat: number;
  lng: number;
  highlights: string[];
  tag?: "race" | null; // "race" = NYRR official race route
}

export const ROUTES: Route[] = [
  {
    name: "Central Park Full Loop",
    borough: "Manhattan",
    distance: "6.1 mi",
    distanceMi: 6.1,
    surface: "Paved",
    difficulty: "Moderate",
    description: "The classic NYC run — counterclockwise, car-free. Gentle hills on the north end.",
    carFree: true,
    icon: "🌳",
    lat: 40.7829,
    lng: -73.9654,
    highlights: ["Car-free", "Water fountains", "Restrooms"],
  },
  {
    name: "Central Park Reservoir (Bridle Path)",
    borough: "Manhattan",
    distance: "1.58 mi",
    distanceMi: 1.58,
    surface: "Dirt",
    difficulty: "Easy",
    description: "Softer surface, great skyline views, less crowded than the main loop.",
    carFree: true,
    icon: "🏞️",
    lat: 40.785,
    lng: -73.9625,
    highlights: ["Soft surface", "Skyline views", "Low traffic"],
  },
  {
    name: "Hudson River Greenway",
    borough: "Manhattan",
    distance: "12.9 mi",
    distanceMi: 12.9,
    surface: "Paved",
    difficulty: "Easy",
    description: "Manhattan's west side waterfront — Battery Park to Inwood. Flat, scenic, car-free.",
    carFree: true,
    icon: "🌊",
    lat: 40.7425,
    lng: -74.0099,
    highlights: ["Waterfront", "Flat", "Bike lane separated"],
  },
  {
    name: "East River Greenway (South)",
    borough: "Manhattan",
    distance: "4.4 mi",
    distanceMi: 4.4,
    surface: "Paved",
    difficulty: "Easy",
    description: "Midtown to Battery Park with stunning bridge views. Best at sunset.",
    carFree: true,
    icon: "🌉",
    lat: 40.7084,
    lng: -74.0032,
    highlights: ["Bridge views", "Sunset spot", "Waterfront"],
  },
  {
    name: "The High Line",
    borough: "Manhattan",
    distance: "1.5 mi",
    distanceMi: 1.5,
    surface: "Elevated",
    difficulty: "Easy",
    description: "Elevated walking path — go before 9am. Too crowded for running later.",
    carFree: true,
    icon: "🌿",
    lat: 40.7480,
    lng: -74.0048,
    highlights: ["Elevated", "Art installations", "Walk only after 9am"],
  },
  {
    name: "Prospect Park Loop",
    borough: "Brooklyn",
    distance: "3.35 mi",
    distanceMi: 3.35,
    surface: "Paved",
    difficulty: "Moderate",
    description: "Brooklyn's Central Park — car-free, beautiful rolling hills. Run counterclockwise.",
    carFree: true,
    icon: "🌳",
    lat: 40.6602,
    lng: -73.9690,
    highlights: ["Car-free", "Rolling hills", "Restrooms"],
  },
  {
    name: "Brooklyn Waterfront Greenway",
    borough: "Brooklyn",
    distance: "14+ mi",
    distanceMi: 14,
    surface: "Paved",
    difficulty: "Easy",
    description: "Dumbo to Red Hook to Bay Ridge waterfront. Flat with incredible harbor views.",
    carFree: true,
    icon: "🌊",
    lat: 40.7024,
    lng: -73.9897,
    highlights: ["Harbor views", "Flat", "Multiple access points"],
  },
  {
    name: "Brooklyn Bridge",
    borough: "Brooklyn",
    distance: "1.3 mi",
    distanceMi: 1.3,
    surface: "Paved",
    difficulty: "Easy",
    description: "Iconic but crowded — run early or late. Slight incline from Brooklyn side.",
    carFree: false,
    icon: "🌉",
    lat: 40.7061,
    lng: -73.9969,
    highlights: ["Iconic views", "Best before 7am", "Photo ops"],
  },
  {
    name: "Flushing Meadows Corona Park",
    borough: "Queens",
    distance: "2.5 mi",
    distanceMi: 2.5,
    surface: "Paved",
    difficulty: "Easy",
    description: "Past the Unisphere and USTA tennis center. Wide paths, flat, family-friendly.",
    carFree: true,
    icon: "🌐",
    lat: 40.7400,
    lng: -73.8407,
    highlights: ["Unisphere", "Wide paths", "Family-friendly"],
  },
  {
    name: "Forest Park (Oak Trail)",
    borough: "Queens",
    distance: "3.5 mi",
    distanceMi: 3.5,
    surface: "Dirt",
    difficulty: "Hilly",
    description: "Queens' hidden gem — largest continuous oak forest in NYC. Real trail running.",
    carFree: true,
    icon: "🌲",
    lat: 40.7008,
    lng: -73.8540,
    highlights: ["Trail running", "Forest canopy", "Wildlife"],
  },
  {
    name: "Van Cortlandt Park (XC Trail)",
    borough: "Bronx",
    distance: "3.1 mi",
    distanceMi: 3.1,
    surface: "Dirt",
    difficulty: "Hilly",
    description: "Classic cross-country course. The Putnam Trail is flatter if you want an easier option.",
    carFree: true,
    icon: "⛰️",
    lat: 40.8972,
    lng: -73.8862,
    highlights: ["XC course", "Historic", "Putnam Trail option"],
  },
  {
    name: "Pelham Bay / Orchard Beach",
    borough: "Bronx",
    distance: "1.8 mi",
    distanceMi: 1.8,
    surface: "Paved",
    difficulty: "Easy",
    description: "NYC's largest park — feels like you left the city. Flat shore path.",
    carFree: true,
    icon: "🏖️",
    lat: 40.8686,
    lng: -73.7940,
    highlights: ["Beachfront", "Nature escape", "Birding"],
  },
  {
    name: "Staten Island Greenbelt (White Trail)",
    borough: "Staten Island",
    distance: "8+ mi",
    distanceMi: 8,
    surface: "Dirt",
    difficulty: "Hilly",
    description: "NYC's best trail running — dense forest, rolling hills. Feels like upstate.",
    carFree: true,
    icon: "🌲",
    lat: 40.5862,
    lng: -74.1467,
    highlights: ["Dense forest", "Trail running", "Best in fall"],
  },
  {
    name: "FDR Boardwalk",
    borough: "Staten Island",
    distance: "2.5 mi",
    distanceMi: 2.5,
    surface: "Boardwalk",
    difficulty: "Easy",
    description: "South Beach to Midland Beach — ocean views, flat boardwalk. Great morning run.",
    carFree: true,
    icon: "🏖️",
    lat: 40.5750,
    lng: -74.0750,
    highlights: ["Ocean views", "Flat", "Boardwalk surface"],
  },

  // ── NYRR Race Routes ──────────────────────────────────────────
  {
    name: "NYC Marathon Course",
    borough: "Manhattan",
    distance: "26.2 mi",
    distanceMi: 26.2,
    surface: "Paved",
    difficulty: "Hilly",
    description: "All five boroughs — Staten Island to Central Park. The world's largest marathon. First Sunday in November.",
    carFree: true,
    icon: "🏅",
    lat: 40.7711,
    lng: -73.9741,
    highlights: ["All 5 boroughs", "26.2 miles", "NYRR official"],
    tag: "race",
  },
  {
    name: "Brooklyn Half Marathon",
    borough: "Brooklyn",
    distance: "13.1 mi",
    distanceMi: 13.1,
    surface: "Paved",
    difficulty: "Moderate",
    description: "Prospect Park to Coney Island Boardwalk. One of NYC's most scenic half marathons. May.",
    carFree: true,
    icon: "🏅",
    lat: 40.6602,
    lng: -73.9690,
    highlights: ["Prospect Park start", "Boardwalk finish", "NYRR official"],
    tag: "race",
  },
  {
    name: "NYC Half Marathon",
    borough: "Manhattan",
    distance: "13.1 mi",
    distanceMi: 13.1,
    surface: "Paved",
    difficulty: "Moderate",
    description: "Brooklyn to Manhattan — crosses the Manhattan Bridge, finishes in Central Park. March.",
    carFree: true,
    icon: "🏅",
    lat: 40.7580,
    lng: -73.9855,
    highlights: ["Bridge crossing", "Central Park finish", "NYRR official"],
    tag: "race",
  },
  {
    name: "Queens 10K",
    borough: "Queens",
    distance: "6.2 mi",
    distanceMi: 6.2,
    surface: "Paved",
    difficulty: "Easy",
    description: "Flushing Meadows Corona Park loop — flat, fast, past the Unisphere. June.",
    carFree: true,
    icon: "🏅",
    lat: 40.7400,
    lng: -73.8407,
    highlights: ["Flat & fast", "Unisphere", "NYRR official"],
    tag: "race",
  },
  {
    name: "Bronx 10 Mile",
    borough: "Bronx",
    distance: "10 mi",
    distanceMi: 10,
    surface: "Paved",
    difficulty: "Hilly",
    description: "Van Cortlandt Park to the Grand Concourse — rolling hills with Bronx culture. September.",
    carFree: true,
    icon: "🏅",
    lat: 40.8972,
    lng: -73.8862,
    highlights: ["Rolling hills", "Bronx neighborhoods", "NYRR official"],
    tag: "race",
  },
  {
    name: "Staten Island Half Marathon",
    borough: "Staten Island",
    distance: "13.1 mi",
    distanceMi: 13.1,
    surface: "Paved",
    difficulty: "Hilly",
    description: "Through the Greenbelt and along the waterfront. A challenging but beautiful course. October.",
    carFree: true,
    icon: "🏅",
    lat: 40.5862,
    lng: -74.1467,
    highlights: ["Greenbelt trails", "Waterfront views", "NYRR official"],
    tag: "race",
  },
];
