import type { RestaurantMenu } from "../types";

export function createCaribbeanTemplate(restaurantName: string, restaurantId: string): RestaurantMenu {
  return {
    restaurantId,
    restaurantName,
    restaurantType: "other",
    cuisine: "Caribbean",
    hasDrinks: true,
    items: [
      {
        id: "caribbean-jerk-chicken-cabbage",
        name: "Jerk Chicken (No Skin) + Steamed Cabbage",
        category: "protein-plates",
        description: "Jerk-seasoned dark meat, skin removed, with steamed cabbage instead of rice & peas",
        calories: 380,
        protein: 34,
        carbs: 12,
        fat: 22,
        saturatedFat: 6,
        fiber: 4,
        sodium: 680,
        pulseScore: 84,
        badges: ["High Protein", "Low Carb"],
        modifierHint: "Skip rice & peas to save ~300 cal. Steamed cabbage is traditional and ~30 cal.",
        isDrink: false,
        isBestPick: true,
        availabilityStatus: "active",
        source: { provider: "usda-composed", components: [{ fdcId: 171477, grams: 200 }, { fdcId: 170394, grams: 150 }], lastVerified: "2026-05-04" },
      },
      {
        id: "caribbean-jerk-chicken-full",
        name: "Jerk Chicken Plate (Rice & Peas + Plantains)",
        category: "rice",
        description: "The classic platter — jerk chicken with rice & peas and fried plantains",
        calories: 780,
        protein: 36,
        carbs: 82,
        fat: 32,
        saturatedFat: 10,
        fiber: 5,
        sodium: 920,
        pulseScore: 32,
        badges: ["🎯 Realistic Treat"],
        modifierHint: "Full platter is 780 cal — a whole meal. Skip snacks for 4 hours after.",
        isDrink: false,
        isRealisticTreat: true,
        availabilityStatus: "active",
        source: { provider: "usda-composed", components: [{ fdcId: 171477, grams: 200 }, { fdcId: 169756, grams: 180 }, { fdcId: 170393, grams: 100 }], lastVerified: "2026-05-04" },
      },
      {
        id: "caribbean-curry-chicken",
        name: "Curry Chicken (Half Rice)",
        category: "rice",
        description: "Jamaican curry chicken with half portion of white rice",
        calories: 440,
        protein: 30,
        carbs: 36,
        fat: 18,
        saturatedFat: 6,
        sodium: 740,
        pulseScore: 66,
        badges: ["High Protein"],
        modifierHint: "Ask for half rice and extra vegetables. Curry sauce is moderate cal if not coconut-heavy.",
        isDrink: false,
        availabilityStatus: "active",
        source: { provider: "usda-composed", components: [{ fdcId: 171477, grams: 170 }, { fdcId: 169756, grams: 90 }], lastVerified: "2026-05-04" },
      },
      {
        id: "caribbean-oxtail-cabbage",
        name: "Oxtail + Steamed Cabbage (No Rice)",
        category: "protein-plates",
        description: "Braised oxtail with steamed cabbage — skip the rice to keep calories in check",
        calories: 460,
        protein: 32,
        carbs: 14,
        fat: 30,
        saturatedFat: 12,
        fiber: 4,
        sodium: 680,
        pulseScore: 52,
        badges: ["Low Carb"],
        modifierHint: "Oxtail is rich — pair with low-cal sides. One serving of oxtail is plenty.",
        isDrink: false,
        availabilityStatus: "active",
        source: { provider: "usda-composed", components: [{ fdcId: 174032, grams: 180 }, { fdcId: 170394, grams: 150 }], lastVerified: "2026-05-04" },
      },
      {
        id: "caribbean-brown-stew-fish",
        name: "Brown Stew Fish + Steamed Veg",
        category: "protein-plates",
        description: "Stewed fish with peppers and onions, served with steamed vegetables",
        calories: 320,
        protein: 28,
        carbs: 18,
        fat: 14,
        saturatedFat: 3,
        fiber: 3,
        sodium: 580,
        pulseScore: 78,
        badges: ["High Protein"],
        modifierHint: "Fish is lean protein. Stew sauce is moderate cal — pair with veg instead of rice.",
        isDrink: false,
        availabilityStatus: "active",
        source: { provider: "usda-composed", components: [{ fdcId: 175159, grams: 170 }, { fdcId: 170394, grams: 120 }], lastVerified: "2026-05-04" },
      },
      {
        id: "caribbean-callaloo",
        name: "Callaloo + Boiled Green Banana",
        category: "sides",
        description: "Steamed callaloo greens with boiled green banana — traditional and nutritious",
        calories: 180,
        protein: 6,
        carbs: 32,
        fat: 4,
        saturatedFat: 1,
        fiber: 6,
        sodium: 320,
        pulseScore: 53,
        badges: ["Plant-Based", "High Fiber"],
        isDrink: false,
        availabilityStatus: "active",
        source: { provider: "usda-composed", components: [{ fdcId: 170394, grams: 100 }, { fdcId: 173944, grams: 100 }], lastVerified: "2026-05-04" },
      },
      {
        id: "caribbean-sorrel",
        name: "Sorrel Drink (Unsweetened or Light)",
        category: "drinks",
        description: "Hibiscus-based Caribbean drink — ask for unsweetened or lightly sweetened",
        calories: 30,
        protein: 0,
        carbs: 8,
        fat: 0,
        saturatedFat: 0,
        sodium: 10,
        pulseScore: 64,
        drinkScore: 64,
        badges: ["Under 50 Cal"],
        modifierHint: "Full-sugar sorrel is 150+ cal. Ask for unsweetened or light.",
        isDrink: true,
        sweetenerType: "minimal-sugar",
        availabilityStatus: "active",
        source: { provider: "curated", lastVerified: "2026-05-04" },
      },
      {
        id: "caribbean-water",
        name: "Bottled Water or Coconut Water",
        category: "drinks",
        description: "Plain water or a small coconut water (~60 cal)",
        calories: 30,
        protein: 0,
        carbs: 8,
        fat: 0,
        saturatedFat: 0,
        sodium: 50,
        pulseScore: 68,
        drinkScore: 68,
        badges: ["Under 50 Cal"],
        isDrink: true,
        sweetenerType: "none",
        availabilityStatus: "active",
        source: { provider: "curated", lastVerified: "2026-05-04" },
      },
    ],
    source: "cuisine-template",
    lastUpdated: "2026-05-04",
    editorialTopPickId: "caribbean-jerk-chicken-cabbage",
  };
}
