import type { RestaurantMenu } from "../types";

export function createChickenTemplate(restaurantName: string, restaurantId: string): RestaurantMenu {
  return {
    restaurantId,
    restaurantName,
    restaurantType: "fast-food",
    cuisine: "Chicken",
    hasDrinks: true,
    items: [
      {
        id: "chicken-grilled-tenders",
        name: "Grilled Chicken Tenders (3pc)",
        category: "protein-plates",
        description: "Grilled chicken strips — skip the fried, save 200+ cal",
        calories: 280,
        protein: 34,
        carbs: 4,
        fat: 14,
        saturatedFat: 4,
        sodium: 620,
        pulseScore: 82,
        badges: ["High Protein", "Under 300 Cal"],
        modifierHint: "Grilled instead of fried saves ~200 cal and cuts fat in half.",
        isDrink: false,
        isBestPick: true,
        availabilityStatus: "active",
        source: { provider: "usda-composed", components: [{ fdcId: 171477, grams: 170 }], lastVerified: "2026-05-04" },
      },
      {
        id: "chicken-grilled-sandwich",
        name: "Grilled Chicken Sandwich (No Mayo)",
        category: "sandwiches",
        description: "Grilled chicken breast on a bun with lettuce and tomato, no mayo",
        calories: 380,
        protein: 32,
        carbs: 36,
        fat: 10,
        saturatedFat: 3,
        fiber: 2,
        sodium: 720,
        pulseScore: 73,
        badges: ["High Protein"],
        modifierHint: "Skip mayo to save ~100 cal. Hot sauce or mustard instead.",
        isDrink: false,
        availabilityStatus: "active",
        source: { provider: "usda-composed", components: [{ fdcId: 171477, grams: 140 }, { fdcId: 169735, grams: 60 }], lastVerified: "2026-05-04" },
      },
      {
        id: "chicken-wings-3",
        name: "Fried Wings (3pc) + Hot Sauce",
        category: "protein-plates",
        description: "Three fried wings — keep it to 3 and skip the blue cheese/ranch",
        calories: 420,
        protein: 28,
        carbs: 16,
        fat: 28,
        saturatedFat: 8,
        sodium: 880,
        pulseScore: 38,
        badges: ["🎯 Realistic Treat"],
        modifierHint: "3 wings is ~420 cal. Every extra wing is +140 cal. Skip ranch/blue cheese (150 cal).",
        isDrink: false,
        isRealisticTreat: true,
        availabilityStatus: "active",
        source: { provider: "usda-composed", components: [{ fdcId: 171477, grams: 180 }], lastVerified: "2026-05-04" },
      },
      {
        id: "chicken-salad-grilled",
        name: "Grilled Chicken Salad (Dressing on Side)",
        category: "salads",
        description: "Grilled chicken over mixed greens with vinaigrette on the side",
        calories: 310,
        protein: 30,
        carbs: 14,
        fat: 14,
        saturatedFat: 4,
        fiber: 4,
        sodium: 480,
        pulseScore: 86,
        badges: ["High Protein", "Low Carb"],
        modifierHint: "Dip your fork in the dressing — don't pour. Saves ~60 cal.",
        isDrink: false,
        availabilityStatus: "active",
        source: { provider: "usda-composed", components: [{ fdcId: 171477, grams: 140 }, { fdcId: 168462, grams: 100 }], lastVerified: "2026-05-04" },
      },
      {
        id: "chicken-rice-beans",
        name: "Grilled Chicken + Rice & Beans (Half Rice)",
        category: "rice",
        description: "Grilled chicken with yellow rice and beans — ask for half rice",
        calories: 460,
        protein: 32,
        carbs: 44,
        fat: 16,
        saturatedFat: 5,
        fiber: 6,
        sodium: 780,
        pulseScore: 64,
        badges: ["High Protein", "High Fiber"],
        modifierHint: "Half rice saves ~150 cal. Beans add fiber and protein.",
        isDrink: false,
        availabilityStatus: "active",
        source: { provider: "usda-composed", components: [{ fdcId: 171477, grams: 140 }, { fdcId: 169756, grams: 90 }, { fdcId: 175223, grams: 80 }], lastVerified: "2026-05-04" },
      },
      {
        id: "chicken-water",
        name: "Bottled Water",
        category: "drinks",
        description: "Water instead of soda — save 150+ cal",
        calories: 0,
        protein: 0,
        carbs: 0,
        fat: 0,
        saturatedFat: 0,
        sodium: 0,
        pulseScore: 68,
        drinkScore: 68,
        badges: ["Zero Cal"],
        modifierHint: "A regular soda adds ~150 cal of pure sugar.",
        isDrink: true,
        sweetenerType: "none",
        availabilityStatus: "active",
        source: { provider: "curated", lastVerified: "2026-05-04" },
      },
    ],
    source: "cuisine-template",
    lastUpdated: "2026-05-04",
    editorialTopPickId: "chicken-grilled-tenders",
  };
}
